<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>
	<div class="wrapper" style="border: 1px dotted #000;background: #fff;width:24cm;margin: 0 auto;min-height: 28cm;padding: 0.5cm;">
			 <style>
		    	.wrapper{
		    		width: 100%;
		    		margin: 0px;
		    		padding: 0px;
		    	}
		    	.contain{
		    		width: 1024px;
		    		margin: 0 auto;
		    	}
				table {
		    		border-collapse: collapse;
		    		width: 100%;
				}
		    </style>
			<table width="100%">
						<tr>
							<td width="20%" align="center">
								<img style="max-height:100px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br>
								<span style="font-family: Freestyle Script;font-size: 20px;"></span>						
							</td>
							<td width="60%">
								<table   style="text-align:center;border:solid 1px #FFF;">
									<tr style="list-style:12px; font-family:  Khmer OS Muol; font-size:55px;font-weight: bold; color:#004D99;">
										<td><img style="width: 25%;height: 25px;" src="<?php echo $this->baseUrl().'/images/kbach1.png'?>"></td>
										<td>ព័ត៌មានផ្លាកម៉ុង</td>
									</tr>
					
								</table>
							</td>
							<td width="20%" >&nbsp;</td>
						</tr>
				</table>
			  	<tr>
		  		<table style="font-size:15px;font-family: Khmer OS Battambang, Times New Roman; line-height:58px; margin-right:">	
		  				<tr style="list-style:25px; font-family:  Khmer OS Muol; font-size:38px;font-weight: bold; list-style:none; color:red;">
		  					<td>
		  						<li>ទីតាំង:..........................................................</li>
		  						<li>TELL:............................................................</li>
		  					</td>
		  				</tr>
		  				<tr style="list-style:25px; font-family:  Khmer OS Muol; font-size:25px;font-weight: bold; color:#009900;">
		  					<td>
		  						 &#x25BA;ខាងប្រុស (រស់ឬស្លាប់)
		  					</td>
		  				</tr>
		  				<tr align="center" style="list-style:25px; font-family:  Khmer OS Muol; font-size:25px;font-weight: bold; padding-left:12px; color:#009900;">
		  					<td>
		  						<li>ឈ្មោះ(ខ្មែរ):.....................................................................................</li>
		  						<li>ឈ្មោះ(ចិន):.....................................................................................</li>
		  					</td>
		  				</tr>
		  				<tr style="list-style:25px; font-family:  Khmer OS Muol; font-size:25px;font-weight: bold; color:#009900;">
		  					<td>
		  						 &#x25BA;ខាងស្រី (រស់ឬស្លាប់)
		  					</td>
		  				</tr>
		  				<tr align="center"  style="list-style:25px; font-family:  Khmer OS Muol; font-size:25px;font-weight: bold; padding-left:12px; color:#009900;">
		  					<td>
		  						<li>ឈ្មោះ(ខ្មែរ):.....................................................................................</li>
		  						<li>ឈ្មោះ(ចិន):.....................................................................................</li>
		  					</td>
		  				</tr>
		  				<tr style="font-family:  Khmer OS Muol; font-size:25px;font-weight: bold; list-style:none; color:#004D99;">
			  				<td>
		  						<li>&#x25BA;ថ្ងៃកើត................................/.............................../.................................</li>
		  						<li>&#x25BA;ថ្ងៃស្លាប់................................/.............................../................................</li>
		  						<li>&#x25BA;ស្រុកកំណើតខាងប្រុស.........................................................................
		  						<br>.................................................................................................................</li>
		  						<li>&#x25BA;ឆ្នាំកូនប្រុស...........................................................................................</li>
		  						<li>&#x25BA;ឆ្នាំកូនស្រី..............................................................................................</li>
			  				</td>
			  			</tr>
			  	</table>				  	
			</div>
		</body>
</html>


