<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
	$row = $this->row
?>	
<body>
	<div class="wrapper" style="border: 1px dotted #000;background: #fff;width:25cm;margin: 0 auto;min-height: 34cm;padding: 0.5cm;">
			 <style>
		    	.wrapper{
		    		width: 100%;
		    		margin: 0px;
		    		padding: 0px;
		    	}
		    	.contain{
		    		width: 1024px;
		    		margin: 0 auto;
		    	}
				table {
		    		border-collapse: collapse;
		    		width: 100%;
				}
				th, td {
		    		padding: 4px;
				}
		    </style>
			<table cellpadding="0" cellspacing="0" width="100%">
				<tr class="no-boder">
					<td>
					<table width="100%" >
						<tr>
							<td width="20%" align="center">
								<img style="max-height:100px;" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.png'?>"><br>
								<span style="font-family: Freestyle Script;font-size: 20px;"></span>
								
							</td>
							<td width="60%">
								<table   style="text-align:center;border:solid 1px #FFF;">
									<tr style="list-style:12px; font-family:  Khmer OS Muol; font-size:32px;font-weight: bold;">
										<td>ព្រះរាជាណាចក្រកម្ពុជា</td>
									</tr>
									<tr style="list-style:12px;font-weight: bold;font-size:13px;" class="img-size">
										<td>
											<img style="width: 25%;height: 25px;" src="<?php echo $this->baseUrl().'/images/kbach1.png'?>"><br>
										</td>
									</tr>
									<tr style="list-style:15px;font-family: Times New Roman, cursive;font-size:25px;font-weight: bold;">
										<td>Tel: 012/ 015 73 73 03</td>
									</tr>
									<tr style="list-style:15px;font-family: Times New Roman, cursive;font-size:15px;">
										<td class="pan-input">
										</td>
									</tr>
								</table>
							</td>
							<td width="20%" >&nbsp;</td>
						</tr>
					</table>
				</td>
			</tr>
		  	<tr>
		  		<td>
		  			<table style="font-size:15px;font-family:  Khmer OS Muol;">	
		  				<div style="font-weight: bold; font-family:  Khmer OS Muol; font-size:28px;">
		  					他好看　(សប្បុរសជន):
		  				</div>
			  			<tr>
  							<td width="47%"><br /></td>
  						</tr>
  						<tr>
			  				<td>
  								<table style="line-height: 80px; margin-top: -10px;"> 										
  									<tr>
  										<td colspan="3" align="center" style="list-style:25px; font-family:   Khmer OS Muol; font-size:58px;font-weight: bold; color:red;">
  											<?php echo $this->row['donor_name']?>
  										</td> 											
  									</tr>
  									<tr>
  										<td colspan="3" align="center" style="list-style:25px; font-family:  Khmer OS Muol; font-size:38px;font-weight: bold; color:red;">
  											<?php echo $this->row['donor_female']?> នឹងបុត្រ ព្រមទាំងចៅ 
  										</td>
  									</tr>
  									<tr>
  										<td colspan="3" align="center" style="list-style:25px; font-family:  Khmer OS Muol; font-size:32px;font-weight: bold; color:red;">
  											<?php echo $this->row['donor_phone']?>
  										</td>
  									</tr>
  								</table>
			  				</td>
			  			</tr>
		  				<tr align="center" style="list-style:25px; font-family:  Khmer OS Muol; font-size:28px;font-weight: bold; ">
		  					<td>
		  						<?php echo $this->row['notes']?>
							</td>
		  				</tr>
			  			<tr align="center" style="list-style:25px; font-family:  Khmer OS Muol; font-size:28px;font-weight: bold; color:red;">
		  					<td>
		  						<?php echo $this->row['note']?>
		  					</td>
		  				</tr>
		  				<tr style="font-family:  Khmer OS Muol; font-size:28px;font-weight: bold;  line-height:70px; color: #6A5ACD; list-style:none;">
		  					<td>
		  						<li>ឈ្មោះ ៖  <?php echo $this->row['dead_name']?></li>
		  						<li>ភេទ  ៖  <?php echo $this->row['dead_sex']?></li>
		  						<li>អាយុ ៖ <?php echo $this->row['dead_age']?>&nbsp;&nbsp;ឆ្នាំ</li>
		  						<li>លំនៅដ្ឋានសព្វថ្ងៃ ៖ <?php echo $this->row['dead_address']?> </li>
		  						<li>ថ្ងៃទី  <?php echo date("d",strtotime($row['date_jenh']));?> ខែ <?php echo date("m",strtotime($row['date_jenh']));?> ឆ្នាំ 20<?php echo date("y",strtotime($row['date_jenh']));?></li>
		  					</td>
		  				</tr>
		  			</table>
		  		</td>
		  	</tr>
		</table>
	</div>
</body>
</html>


