<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
	$row = $this->row;
?>
<div id="Printgoodtime">	
	<div class="wrapper" id="borderimg1" background: #fff;width:24cm;margin: 0 auto;min-height: 20cm;padding: 0.5cm;">
		<style>
	    	.wrapper{
	    		width: 100%;
	    		margin: 0px;
	    		padding: 0px;
	    	}
	    	.contain{
	    		width: 1024px;
	    		margin: 0 auto;
	    	}
			table {
	    		border-collapse: collapse;
	    		width: 100%;
			}
			th, td {
	    		padding: 4px;
			}
			#borderimg1 { 
			    border: 12px solid transparent;
			    border-image: url(/bunastock/trunk/public/images/kiifo.jpg) 35 round;
			}
	    </style>
		<table cellpadding="0" cellspacing="0" width="100%">
			<tr class="no-boder">
				<td>
				<table width="100%" >
					<tr>
						<td width="20%" align="center">
							<img style="width: 138%;height: 125px;" alt="<?php ?>" src="<?php echo $this->baseUrl()?>/images/logosbona.jpg"><br>
							<span style="font-family: Freestyle Script;font-size: 20px;"></span>
							
						</td>
						<td width="60%">
							<table   style="text-align:center;border:solid 1px #FFF;">
								<tr style="list-style:12px; font-family:  Khmer OS Muol; font-size:79px;font-weight: bold;color:red;">								
									<td>វេលាល្អ</td>							
								</tr>
				
							</table>
						</td>
						<td width="20%" >&nbsp;</td>
					</tr>
				</table>
				</td>
			</tr>
	  			<table style="font-size:15px;font-family: Khmer OS Battambang, Times New Roman;">  			
	  				<tr style="list-style:25px; font-family:  Khmer OS Muol; font-size:60px;font-weight: bold; list-style:none; color:#60A0E0;">
	  					<td>
	  						<li>សែនបើកឆាក</li>
	  					</td>
	  				</tr>
	  				<tr align="center" style="list-style:25px; font-family:  Khmer OS Muol;line-height:140px;; font-size:55px;font-weight: bold; list-style:none; color:#800080;">
	  					<td>
	  						<li>ថ្ងៃទីៈ <?php echo date("d",strtotime($row['date_sen']));?> ខែ <?php echo date("m",strtotime($row['date_sen']));?>
	  						ឆ្នាំ 20<?php echo date("y",strtotime($row['date_sen']));?></li>
	  						<li>ម៉ោងៈ <?php echo $this->row['time_chlong_mong']?> ព្រឹក</li>
	  					</td>
	  				</tr>
	  			</table>	  			
			</table>
			<table style="font-size:15px;font-family: Khmer OS Battambang, Times New Roman;">  			
	  				<tr style="list-style:25px; font-family:  Khmer OS Muol; font-size:60px;font-weight: bold; list-style:none; color:#60A0E0;">
	  					<td>
	  						<li>&nbsp;</li>
	  					</td>
	  				</tr>
	  				<tr align="center" style="list-style:25px; font-family:  Khmer OS Muol;line-height:140px;; font-size:55px;font-weight: bold; list-style:none; color:#800080;">
	  					<td>
	  						<li>&nbsp;</li>
	  						<li>&nbsp;</li>
	  					</td>
	  				</tr>
	  			</table>
	</div>
</div>
<div style="padding-left:14%; margin: 0 auto;"> 
    	<lable class="col-md-3" style=""></lable>
    	<div class="col-md-2">
			<a href="<?php echo $this->baseUrl();?>/mong/index"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ចាកចេញ</button></a>
		</div>
    	<lable class="col-md-2" style="">
             <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i> បោះពុម្ភ </button>
		</lable>
		<lable class="col-md-3" style=""></lable>
	</div>

<script>
function printinvoice(){
	var printContents = document.getElementById('Printgoodtime').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_goodtime").submit();
}
</script>


