<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
?>
<title>របាយការណ៍ផ្ទេរទំនិញ</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("របាយការណ៍ផ្ទេរទំនិញ");?>
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
					 <ul class="dropdown-menu" role="menu">
						<li>
							<a href="#" onclick="doPrint();">
								<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
							</a>
						</li>
						<li>
							<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
						</li>
						
					 </ul>
				</div>
			</div>
		</div>	
		
		<div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('ad_search');?>
							</label>
							<label class="control-label col-md-3">
								<select name="from_location" id="from_location" class="form-control select2me" >
									<option value="">From location</option>
									<?php if(!empty($this->branch)){foreach ($this->branch as $branch){?>
									<option value="<?php echo $branch['id']?>" <?php if($branch['id']==$this->search['from_location']){echo "selected='selected'";}?>><?php echo $branch['name']?></option>
									<?php }}?>
								</select>
							</label>
							<label class="control-label col-md-3">
								<select name="to_location" id="to_location" class="form-control select2me" >
									<option value="">To location</option>
									<?php if(!empty($this->branch)){foreach ($this->branch as $branch){?>
									<option value="<?php echo $branch['id']?>" <?php if($branch['id']==$this->search['to_location']){echo "selected='selected'";}?>><?php echo $branch['name']?></option>
									<?php }}?>
								</select>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('status');?>
							</label>
							<label class="control-label col-md-1">
								<button type="submit" class="btn btn-primary col-md-12"><?php echo $tr->translate("ស្វែងរក");?></button>
							</label>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">
								<div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div>
							</label>
							<label class="control-label col-md-3">
								<div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div>
							</label>
						</div>
					</div>
					<div style="clear:both;"></div>	
				</form> 
			</div>	
			
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
		<div id="divPrint" style="width: 100%;">
			<style>
				.style{
					line-height: 25px;font-size: 12x !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
				th{padding: 5px;}
				.hover:hover{background: #ccc;}
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
			</style>
			<table style="font-family: 'Khmer OS Content'; width:100%;">
				<tbody>
					<tr>
				    	<td align="center">
				        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
				            	<tbody>
				            		<tr>
					                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logosbona.jpg" height="95px" ></td>
					                	<td width="60%" >
					                		<ul>
					                			<li style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
					                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'">របាយការណ៍ផ្ទេរទំនិញ</li>
					                		</ul>
					                	</td>
					                    <td width="20%"></td>
					                </tr> 
					            </tbody>
				            </table>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				            <table class="table2excel" border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
				                 <tr bgcolor="#b0bdfd" align="center" style="font-weight:bold; line-height: 25px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
				                    <td><?php echo $tr->translate("NUM");?></td>
									<td><?php echo $tr->translate("ពីសាខា");?></ts>
									<td><?php echo $tr->translate("ទៅសាខា");?></td>
									<td><?php echo $tr->translate("ឈ្មោះផលិតផល");?></td>
									<td><?php echo $tr->translate("បរិ.ដុំ");?></td>
									<td><?php echo $tr->translate("បរិ.រាយ");?></td>
									<td><?php echo $tr->translate("បរិ.សរុប");?></td>
									<td><?php echo $tr->translate("សម្គាល់");?></td>
									<td><?php echo $tr->translate("ថ្ងៃបង្កើត");?></td>
									<td><?php echo $tr->translate("អ្នកប្រើប្រាស់");?></td>
									<td><?php echo $tr->translate("ស្ថានភាព");?></td>
				                </tr>
				                <?php
								$i=0;
				                if(!empty($this->transfer_detail))foreach ($this->transfer_detail AS $index => $row){
				                	$i++;
								?>
									<tr class='hover ' style="font-size:13px; " >
										<td align="center" style="white-space: nowrap;"><?php echo $i; ?></td>
										<td >&nbsp;&nbsp;<?php echo $row["from_loc"]?></td>
										<td >&nbsp;&nbsp;<?php echo $row["to_loc"]?></td>
										<td >&nbsp;&nbsp;<?php echo $row["pro_name"]?></td>
										<td align="center">&nbsp;&nbsp;<?php echo $row["qty"]?></td>
										<td align="center">&nbsp;&nbsp;<?php echo $row["qty_detail"]?></td>
										<td align="center">&nbsp;&nbsp;<?php echo $row["total_qty"]?></td>
										<td >&nbsp;&nbsp;<?php echo $row["note"];?></td>
										<td align="center">&nbsp;&nbsp;<?php echo date("d-m-Y",strtotime($row["create_date"]));?></td>
										<td >&nbsp;&nbsp;<?php echo $row["user"];?></td>
										<td >&nbsp;&nbsp;<?php echo $row["status"];?></td>
									</tr>
								  <?php }?> 
				           </table>
				            <br>
				            <table align="center" width="100%">
							   <tr style="font-size: 14px;">
							        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
							        <th></th>
							        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
							        <th></th>
							        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
							   </tr>
							</table>	
			    		</td>
			    	</tr>
				</tbody>
			</table>
		</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {
	var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();
}

</script>
