<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
?>
<title>Adjust Stock Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("របាយការណ៏ បញ្ជីកែប្រែចំនួនផលិតផលក្នុងស្តុកលម្អិត");?>
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
					 <ul class="dropdown-menu" role="menu">
						<li>
							<a href="#" onclick="doPrint();">
								<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
							</a>
						</li>
						<li>
							<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
						</li>
						
					 </ul>
				</div>
			</div>
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
			            	<tr>
			                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl()?>/images/logosbona.jpg" height="95px" ></td>
			                	<td width="60%" >
			                		<ul>
			                			<li style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'">របាយការណ៏ បញ្ជីកែប្រែចំនួនផលិតផលក្នុងស្តុកលម្អិត</li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
			            </tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table class="table2excel" border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
			                 <tr bgcolor="#B0C4DE" align="center" style="font-weight:bold; line-height: 30px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td><?php echo $tr->translate("សាខា");?></td>
								<td><?php echo $tr->translate("លេខសម្គាល់");?></td>
								<td><?php echo $tr->translate("ផលិតផល");?></td>
								<td><?php echo $tr->translate("ចំនួនដើម");?></td>
								<td><?php echo $tr->translate("បរិ.ដុំ");?></td>
								<td><?php echo $tr->translate("បរិ.រាយ");?></td>
								<td><?php echo $tr->translate("បរិ.សរុប ");?></td>
								<td><?php echo $tr->translate("ចំនួននៅសល់ ");?></td>
								<td><?php echo $tr->translate("ថ្ងៃបង្កើត");?></td>
								<td><?php echo $tr->translate("អ្នកប្រើប្រាស់");?></td>
								<td><?php echo $tr->translate("ស្ថានភាព");?></td>
			                </tr>
		                <?php $num=1; 
		                if(!empty($this->adjust_detail))foreach ($this->adjust_detail AS $index => $row){?>
							<tr height="30" style="font-size: 13px;" align="center" class='row-format<?php echo $num++; ?>' id="item_<?php echo $index; ?>">
								<td >&nbsp;<?php echo $index+1 ?></td>
								<td ><?php echo $row["branch"]?></td>
								<td >&nbsp;<?php echo $row["code"];?></td>
								<td ><?php echo $row["pro_name"]?></td>
								
								<?php 
									$total_unit_detail = $row["cur_qty"] * $row["qty_perunit"]; 
									$qty_detail_remain = number_format($total_unit_detail % $row["qty_perunit"],0); 
									$qty_unit = intval($row["cur_qty"]);
									
									if($qty_unit>0){
										$qty_unit = $qty_unit."".$row['measure_name'];
									}else{
										$qty_unit = "";
									}
									
									if($qty_detail_remain>0){
										$qty_detail_remain=$qty_detail_remain."".$row['unit_label'];
									}else{
										$qty_detail_remain="";
									}
								?>
								
								<td ><?php echo $qty_unit." ".$qty_detail_remain;?></td>
								<td ><?php echo $row["qty_unit"]?></td>
								<td ><?php echo $row["qty_detail"]?></td>
								<td ><?php echo $row["total_qty"]?></td>
								<td ><?php echo $row["qty_remain"]?></td>
								<td ><?php echo date("d-m-Y",strtotime($row["create_date"]))?></td>
								<td ><?php echo $row["user"]?></td>
								<td ><?php echo $row["status"]?></td>
							</tr>
						  <?php }?> 
		                </tbody>
		           </table>
		            <br>
		             
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
//function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
