<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
?>
<title>Adjust Stock Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("របាយការណ៏ បញ្ជីកែប្រែចំនួនផលិតផលក្នុងស្តុក");?>
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
					 <ul class="dropdown-menu" role="menu">
						<li>
							<a href="#" onclick="doPrint();">
								<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
							</a>
						</li>
						<li>
							<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
						</li>
						
					 </ul>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<div class="form-body">
						<div class="form-group">
							<div class="col-md-3">
								<?php echo $formFilter->getElement('ad_search');?>
							</div>
							<div class="col-md-3">
								<?php echo $formFilter->getElement('branch');?>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<i class="fa fa-calendar"></i>
									<?php echo $formFilter->getElement('start_date');?>
								</div>	
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<i class="fa fa-calendar"></i>
									<?php echo $formFilter->getElement('end_date');?>
								</div>
							</div>
							<div class="col-md-1">
								<button type="submit" class="btn green"><?php echo $tr->translate("ស្វែងរក");?></button>
							</div>
						</div>		
					</div>
					<div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 29px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
			            	<tr>
			                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl()?>/images/logosbona.jpg" height="95px" ></td>
			                	<td width="60%" >
			                		<ul>
			                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light'; color: #F31A1A  !important"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'; color: #F31A1A  !important">របាយការណ៏ បញ្ជីកែប្រែចំនួនផលិតផលក្នុងស្តុក</li>
			                			<li style="text-align:center; font-size:14px; color: #F31A1A  !important"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
			            </tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table class="table2excel" border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
			                 <tr bgcolor="#B0C4DE" align="center" style="font-weight:bold; line-height: 30px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td><?php echo $tr->translate("សាខា");?></td>
								<td><?php echo $tr->translate("លេខសម្គាល់");?></td>
								<td><?php echo $tr->translate("សម្គាល់");?></td>
								<td><?php echo $tr->translate("ថ្ងៃបង្កើត");?></td>
								<td><?php echo $tr->translate("អ្នកប្រើប្រាស់");?></td>
								<td><?php echo $tr->translate("ស្ថានភាព");?></td>
			                </tr>
		                <?php $num=1; 
		                if(!empty($this->product))foreach ($this->product AS $index => $row){?>
							<tr height="30" style="font-size: 13px;" align="center" class='row-format<?php echo $num++; ?>' id="item_<?php echo $index; ?>">
								<td >&nbsp;<?php echo $index+1 ?></td>
								<td ><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/product/rptadjuststockbyid/id/".$row["id"];?>"><?php echo $row["branch"]?></a></td>
								<td ><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/product/rptadjuststockbyid/id/".$row["id"];?>">&nbsp;<?php echo $row["code"];?></a></td>
								<td ><?php echo $row["note"]?></td>
								<td ><?php echo date("d-m-Y",strtotime($row["create_date"]))?></td>
								<td ><?php echo $row["user"]?></td>
								<td ><?php echo $row["status"]?></td>
							</tr>
						  <?php }?> 
		                </tbody>
		           </table>
		            <br>
		             
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}

/*var currentTime = new Date();
var month = currentTime.getMonth() + 1;
var day = currentTime.getDate();
var year = currentTime.getFullYear();
	var date =(year + "-" + month + "-" + day );

var start_date = $('#start_date').val();
var end_date =$('#end_date').val();

if(end_date!="" | start_date!=""){
    start_date = $('#start_date').val();
	end_date =$('#end_date').val();
	
}else{
	start_date = $('#start_date').val(date);
	end_date = $('#end_date').val(date);
}*/

<?php //$url_item_filter =  $this->url(array('module'=>'report','controller'=>'index','action'=>'get-item-filter')); ?>
/*function getProductFilter(){
	var location_id=$("#LocationId").val();
	var branch_id = $('#branch_id').val();
	var category_id = $('#category_id').val();
		$.ajax({
			url:"<?php //echo $url_item_filter;?>",
			type:"post",
			data:{'category_id':category_id,'branch_id':branch_id,'location_id':location_id},
			success: function(data){
				items = $.parseJSON(data);
				if(items){
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
					 $('#item').append($("<option></option>").attr("value","").text("Please Select Item"));
					 for (var index = 1 ; index <= items.length; index++) {
							$('#item').append($("<option></option>").attr("value",items[index-1]['pro_id']).text(items[index-1]['item_code'] + items[index-1]['item_name'])); 
							$("select#item").find("option#items[index-1]['pro_id']").attr("selected", true);
					 }           
					$('#item').val('').trigger("liszt:updated");
				}else{
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
						 $('#item').append($("<option></option>").attr("value","").text("No Items Result!"));
						 $('#item').val('').trigger("liszt:updated");
				}
			},
			error:function(){
			}
		});
	}*/
</script>
