<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
$db = new report_Model_DbProduct();
?>
<title>Product Current Stock Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("បញ្ជីរាយឈ្មោះទំនិញ-សេវាកម្មលក់");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
							<ul class="dropdown-menu" role="menu">
								<li>
									<a href="#" onclick="doPrint();">
										<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
									</a>
								</li>
								<li>
									<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
								</li>
							</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<div class="form-body">
							<div class="form-group">
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('ad_search');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('branch');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('brand');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('category');?>
								</label>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('status_qty');?>
								</label>
								<label class="control-label col-md-1">
									<button type="submit" class="btn btn-primary col-md-12"><?php echo $tr->translate("ស្វែងរក");?></button>
								</label>
							</div>
							
						
				</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 15px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 29px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
		            		<tr>
			                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logosbona.jpg" height="95px" ></td>
			                	<td width="60%" >
			                		<ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'; color: #F31A1A  !important"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'; color: #F31A1A  !important">បញ្ជីរាយឈ្មោះទំនិញ-សេវាកម្មលក់</li>
			                			<!--<li style="text-align:center; font-size:13px;"><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>-->
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
			            </tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table class="table2excel" border="1"  style="border-collapse:collapse;border:1px solid #000; font-size:14px;" width="100%" cellspacing="0">               
		                 
		                 <?php 	$i=0;$location_id=0;$total=1;if(!empty($this->product)){foreach($this->product as $key => $row){
								$i++;
								if($location_id != $row['location_id']){
									if($key>0){
						 ?>
									</table>
									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;margin-top: 15px;">
								<?php 
										$i=1;
									}
								?>
							
										<tr style="font-size:10px; color:#000; height: 23px; border-left:1px solid #fff; border-right:1px solid #fff; border-top: 1px solid #fff;"​ align="center">
										    <th colspan="16" style="text-align:left">
										    	<strong style="color:#000; font-size: 14px;font-family:'Khmer OS Battambang';font-weight: bold;" ><?php echo $tr->translate('សាខា').' : '.$row['location_name']; ?></strong>
										    </th>
										</tr>
										<tr style="font-family:'khmer os battambang';font-size:14px; height: 20px;border: 1px solid #000;white-space: nowrap;background-color: #b0bdfd;line-height:30px;font-weight: bold;" align="center" >
											<td>&nbsp;<?php echo $tr->translate("ល.រ	");?></td>
											<td><?php echo $tr->translate("លេខកូដ");?></td>
											<td><?php echo $tr->translate("ឈ្មោះទំនិញ/សេវាកម្ម");?></td>
											<td><?php echo $tr->translate("ប្រភេទ");?></td>
											<td><?php echo $tr->translate("ឯកតា");?></td>
											<td><?php echo $tr->translate("តម្លៃលក់");?></td>
											<td><?php echo $tr->translate("ចំនួនក្នុងស្តុក");?></td>
										</tr>
									<?php 
									$total = 0;
								}
										$location_id = $row['location_id'];
										if($row['status']==1){
											$total = $total + $row['price'];
										}
									?>	
									<tr class="hover" style="font-size:13px; height: 25px;border: 1px solid #000; white-space: nowrap;<?php if($row['status']==0){echo "color:red;";}?>" align="center" >
										<td align="center" style="width:3% !important">&nbsp;<?php echo $i?></td>
										<td style="white-space: nowrap;">&nbsp;<?php echo $row["item_code"]?></td>
										<td style="white-space: nowrap;">&nbsp;&nbsp;<?php echo $row["item_name"]?>&nbsp;&nbsp;</td>									
										<td style="width:10% !important;white-space: nowrap;" class="center"><?php echo $row["cat"]?></td>
										<td style="width:10% !important" class="center"><?php echo $row["measure"];?></td>
										<td style="width:10% !important" class="center"><?php echo "$ ".number_format($row["selling_price"],2);?></td>
										<td style="width:10% !important; <?php if($row["qty"]<=$row['qty_warning']){echo "color:red;";}?>" class="center"><?php if($row['is_service']==0){echo $row["qty"];}?></td>
									</tr>
						<?php		
							}}
						?>
						</table>
		                 
		                 
		                 
		                 
		             
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer OS Battambang'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer OS Battambang'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer OS Battambang'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}

</script>
