<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage(); 
  ?>
<div class="row">
	<h2 style="font-size: 14px;text-align: center;font-family:'Khmer MEF2'">
		<?php echo $tr->translate("COMPANY_CUSTOMER")."<br /><br />";?>
		លេខកូដទំនិញ
	</h2>
	
	<?php 
	$cate_id='';
	if(!empty($this->rsproduct)) foreach($this->rsproduct as $key => $rs){?>	
	 <?php $url_barcode = $this->url(array("module"=>"report","controller"=>"product","action"=>"generate-barcode","pro_code"=>$rs['item_code']),null,true); ?>
		<?php if($rs['cate_id']!=$cate_id){?>		
		<?php if($key>0){?></ul><?php }?>				
		<h2 style="clear:left;font-size: 14px;text-align: center;font-family:'Khmer MEF2'"><?php echo $rs['cate_name'];?></h2>
		<ul>
		<?php }
		$cate_id = $rs['cate_id'];?>
		<li class="<?php if(count($this->rsproduct)==$key+1){ echo 'lastrecord';}?>">
			<div style="margin-bottom: 3px;"><?php echo $rs['item_name']."<br />"?></div>
		<img src="<?php echo $url_barcode;?>" /></li>
	<?php }?>
	</ul>
</div>
<style>
ul li{list-style: none;
float:left;border:1px solid #000;padding:0px 10px;
text-align: center; border-right:none;}
ul{border-right:1px solid #000 !important;}
ul li.lastrecord{border-right:1px solid #000 !important; }
</style>