<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'index'));
	$url_new = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'add'));
?>
<title><?php echo $tr->translate("Customer Payment");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("Suppliyer Payment")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" autocomplete="off" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body" style="background:#fbf9f9;">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("លេខបញ្ជាទិញ");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<select name="purchase_id" id="purchase_id" class="form-control select2me" onchange="getInvoice(1);" >
									<option value="">ជ្រើសរើសលេខបញ្ជាទិញ</option>
									<?php if(!empty($this->purchase_num)){foreach($this->purchase_num as $rs){?>
									<option value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
									<?php }}?>
								</select>
							</div>
							
							<label class="control-label col-md-2"> <?php echo $tr->translate("VENDOR_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<select name="vendor_id" id="vendor_id" class="form-control select2me" onchange="getInvoice(2);" >
									<option value="">ជ្រើសរើសអ្នកផ្គត់ផ្គង់</option>
									<?php if(!empty($this->all_vendor)){foreach($this->all_vendor as $rs){?>
									<option value="<?php echo $rs['id']?>"><?php echo $rs['name']?></option>
									<?php }}?>
								</select>
							</div>
						</div>
						
						
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PAYMENT_TYPE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<select name="payment_type" id="payment_type" class="form-control select2me" onchange="checkpayment();" >
									<option value="Cash">Cash</option>
									<option value="Cheque">Cheque</option>
									<option value="Credit">Credit</option>
									<option value="Bank Transtransfer">Bank Transtransfer</option>
								</select>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("CHEQUE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("cheque");?>
								</div>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<?php echo $form->getElement("bank_name");?>
								</div>
							</div>
							
						</div>
					    <div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("Expense Date");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"><i class="fa fa-calendar"></i>
								<?php echo $form->getElement("expense_date");?>
								</div>
							</div>
					    </div>
						
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<th><?php echo $tr->translate("ល.រ");?></th>
									<th style="white-space:nowrap;"><?php echo $tr->translate("អ្នកផ្គត់ផ្គង់");?></th>
									<th><?php echo $tr->translate("លេខបញ្ជាទិញ");?></th>
									<th><?php echo $tr->translate("ថ្ងៃចំណាយ");?></th>
									<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>
									<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>
									<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
					</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<label class="control-label col-md-2">
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("ជំពាក់សរុប​ :");?> Total<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("all_total");?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("ប្រាក់បានបង់សរុប");?> (Paid)
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<?php echo $form->getElement("paid");?>
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ពន្ធ");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("total_tax");?>
								</div>
							</div>
							<label class="control-label col-md-2">ប្រាក់នៅសល់ (Balance)​ :<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php echo $form->getElement("balance");?>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-3">
							</div>
							<div class="col-md-2">
								<a href="<?php echo $this->baseUrl();?>/purchase/payment/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<button type="submit" name="saveclose" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-2">
								<button type="submit" value="btnsavenew" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
							</div>
							<div class="col-md-3">
							</div>
						</div>
						
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- end new product -->

<script>
$('#frm').submit(function() {
	paid=$("#paid").val();
	if(paid=='' || paid==0){
		alert("សូមបញ្ចុលទឹកប្រាក់ដែលបានបង់");
		$('#paid').focus;
		return false;	
	}
	identity =$("#identity").val();
	if(identity=='' || identity==-1){
		alert("សូមជ្រើសលេខវិក្កយបត្រដែលចង់បង់!");
		return false;
	}
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
	} else {
	   return false;	    
	}
});
function paidtotal(type){//1=dollar,2=riel
	doRemain();
}
function checkpayment(){
	payment_type = $("#payment_type").val();
	if(payment_type=="Cheque"){
		$( "#bank_name" ).attr( "readOnly", false );
		$( "#cheque" ).attr( "readOnly", false );
	}else{
		$( "#bank_name" ).attr( "readOnly", true );
		$( "#cheque" ).attr( "readOnly", true );}
}

<?php $urlgetinvoice =  $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'getinvoice')); ?>
function getInvoice(type){
	//alert(type);
	if(type==1){
		post_id=$("#purchase_id").val();
		$("#vendor_id").val(post_id).select2();
	}else{
		post_id=$("#vendor_id").val();
		$("#purchase_id").val(post_id).select2();
	}
	
	$("#all_total").val(0);
	$("#paid").val(0);
	$("#balance").val(0);
	
	if(post_id>0){
		$.ajax({
			url:"<?php echo $urlgetinvoice;?>",
			type:"post",
			data:{'post_id':post_id},
			success: function(data){	
				$("#table_order").html("");
				template='<tr height="33px">';
					template+='<th><?php echo $tr->translate("ល.រ");?></th>';
					template+='<th><?php echo $tr->translate("អ្នកផ្គត់ផ្គង់");?></th>';
					template+='<th><?php echo $tr->translate("លេខបញ្ជាទិញ");?></th>';
					template+='<th><?php echo $tr->translate("ថ្ងៃចំណាយ");?></th>';
					template+='<th><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></th>';
					template+='<th><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></th>';
					template+='<th><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></th>';
				template+='</tr>';
				
				$('#identity').val("");
				data = $.parseJSON(data);
				
				for(i=0;i<data.length;i++){
					
					index=i+1;
					template+='<tr style="height:30px;" id="row_order_'+index+'">';
						template+='<td >'+index+'</td>';
						template+='<td >'+data[i].vendor+'</td>';
						template+='<td >'+data[i].order_number+'</td>';
						template+='<td >'+data[i].expense_date+'</td>';
						template+='<td >'+data[i].total+'<input type="hidden" value='+data[i].total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
						template+='<td >'+data[i].paid+'<input type="hidden" value='+data[i].paid+' id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
						template+='<td >'+data[i].balance+'<input type="hidden" value='+data[i].balance+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
				    template+="</tr>";
					if($('#identity').val()!="") {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+index);
					} else {$('#identity').val(index);}
					
					$('#all_total').val(data[i].total_payment);
					$('#balance').val(data[i].total_payment);
				}
				$('#table_order').append(template);
				//if(data.length>0){netTotal();}else{$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}				
			},
			error:function(e){
				alert("error"+e);
			}
		});	
	}
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var subtotal=0;
	var paid = 0;
	discount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
	}
	$('#all_total').val(subtotal);
	doRemain();
}
function doRemain() {
	var all_total = Number($('#all_total').val());
	var paid = Number($('#paid').val());
	if(paid > all_total){
		var paid = $('#paid').val(all_total);
		 $('#balance').val(0);
   }else{
	   remain = all_total-paid;
	   $('#balance').val(remain.toFixed(2));
	}	
}
function getCustomerInfo(){
	v_id = $("#v_name").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}
</script>	