<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'edit'));
?>
<title><?php echo $tr->translate("Customer Payment");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("Suppliyer Payment")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" autocomplete="off" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					
					<div class="form-body" style="background:#fbf9f9;">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("BRANCH_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<select name="branch_id" id="branch_id" disabled="disabled" class="form-control select2me"  >
									<option value=""><?php echo $tr->translate("SELECT_BRANCH");?></option>
									<?php if(!empty($this->branch)){foreach($this->branch as $branch){?>
									<option value="<?php echo $branch['id']?>" <?php if($branch['id']==$this->row['branch_id']){echo "selected='selected'";}?>><?php echo $branch['name'];?></option>
									<?php }}?>
								</select>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("លេខបញ្ជាទិញ");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<select name="purchase_id" id="purchase_id" class="form-control select2me" onchange="getInvoice(1);" >
									<option value="">ជ្រើសរើសលេខបញ្ជាទិញ</option>
									<?php if(!empty($this->purchase_num)){foreach($this->purchase_num as $rs){?>
									<option value="<?php echo $rs['id']?>" <?php if($rs['id']==$this->row['purchase_id']){echo "selected='selected'";}?>><?php echo $rs['name']?></option>
									<?php }}?>
								</select>
							</div>
							
							<label class="control-label col-md-2"> <?php echo $tr->translate("VENDOR_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<select name="vendor_id" id="vendor_id" class="form-control select2me" onchange="getInvoice(2);" >
									<option value="">ជ្រើសរើសអ្នកផ្គត់ផ្គង់</option>
									<?php if(!empty($this->all_vendor)){foreach($this->all_vendor as $rs){?>
									<option value="<?php echo $rs['id']?>" <?php if($rs['id']==$this->row['purchase_id']){echo "selected='selected'";}?>><?php echo $rs['name']?></option>
									<?php }}?>
								</select>
							</div>
						</div>
						
						
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("PAYMENT_TYPE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<select name="payment_type" id="payment_type" class="form-control select2me" onchange="checkpayment();" >
									<option value="Cash" <?php if($this->row['payment_type']=="Cash"){echo "selected='selected'";}?>>Cash</option>
									<option value="Cheque" <?php if($this->row['payment_type']=="Cheque"){echo "selected='selected'";}?>>Cheque</option>
									<option value="Credit" <?php if($this->row['payment_type']=="Credit"){echo "selected='selected'";}?>>Credit</option>
									<option value="Bank Transtransfer" <?php if($this->row['payment_type']=="Bank Transtransfer"){echo "selected='selected'";}?>>Bank Transtransfer</option>
								</select>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("CHEQUE");?><span class="required">
							*</span>
							</label>
							<div class="col-md-2">
								<input type="text" class="form-control" name="cheque" id="cheque" value="<?php echo $this->row['cheque_number']?>" readonly placeholder="លេខសែក"​/>
							</div>
							<div class="col-md-2">
								<input type="text" class="form-control" name="bank_name" id="bank_name" value="<?php echo $this->row['bank_name']?>" readonly placeholder="ឈ្មោះធនាគារ"/>
							</div>
							
						</div>
					    <div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<textarea name="remark" id="remark" class="form-control" rows="1"><?php echo $this->row['remark']?></textarea>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("Expense Date");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"><i class="fa fa-calendar"></i>
									<input class="form-control date-picker" name="expense_date" id="expense_date" value="<?php echo date("d-m-Y",strtotime($this->row['expense_date']))?>" data-date-format="dd-mm-yyyy" />
								</div>
							</div>
					    </div>
						<div class="form-group" style="">
							<label class="control-label col-md-2"><?php echo $tr->translate("ស្ថានភាព");?></span>
							</label>
							<div class="col-md-4">
								<select name="status" id="status" class="form-control select2me" >
									<option value="1" <?php if($this->row['status']==1){echo "selected='selected'";}?>>ប្រើប្រាស់</option>
									<option value="0" <?php if($this->row['status']==0){echo "selected='selected'";}?>>មិនប្រើប្រាស់</option>
								</select>
							</div>
						</div>
						
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px" align="center" style="font-weight:bold;">
									<td><?php echo $tr->translate("ល.រ");?></td>
									<td style="white-space:nowrap;"><?php echo $tr->translate("អ្នកផ្គត់ផ្គង់");?></td>
									<td><?php echo $tr->translate("លេខបញ្ជាទិញ");?></td>
									<td><?php echo $tr->translate("ថ្ងៃចំណាយ");?></td>
									<td><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></td>
									<td><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></td>
									<td><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></td>
							</tr>
						 </table>
						 <input type="hidden" id="identity" name="identity" />
					</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("PAYMENT_METHOD");?><span class="required">
								 </span>
							</label>
							<label class="control-label col-md-2">
							</label>
							<div class="col-md-2">
								<div class="input-icon right">
								</div>
							</div>
								<label class="control-label col-md-2"><?php echo $tr->translate("ជំពាក់សរុប​ :");?> Total<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<input type="text" class="form-control" name="all_total" id="all_total" value="<?php echo $this->row['total']?>" readonly />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right"></div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("ប្រាក់បានបង់សរុប");?> (Paid)
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<input type="text" class="form-control" name="paid" id="paid" value="<?php echo $this->row['paid']?>" onkeyup="doRemain()"/>
								</div>
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php //echo $tr->translate("ពន្ធ");?><span class="required">
							</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
								<?php //echo $form->getElement("total_tax");?>
								</div>
							</div>
							<label class="control-label col-md-2">ប្រាក់នៅសល់ (Balance)​ :<span class="required">
							* </span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<input type="text" class="form-control" name="balance" id="balance" value="<?php echo $this->row['balance']?>" readonly />
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<div class="col-md-4">
							</div>
							<div class="col-md-2">
								<a href="<?php echo $this->baseUrl();?>/purchase/payment/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<button type="submit" id="saveclose" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-4">
							</div>
						</div>
						
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- end new product -->

<script>
$(document).ready(function() {
	getInvoice(0);
	setReadonly();
});
function setReadonly(){
	$('#purchase_id').prop('readonly', true);
	$('#vendor_id').prop('readonly', true);
	$('#payment_type').prop('readonly', true);
	$('#expense_date').prop('readonly', true);
	$('#remark').prop('readonly', true);
	$('#paid').prop('readonly', true);
	
	status = "<?php echo $this->row['status']?>";
	if(status==0){
		$('#status').prop('readonly', true);
	}
}
$('#frm').submit(function() {
	paid=$("#paid").val();
	if(paid=='' || paid==0){
		alert("សូមបញ្ចុលទឹកប្រាក់ដែលបានបង់");
		$('#paid').focus;
		return false;	
	}
	identity =$("#identity").val();
	if(identity=='' || identity==-1){
		alert("សូមជ្រើសលេខវិក្កយបត្រដែលចង់បង់!");
		return false;
	}
	var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
	if (r == true) {
	    return true;
		$("#saveclose").attr("disabled", true);
	} else {
	   return false;	    
	}
	
});
function paidtotal(type){//1=dollar,2=riel
	doRemain();
}
function checkpayment(){
	payment_type = $("#payment_type").val();
	if(payment_type=="Cheque"){
		$( "#bank_name" ).attr( "readOnly", false );
		$( "#cheque" ).attr( "readOnly", false );
	}else{
		$( "#bank_name" ).attr( "readOnly", true );
		$( "#cheque" ).attr( "readOnly", true );}
}

<?php $urlgetinvoice =  $this->url(array('module'=>'purchase','controller'=>'payment','action'=>'getinvoice')); ?>
function getInvoice(type){
	//alert(type);
	if(type==1){
		post_id=$("#purchase_id").val();
		$("#vendor_id").val(post_id).select2();
	}else if(type==2){
		post_id=$("#vendor_id").val();
		$("#purchase_id").val(post_id).select2();
	}else{
		post_id=$("#vendor_id").val();
	}
	
	if(post_id>0){
		$.ajax({
			url:"<?php echo $urlgetinvoice;?>",
			type:"post",
			data:{'post_id':post_id,'action':"edit"},
			success: function(data){	
				$("#table_order").html("");
				template='<tr height="33px" align="center" style="font-weight:bold;">';
					template+='<td><?php echo $tr->translate("ល.រ");?></td>';
					template+='<td><?php echo $tr->translate("អ្នកផ្គត់ផ្គង់");?></td>';
					template+='<td><?php echo $tr->translate("លេខបញ្ជាទិញ");?></td>';
					template+='<td><?php echo $tr->translate("ថ្ងៃចំណាយ");?></td>';
					template+='<td><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></td>';
					template+='<td><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></td>';
					template+='<td><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></td>';
					template+='<td><?php echo $tr->translate("សម្គាល់");?></td>';
					template+='<td><?php echo $tr->translate("ស្ថានភាព");?></td>';
				template+='</tr>';
				
				$('#identity').val("");
				data = $.parseJSON(data);
				
				for(i=0;i<data.length;i++){
					
					index=i+1;
					template+='<tr style="height:30px;" id="row_order_'+index+'">';
						template+='<td align="center">'+index+'</td>';
						template+='<td >'+data[i].vendor+'</td>';
						template+='<td align="center">'+data[i].order_number+'</td>';
						template+='<td align="center">'+data[i].expense_date+'</td>';
						template+='<td align="center">'+"$ "+data[i].total+'<input type="hidden" value='+data[i].total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
						template+='<td align="center">'+"$ "+data[i].paid+'<input type="hidden" value='+data[i].paid+' id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
						template+='<td align="center">'+"$ "+data[i].balance+'<input type="hidden" value='+data[i].balance+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
						template+='<td >'+data[i].remark+'<input type="hidden" value='+data[i].remark+' id="remark_'+index+'" name="remark_'+index+'"/></td>';
						template+='<td >'+data[i].status_name+'<input type="hidden" value='+data[i].status_name+' id="status_'+index+'" name="status_'+index+'"/></td>';
					template+="</tr>";
					if($('#identity').val()!="") {
						var identity = $('#identity').val();
						$('#identity').val(identity+','+index);
					} else {$('#identity').val(index);}
					
					// $('#all_total').val(data[i].total_payment);
					// $('#balance').val(data[i].total_payment);
				}
				$('#table_order').append(template);
				//if(data.length>0){netTotal();}else{$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}				
			},
			error:function(e){
				alert("error"+e);
			}
		});	
	}
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();
	netTotal();
}
function netTotal() {//use
	var subtotal=0;
	var paid = 0;
	discount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		subtotal += Number($('#balance_after'+rowIDArray[n]).val());
	}
	$('#all_total').val(subtotal);
	doRemain();
}
function doRemain() {
	var all_total = Number($('#all_total').val());
	var paid = Number($('#paid').val());
	if(paid > all_total){
		var paid = $('#paid').val(all_total);
		 $('#balance').val(0);
   }else{
	   remain = all_total-paid;
	   $('#balance').val(remain);
	}	
}
function getCustomerInfo(){
	v_id = $("#v_name").val();
	if(v_id==-1){
		$('#dialogvendor').modal('show');
	}
}
</script>	