<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->form_fastiveprogram;
?>
<title>របាយការណ៍កម្មវិធីបុណ្យ</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i>របាយការណ៍កម្មវិធីបុណ្យ
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" onclick="doPrint();">
									<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
								</a>
							</li>
							<li>
								<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
							</li>								
						</ul>
					</div>
				</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<?php $formFilter = $this->form_fastiveprogram; ?>
					<div class="form-group" style="padding-top: -6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('ad_search');?></label>
					</div>
					<div class="form-group" style="padding-top: -6px;">
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('status');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>
					<div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 14px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 29px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td align="center" width="16%" valign="top"><img  height="95px" src="<?php echo $this->baseUrl();?>/images/logosbona.jpg"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light';  color: #F31A1A   !important"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:17px; font-family:'Khmer OS Muol Light';  color: #F31A1A   !important">របាយការណ៍កម្មវិធីបុណ្យ</li>
		                			<li style="text-align:center; font-size:16px;  color: red !important"><?php if(!empty($this->search['start_date'])){?><?php echo date("d/m/Y",strtotime($this->search['start_date']));?> ដល់  <?php echo date("d/m/Y",strtotime($this->search['end_date']));}?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;"></td>
		                				<td width="65%"></td>
		                			</tr>
				                	</tbody>
				                </table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table  border="1" style="border-collapse:collapse;border:1px solid #000; font-size:14px;" width="100%" cellspacing="0">
		                 <thead>
							<tr style="background-color: #b0bdfd !important;font-weight:bold; text-align:center; line-height: 25px; font-size:13px; padding:1px 0px;">
								<th rowspan="2"  style="border:1px solid #000;text-align:center;">ល.រ</th>
								<th colspan="6"  style="border:1px solid #000;text-align:center;">ព័ត៌មានលម្អិតរបស់សព</th>
								<th colspan="6"  style="border:1px solid #000;text-align:center;">ព័ត៌មានលម្អិតរបស់ដៃគូសព</th>
								<th colspan="2"  style="border:1px solid #000;text-align:center;">ព័ត៌មានទីតាំង</th>
								<th colspan="2"  style="border:1px solid #000;text-align:center;">ទូរស័ព្ទសមាជិក</th>
								<th rowspan="2"  style="border:1px solid #000;text-align:center;" width="6%">ថ្ងៃបង្កើត</th>					
								<th rowspan="2"  style="border:1px solid #000;text-align:center;">អ្នកប្រើប្រាស់</th>	
								<th rowspan="2"  style="border:1px solid #000;text-align:center;">ស្ថានការ</th>	
							</tr>
							<tr style="background-color: #b0bdfd !important;font-weight:bold; text-align:center; line-height: 25px; font-size:13px; padding:1px 0px;">
								<th style="border:1px solid #000;text-align:center;" width="7%">ឈ្មោះ</th>
								<th style="border:1px solid #000;text-align:center;" width="7%">ឈ្មោះ(ចិន)</th>
								<th style="border:1px solid #000;text-align:center;">ភេទ</th>
								<th style="border:1px solid #000;text-align:center;">ឆ្នាំ</th>
								<th style="border:1px solid #000;text-align:center;">អាយុ</th>
								<th style="border:1px solid #000;text-align:center;" width="8%">ស្លាប់នៅថ្ងៃ</th>
								
								<th style="border:1px solid #000;text-align:center;" width="7%">ឈ្មោះ</th>
								<th style="border:1px solid #000;text-align:center;" width="7%">ឈ្មោះ(ចិន)</th>
								<th style="border:1px solid #000;text-align:center;">ភេទ</th>
								<th style="border:1px solid #000;text-align:center;">ឆ្នាំ</th>
								<th style="border:1px solid #000;text-align:center;">អាយុ</th>
								<th style="border:1px solid #000;text-align:center;" width="8%">ស្លាប់នៅថ្ងៃ</th>
								
								<th style="border:1px solid #000;text-align:center;">ទីតាំងបុណ្យ</th>
								<th style="border:1px solid #000;text-align:center;">ទីតាំងបញ្ចុះ/បូជា</th>
								
								<th style="border:1px solid #000;text-align:center;">ទូរស័ព្ទសមាជិកទី១</th>
								<th style="border:1px solid #000;text-align:center;">ទូរស័ព្ទសមាជិកទី២</th>
							</tr>
						</thead>		
		                <?php $num=1; 
		               
		                if(!empty($this->other))foreach ($this->other AS $index => $rs){?>
		                
						<tr class='row-format hover' align="center" style="border:1px solid #000; ">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;"><a style="color:#000080;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/sales/program/travel/id/".$rs["id"];?>">&nbsp;<?php echo $rs["dead_name"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["dead_name_chinese"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["dead_sex"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["dead_khmer_year"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["dead_age"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php if(!empty($rs['date_time_dead'])){echo date("d-m-Y H:i",strtotime($rs['date_time_dead']));}?></td>
						   <td style="white-space: nowrap;"><a style="color:#000080;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/sales/program/travel/id/".$rs["id"];?>">&nbsp;<?php echo $rs["partner_name"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["partner_name_chinese"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["partner_sex"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["partner_khmer_year"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["partner_age"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php if(!empty($rs['date_time_female'])){echo date("d-m-Y H:i",strtotime($rs['date_time_female']));}?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["place_of_program"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["place_pjos_sop"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["membersone"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["memberstwo"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs['create_date']));?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["user_id"];?></td>
						   						   
						   <td>&nbsp;<?php echo $rs["status"];?></td>
						</tr>
						   <?php 
							
                   		 }?>
		                </tbody>
		           </table>
		            <br>
		           
		              <br>
		              <table align="center" width="100%">
						   <tbody>
						   	<tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
