<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $rpt_other_donors=$this->url(array('module'=>'report','controller'=>'other','action'=>'rptdonorslist'), null, true);
  $rpt_sponsorship=$this->url(array('module'=>'report','controller'=>'other','action'=>'rptsponsorship'), null, true);
  $rpt_salemong=$this->url(array('module'=>'report','controller'=>'other','action'=>'rptsalemong'), null, true);
  $rpt_paymentlist=$this->url(array('module'=>'report','controller'=>'other','action'=>'rptpaymentlist'), null, true);
  $rpt_other_worker=$this->url(array('module'=>'report','controller'=>'other','action'=>'rptworker'), null, true);
  $rpt_partnerservice=$this->url(array('module'=>'report','controller'=>'other','action'=>'partnerservice'), null, true);
  $rpt_other_feast=$this->url(array('module'=>'report','controller'=>'other','action'=>'fastiveprogram'), null, true);
  $rpt_borrowandpay=$this->url(array('module'=>'report','controller'=>'other','action'=>'rptborrowandpay'), null, true);
  
  
  
  $user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage(); 
	$session_user=new Zend_Session_Namespace('auth');
	$request=Zend_Controller_Front::getInstance()->getRequest();
	 $level = $result["level"];
  
  ?>
  
<title>របាយការណ៍ ផ្សេងៗ</title>  
  
<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat blue-madison">
						<a class="more" href="<?php echo $rpt_other_donors;?>">
						<div class="visual">
							<i class="fa fa-comments"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 របាយកាណ៍ឧបត្ថមរបស់សប្បុរសជន
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						View more <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat red-intense">
						<a class="more" href="<?php echo $rpt_sponsorship;?>">
						<div class="visual">
							<i class="fa fa-bar-chart-o"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 របាយកាណ៍ប្រគល់ការ ឧបត្ថម						
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						View more <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat blue-madison">
						<a class="more" href="<?php echo $rpt_other_worker;?>">
						<div class="visual">
							<i class="fa fa-comments"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 របាយកាណ៍ជាងសាងសង់
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						View more <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat green-haze">
						<a class="more" href="<?php echo $rpt_partnerservice;?>">
						<div class="visual">
							<i class="fa fa-shopping-cart"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 របាយកាណ៍ដៃគូសេវាកម្ម
								 					
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						View more <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat blue-madison">
						<a class="more" href="<?php echo $rpt_other_feast;?>">
						<div class="visual">
							<i class="fa fa-comments"></i>
						</div>
						<div class="details">
							<div class="number">
							</div>
							<div class="desc">
								 របាយកាណ៍កម្មវិធីបុណ្យ
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						View more <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat red-intense">
						<a class="more" href="<?php echo $rpt_borrowandpay;?>">
						<div class="visual">
							<i class="fa fa-bar-chart-o"></i>
						</div>
						<div class="details">
							<div class="number">
								 
							</div>
							<div class="desc">
								 របាយកាណ៍អ្នកខ្ចីប្រាក់ នឹង អ្នកសងប្រាក់											
							</div>
						</div>
						</a>
						<a class="more" href="javascript:;">
						View more <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				
			</div>