<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->form_listsponorship;
	$rows=$this->other;
//	print_r($this->row);exit();
?>
<title><?php echo $tr->translate("RPT_PURCHASE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i>ការប្រគល់ របស់សប្បុរសជនជូនដល់សព
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" onclick="doPrint();">
									<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
								</a>
							</li>
							<li>
								<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
							</li>								
						</ul>
					</div>
				</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<?php $formFilter = $this->form_listsponorship; ?>
					<div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 14px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang'; " cellpadding="0" cellpadding="0">
		            	<tbody><tr><br>
		                	<td width="20%" valign="top"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:20px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:20px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_PURCHASE");?></li>
		                		</ul>
		                	</td>
		                    <td width="40%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;"></td>
		                				<td width="65%"></td>
		                			</tr>
				                	</tbody>
				                </table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel"> 		    	
		            <tr style="line-height: 27px; color: #000080; font-family:'Khmer OS Muol Light'; font-size:20px; padding:1px 0px;">
		           		<td><u>ឈ្មោះសប្បុរសជនៈ* <?php echo ('សុខ គុង');?></u></td>
		           	</tr>
		           <tr><td>&nbsp;</td></tr>
		            <table  border="1" style="border-collapse:collapse;border:1px solid #000; font-size:14px;" width="100%" cellspacing="0">		               
		                 <thead>
		                 	<tr bgcolor="#b0bdfd" style="font-weight:bold; text-align:center; line-height: 25px; font-size:12px; padding:1px 0px;">
			                    <th style="border:1px solid #000;text-align:center;">&nbsp;<?php echo $tr->translate("NUM");?></th>
								<th style="border:1px solid #000;text-align:center;">&nbsp;ឈ្មោះសព</th>
								<th style="border:1px solid #000;text-align:center;">&nbsp;ភេទ</th>
								<th style="border:1px solid #000;text-align:center;">&nbsp;អាយុ</th>
								<th style="border:1px solid #000;text-align:center;">&nbsp;ថ្ងៃស្លាប់</th>
								<th style="border:1px solid #000;text-align:center;">&nbsp;អាស័យដ្ឋាន</th>
								<th style="border:1px solid #000;text-align:center;">&nbsp;ថ្ងៃជំនួយ</th>
								<th style="border:1px solid #000;text-align:center;">&nbsp;ប្រើប្រាស់</th>
		               	 	</tr>
		                <thead>
		                <?php $num=1;
		                $d_balance = 0;
		                if(!empty($rows))foreach ($rows AS $index => $rs){?>	                
						<tr class='row-format hover' style="border:1px solid #000; text-align:center;">
						   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $index+1?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php //echo $rs["donor_name"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php //echo $rs["donor_female"];?></td>						  
						   <td style="border:1px solid #000;">&nbsp;<?php //echo $rs["date_jom"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php //echo $rs["dead_address"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php //echo $rs["dead_address"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php //echo $rs["dead_address"];?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						</tr>
						   <?php }?>
						   	<tr style="font-size:12px; height: 30px;border: 1px solid #000;" align="center" >
							<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="6"></td>
							<td style="border: 1px solid #000;white-space: nowrap;">សរុបរួម/Grand Total</td>
							<td style="border: 1px solid #000;"><?php echo  number_format($d_balance,2);?></td>
							</tr>
		                </tbody>
		           </table>
		            <br>
		              <table align="center" width="100%">
						   <tbody>
						   	<tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
