<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
// $brach_name =  $this->branch;
?>
<title>របាយការណ៍ អ្នកខ្ចីប្រាក់ នឹង អ្នកសងប្រាក់</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i>របាយការណ៍ អ្នកខ្ចីប្រាក់ នឹង អ្នកសងប្រាក់
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
					 <ul class="dropdown-menu" role="menu">
						<li>
							<a href="#" onclick="doPrint();">
								<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
							</a>
						</li>
						<li>
							<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
						</li>
					 </ul>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<div class="form-group" style="padding-top: 6px;">
						<?php $formFilter = $this->form_borrowandpay; ?>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('ad_search');?></label>	
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch');?></label>	
						<label class="control-label col-md-2">
							<select name="paid_type" id="paid_type" class="form-control select2me" >
								<option value="0" <?php if($this->rssearch['paid_type']==0){echo "selected='selected'";}?>>ជ្រើសរើសប្រភេទ</option>
								<option value="1" <?php if($this->rssearch['paid_type']==1){echo "selected='selected'";}?>>បញ្ជីឈ្មោះអ្នកខ្ចីប្រាក់</option>
								<option value="2" <?php if($this->rssearch['paid_type']==2){echo "selected='selected'";}?>>បញ្ជីឈ្មោះអ្នកសងប្រាក់</option>						
							</select>
						</label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('status');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 11px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 29px; }
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
			            	<tbody>
				            	<tr>
				                	<td align="center" width="16%" valign="top"><img  height="95px" src="<?php echo $this->baseUrl();?>/images/logosbona.jpg"></td>
				                	<td width="70%" valign="top">
				                		<ul>
				                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light';  color: #F31A1A   !important"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
				                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light';  color: #F31A1A   !important">របាយការណ៍ អ្នកខ្ចីប្រាក់ នឹង អ្នកសងប្រាក់</li>
				                			<li style="font-size:17px; text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'; color: #F31A1A  !important;">
							                	<span id="projectName"></span>
							                </li>
				                			<li style="text-align:center; font-size:14px; color: #F31A1A   !important"><?php if(!empty($this->rssearch['start_date'])){?><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));}?></li>
				                		</ul>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
			            	</tbody>
			            </table>
			        </td>
			    </tr>
			    <tr>
			    	<td class="table2excel" id="exportExcel">
			            <?php if(!empty($this->borrowers_payment)){?>
			            <table style="border-collapse:collapse;" width="100%"  cellspacing="0">
			                <tr>
			                    <td style="font-size:18px;font-weight: bold;">បញ្ជីឈ្មោះអ្នកខ្ចីប្រាក់</td>
			                </tr>
			            </table>
			            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;white-space: nowrap;" width="100%" cellspacing="0">
			                 <tbody>
			                 <tr align="center" style="background-color: #b0bdfd !important;font-weight:bold; line-height: 30px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td width="5%">&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td width="15%"><?php echo $tr->translate("ឈ្នោះអ្នកខ្ចី");?></td>					
								<td width="10%">&nbsp;<?php echo $tr->translate("ភេទ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ទូរសព័្ទ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ថ្ងៃខ្ចីប្រាក់");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ចំនួនទឹកប្រាក់ខ្ចី");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ចំនួនទឹកប្រាក់នៅខ្វះ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("កំណត់សម្គាល់");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ស្ថានការ");?></td>
			                </tr>
			                <?php $num=1; $total = 0;$total_balance=0;
			                foreach ($this->borrowers_payment AS $index => $rs){?>
							<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;font-size: 13px;">
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $index+1?></td>
							   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["name_borrow"];?></td>
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $rs["gender"];?></td>
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $rs["phone"];?></td>
							   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["date"];?></td>
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo "$ ".number_format($rs["qtys"],2);?></td>
							    <td align="center" style="border:1px solid #000;">&nbsp;<?php if($rs['is_complete']==0){echo "$ ".number_format($rs["qtys_after"],2);}else{echo "បង់រួច";}?></td>
							   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["notes"];?></td>
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $rs["status"];?></td>
							</tr>
							<?php 
								$total = $total+$rs["qtys"];
								$total_balance = $total_balance + $rs["qtys_after"];
			                }
			                ?>
						</table>
						<table width="40%" align="right" style="margin-top: 5px;border-collapse: collapse;">
							<tbody>
				                <tr style="font-size:14px; height: 30px;border: 1px solid #000;font-weight: bold;" align="center" >
									<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="7"></td>
									<td style="background-color: #b0bdfd !important;border: 1px solid #000;white-space: nowrap;">ចំនួនទឹកប្រាក់សរុប</td>
									<td style="background-color: #b0bdfd !important;border: 1px solid #000;white-space: nowrap;">ចំនួនទឹកប្រាក់នៅខ្វះសរុប</td>
								</tr>
								<tr style="font-size:14px; height: 30px;border: 1px solid #000;font-weight: bold;" align="center" >
									<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="7"></td>
									<td style="border: 1px solid #000;"><?php echo "$ ".number_format($total,2);?></td>
									<td style="border: 1px solid #000;color: red;"><?php echo "$ ".number_format($total_balance,2);?></td>
								</tr>
			                </tbody>
			           </table>
			           <?php }?>
			           
			           
			           <?php if(!empty($this->mepay_payment)){?>
			           <br />
			           <table style="border-collapse:collapse;font-size:12px;" width="100%"  cellspacing="0">
			                <tr>
			                    <td style="font-size:18px;font-weight: bold;">បញ្ជីឈ្មោះអ្នកសងប្រាក់</td>
			                </tr>
			           </table>
			            
			            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;white-space: nowrap;" width="100%" >
			                 <tbody>
			                  <tr align="center" style="background-color: #b0bdfd !important;font-weight:bold; line-height: 30px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td width="5%">&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td width="15%"><?php echo $tr->translate("ឈ្នោះអ្នកសង");?></td>					
								<td width="10%">&nbsp;<?php echo $tr->translate("ភេទ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ទូរសព័្ទ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ថ្ងៃសងប្រាក់");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ចំនួនទឹកប្រាក់សង");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("កំណត់សម្គាល់");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ស្ថានការ");?></td>
			                </tr>
			                <?php $num=1; $partner_service_balance=0;$d_balance = 0;
			                foreach ($this->mepay_payment AS $index => $rs){?>
							<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;font-size: 13px;">
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $index+1?></td>
							   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["name_borrow"];?></td>
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $rs["gender"];?></td>
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $rs["phone"];?></td>
							   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["date"];?></td>
							   <td align="center" style=" border:1px solid #000;">&nbsp;<?php echo "$ ".number_format($rs["qtys"],2);?></td>
							   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["notes"];?></td>
							   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $rs["status"];?></td>
							</tr>
							<?php 
								$d_balance = $d_balance+$rs["qtys"];
			                }?>
						</table>
						<table width="20%" align="right" style="margin-top: 5px;border-collapse: collapse;">
							<tbody>			                
				                <tr style="font-size:14px; height: 30px;border: 1px solid #000;font-weight: bold;" align="center" >
									<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="6"></td>
									<td style="background-color: #b0bdfd !important;border: 1px solid #000;white-space: nowrap;">ចំនួនទឹកប្រាក់សរុប</td>
								</tr>
								<tr style="font-size:14px; height: 30px;border: 1px solid #000;font-weight: bold;" align="center" >
									<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="6"></td>
									<td style="border: 1px solid #000;"><?php echo "$ ".number_format($d_balance,2);?></td>
								</tr>
			                </tbody>
			           </table>
			           <?php }?>
			           <br>
			           <br>
			           <table align="center" width="100%">
							<tbody>
							   <tr style="font-size: 14px;">
							        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
							        <th></th>
							        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
							        <th></th>
							        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
							   </tr>
							</tbody>
						</table>	
		    		</td>
		    	</tr>
			</tbody>
			</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
$(document).ready(function(){
	branch_id = $("#branch").val();
	 if(branch_id!=-1 && branch_id!=0){
		 var bbr = $("#branch option:selected").text();
		 document.getElementById('projectName').innerHTML = bbr+"<br />";
	 }
});
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
