<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->form_donors;
?>
<title><?php echo $tr->translate("របាយកាណ៍ឧបត្ថមរបស់សប្បុរសជន");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i>របាយកាណ៍ឧបត្ថមរបស់សប្បុរសជន
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" onclick="doPrint();">
									<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
								</a>
							</li>
							<li>
								<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
							</li>								
						</ul>
					</div>
				</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<?php $formFilter = $this->form_donors; ?>
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('ad_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('status');?></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>
					<div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 14px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		
	</style>
	<?php //echo $this->baseUrl();?>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td align="center" width="16%" valign="top"><img  height="95px" src="<?php echo $this->baseUrl();?>/images/logosbona.jpg"></td>
		                	<td width="70%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:17px; font-family:'Khmer OS Muol Light'">របាយកាណ៍ឧបត្ថមរបស់សប្បុរសជន</li>
		                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->rssearch['start_date'])){?><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));}?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;"></td>
		                				<td width="65%"></td>
		                			</tr>
				                	</tbody>
				                </table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table  border="1" style="border-collapse:collapse; border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <thead>
		                 	<tr bgcolor="#b0bdfd" align="center" style="font-weight:bold; line-height: 24px; border:1px solid #000; font-size:13px; padding:1px 0px; white-space: nowrap; ">
			                    <td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td style="border:1px solid #000;"><?php echo $tr->translate("ឈ្មោះប្ដី");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("ឈ្មោះប្រពន្ធ");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("លេខទូរស័ព្ទ");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("អាសយដ្ឋាន");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("តម្រូវការ");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("ប្រើយូរបំផុត	");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("សម្គាល់ផ្សេង	");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("លេខបង្កាន់ដៃ");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("ថ្ងៃបង់ប្រាក់	");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("ចំនួនម្ឈូស");?></td>
								<td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("តម្លៃរាយ");?></td>
								<td>&nbsp;<?php echo $tr->translate("តម្លៃសរុប");?></td>								
						        <td>&nbsp;<?php echo $tr->translate("អ្នកប្រើប្រាស់");?></td>
		               		 </tr>
		                </thead>
		                <?php $num=1; 
		                $total_amount = 0;
		                if(!empty($this->other))foreach ($this->other AS $index => $rs){?>		                
						<tr class='row-format hover' style="border:1px solid #000; text-align:center;white-space: nowrap;">
						   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $index+1?></td>
						   <td align="left" style="border:1px solid #000;"><a style="color:#000080;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/other/listsponorship/id/".$rs["id"];?>">&nbsp;<?php echo $rs["donor_name"];?></a></td>
						   <td align="left" style="border:1px solid #000;"><a style="color:#000080;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/other/listsponorship/id/".$rs["id"];?>">&nbsp;<?php echo $rs["donor_female"];?></a></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["tel"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["address"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["required_using"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["invalid_date"]));?></td>
						   <td align="left" style="border:1px solid #000;">&nbsp;<?php echo $rs["note"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["receipt_no"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["paid_date"]));?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo number_format($rs["qty"],0);?></td>
						   <td align="left" style="border:1px solid #000;">&nbsp;<?php echo "$ ".number_format($rs["unit_price"],2);?></td>
						   <td align="left" style="border:1px solid #000;">&nbsp;<?php echo "$ ".number_format($rs["total_amount"],2);?></td>		
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						   <!-- <td>&nbsp;<a style="color:#000;text-decoration: none;" target="_blank" href="<?php //echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>"><?php echo $tr->translate("PRINT");?></a></td> -->
						</tr>
						   <?php 
							$total_amount = $total_amount+$rs["total_amount"];
                   		 }?>
                    	<tr style="font-size:13px;font-weight:bold; height: 40px;border: 1px solid #000;" align="center" >
							<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="12"></td>
							<td style="border: 1px solid #000;white-space: nowrap;">Grand Total</td>
							<td style="border: 1px solid #000;"><?php echo  "$ ".number_format($total_amount,2);?></td>
						</tr>
		                </tbody>
		           </table>
		            <br>
		              <table align="center" width="100%">
						   <tbody>
						   	<tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
