<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->form_sponsorship;
?>
<title><?php echo $tr->translate("RPT_PURCHASE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i>របាយការណ៍ប្រគល់ការ ឧបត្ថម
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" onclick="doPrint();">
									<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
								</a>
							</li>
							<li>
								<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
							</li>								
						</ul>
					</div>
				</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<?php $formFilter = $this->form_sponsorship; ?>
					<div class="form-group" style="padding-top: -6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('ad_search');?></label>
					</div>
					<div class="form-group" style="padding-top: -6px;">
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('status');?></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>
					<div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 14px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td align="center" width="16%" valign="top"><img  height="95px" src="/bonastock/trunk/public/images/logosbona.jpg"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:17px; font-family:'Khmer OS Muol Light'">របាយការណ៍ប្រគល់ការ ឧបត្ថម</li>
		                			<li style="text-align:center; font-size:16px;"><?php if(!empty($this->rssearch['start_date'])){?><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់  <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));}?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;"></td>
		                				<td width="65%"></td>
		                			</tr>
				                	</tbody>
				                </table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table  border="1" style="border-collapse:collapse;border:1px solid #000; font-size:14px;" width="100%" cellspacing="0">
		                 <thead>
		                 	<tr bgcolor="#b0bdfd" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
								<td>&nbsp;<?php echo $tr->translate("BODY_NAME");?></td>
								<!--<td>&nbsp;<?php //echo $tr->translate("PURCHASE_ORDER");?></td> -->
								<td>&nbsp;<?php echo $tr->translate("GENDER");?></td>
								<td>&nbsp;<?php echo $tr->translate("YEAR_AGE");?></td>
								<td><?php echo $tr->translate("DATE_SPONSOR");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ADDRESS");?></td>
								<td>&nbsp;<?php echo $tr->translate("NAME_SPONSOR");?></td>
								<td>&nbsp;<?php echo $tr->translate("DATE_MJOS");?></td>
								<td>&nbsp;សម្គាល់(ភាសាខ្មែរ)</td>
								<td>&nbsp;<?php echo $tr->translate("NOTE_CHINESS");?></td>
								<td>&nbsp;<?php echo $tr->translate("CREATION_DATE");?></td>
								<!-- <td>&nbsp;<?php //echo $tr->translate("PAYMENT_METHOD");?></td>
								
								<td>&nbsp;<?php //echo $tr->translate("STATUS");?></td> -->
						        <td>&nbsp;<?php echo $tr->translate("BY_USER");?></td>
							<!-- <td style="white-space: nowrap;">&nbsp;<?php //echo $tr->translate("PRINT");?></td> -->
		               	 </tr>
		                <thead>
		                <?php $num=1; 
		               
		                if(!empty($this->other))foreach ($this->other AS $index => $rs){?>
		                
						<tr class='row-format hover' style="border:1px solid #000; ">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["donor_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["dead_sex"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["dead_age"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["date_jom"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["dead_address"];?></td>
						   <td style="white-space: nowrap;"><a style="color:#000080;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/donors/donate/donorpeople/id/".$rs["id"];?>">&nbsp;<?php echo $rs["donor_name"];?></a></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["date_jenh"];?></td>
						    <td style="white-space: nowrap;">&nbsp;<?php echo $rs["note"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["notes"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["create_date"];?></td>
					
						   <!-- <td>&nbsp;<?php //echo $rs["payment_method"];?></td>
						   <td>&nbsp;<?php //echo $rs["purchase_status"];?></td> -->
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						   <!-- <td>&nbsp;<a style="color:#000;text-decoration: none;" target="_blank" href="<?php //echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>"><?php echo $tr->translate("PRINT");?></a></td> -->
						</tr>
						   <?php 
							
                    }?>
		                </tbody>
		           </table>
		            <br>
		           
		              <br>
		              <table align="center" width="100%">
						   <tbody>
						   	<tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
