<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->form_worker;
	$search = $this->search;
?>
<title><?php echo $tr->translate("RPT_PURCHASE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i>ជាងសាងសង់		
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" onclick="doPrint();">
									<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
								</a>
							</li>
							<li>
								<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
							</li>								
						</ul>
					</div>
				</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
					<?php $formFilter = $this->form_worker; ?>
					<div class="form-group" style="padding-top: -6px;">
						<label class="control-label col-md-4"><?php echo $formFilter->getElement('ad_search');?></label>
						<label class="control-label col-md-4"><?php echo $formFilter->getElement('status');?></label>
					</div>
					<div class="form-group" style="padding-top: -6px;">
						<label class="control-label col-md-4">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>
					<div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 14px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}		
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td align="center" width="16%" valign="top"><img  height="95px" src="/bonastock/trunk/public/images/logosbona.jpg"></td>
		                	<td width="70%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("COMPANY_PRIVATE");?></li>
		                			<li style="text-align:center; font-size:17px; font-family:'Khmer OS Muol Light'">របាយការណ៍ ជាងសាងសង់</li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;"></td>
		                				<td width="65%"></td>
		                			</tr>
				                	</tbody>
				                </table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table  border="1" style="border-collapse:collapse;border:1px solid #000; font-size:14px;" width="100%" cellspacing="0">
		                 <thead>
		                 	<tr bgcolor="#b0bdfd" class="style" align="center" style="font-weight:bold; line-height: 23px; font-size:11px; padding:1px 0px; white-space: nowrap; ">
			                    <td style="border:1px solid #000;">&nbsp;<?php echo $tr->translate("NUM");?></td>
								<td style="border:1px solid #000;">&nbsp;ឈ្មោះអ្នកម៉ៅការ</td>
								<td style="border:1px solid #000;">&nbsp;ភេទ</td>
								<td style="border:1px solid #000;">&nbsp;លេខទូរស័ទ្ទ</td>
								<td style="border:1px solid #000;">&nbsp;អ៊ីម៉ែល</td>
								<td width="30%" style="border:1px solid #000;">&nbsp;អាស័យដ្ឋាន</td>
								<td style="border:1px solid #000;">&nbsp;ប្រភេទជាង</td>
								<td style="border:1px solid #000;">&nbsp;សម្គាល់</td>
								<td style="border:1px solid #000;">&nbsp;ថ្ងៃបង្កើត</td>
						        <td>&nbsp;ប្រើប្រាស់</td>					
		               	 	</tr>
		                <thead>
		                <?php $num=1;
		                $d_balance = 0;
		                $db_bal = 0;
		                if(!empty($this->other))foreach ($this->other AS $index => $rs){?>     
						<tr class='row-format hover' style="border:1px solid #000; font-size:12px; ">
						   <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $index+1?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["name"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["sex"];?></td>
						  
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["sex"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["email"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["address"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["constructor_type"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["note"];?></td>
						   <td style="border:1px solid #000;">&nbsp;<?php echo $rs["create_date"];?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>					
						</tr>
						   <?php }?>               
		                </tbody>
		           </table>
		              <br>
		              <table align="center" width="100%">
						   <tbody>
						   	<tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
