<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'payment','action'=>'add'));
?>
<title><?php echo $tr->translate("Customer Payment");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("Customer Payment")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body" style="background:#fbf9f9;">
						<div class="form-group">
							<label class="control-label col-md-2"> <?php echo $tr->translate("អតិថិជន");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<select name="customer_id" id="customer_id" class="form-control select2me" onchange="getCustomerInfo(1);" >
										<option value="-1">ជ្រើសរើសអតិថិជន</option>
										<?php if(!empty($this->customer_name)){foreach($this->customer_name as $customer){?>
										<option value="<?php echo $customer['id']?>"><?php echo $customer['name']?></option>
										<?php }}?>
									</select>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("លេខវិក័យបត្រ");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<select name="invoice_id" id="invoice_id" class="form-control select2me" onchange="getCustomerInfo(2);" >
										<option value="-1">ជ្រើសរើសវិក័យបត្រ</option>
										<?php if(!empty($this->customer_invoice)){foreach($this->customer_invoice as $invoice){?>
										<option value="<?php echo $invoice['id']?>"><?php echo $invoice['name']?></option>
										<?php }}?>
									</select>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2">Customer Information
							</label>
							<div class="col-md-4">
								<input type="text" class="form-control" name="customer_info" id="customer_info" readonly />
								<input type="hidden" id="cus_id" name="cus_id" />
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("លេខបង្កាន់ដៃ");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<input type="text" class="form-control" name="receipt" id="receipt" readonly value="<?php echo $this->receipt;?>" />
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("បង់ជា");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<select name="payment_id" id="payment_id" class="form-control select2me" onchange="checkpayment();" >
									<option value="1">Cash</option>
									<option value="2">Cheque</option>
									<option value="3">Credit</option>
									<option value="4">Bank Transtransfer</option>
								</select>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("សែក");?>
								<span class="required">*</span>
							</label>
							<div class="col-md-2">
								<input type="text" class="form-control" name="cheque" id="cheque" readonly placeholder="លេខសែក"​/>
							</div>
							<div class="col-md-2">
								<input type="text" class="form-control" name="bank_name" id="bank_name" readonly placeholder="ឈ្មោះធនាគារ"/>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2">
								<?php echo $tr->translate("សម្គាល់");?>
							</label>
							<div class="col-md-4">
								<textarea name="other_note" id="other_note" class="form-control" rows="3"></textarea>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("កាលបរិច្ឆេទ");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa fa-calendar"></i>
									<input class="form-control date-picker" name="date_in" id="date_in" value="<?php echo date("d-m-Y")?>" data-date-format="dd-mm-yyyy" />
								</div>
							</div>
						</div>
						
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px" align="center" style="font-weight: bold;">
									<td><?php echo $tr->translate("NUM");?></td>
									<td style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃបង់");?></td>
									<td><?php echo $tr->translate("លេខបង្កាន់ដៃ");?></td>
									<td><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></td>
									<td><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></td>
									<td><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></td>
								</tr>
							</table>
						 	<input type="hidden" id="identity" name="identity" />
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-7"><span class="required">
								 </span>
							</label>
							<label class="control-label col-md-2">
								<?php echo $tr->translate("ជំពាក់សរុប​ :");?>Total
							</label>
							<div class="col-md-3">
								<input type="text" class="form-control" name="all_total" id="all_total" readonly />
							</div>
						</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-7">
							</label>
							<label class="control-label col-md-2">
								<?php echo $tr->translate("ប្រាក់បានបង់");?> (Paid)
							</label>
							<div class="col-md-3">
								<input type="text" class="form-control" name="paid" id="paid" onkeyup="doRemain();" />
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-7">
							</label>
							
							<label class="control-label col-md-2">
								ប្រាក់នៅសល់ (Balance)​ :<span class="required">*</span>
							
							</label>
							<div class="col-md-3">
								<input type="text" class="form-control" name="balance" id="balance" readonly />
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-4"></div>
							<div class="col-md-2">
								<a href="<?php echo $this->baseUrl();?>/sales/payment/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<button type="submit" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-4">
							</div>
						</div>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- end new product -->
<script>
	function paidtotal(type){//1=dollar,2=riel
		paid_dollar = $("#paid_dollar").val();
		paid_riel = $("#paid_riel").val();
		dollar_fromriel = parseFloat(paid_riel/$("#exchange_rate").val());
		all_paid =  parseFloat(paid_dollar) + parseFloat(dollar_fromriel);
		all_paid = (all_paid).toFixed(2);
		$("#paid").val(all_paid);
		doRemain();
	}
	
	function checkpayment(){
		payment_id = $("#payment_id").val();
		if(payment_id==2){
			$( "#bank_name" ).attr( "readOnly", false );
			$( "#cheque" ).attr( "readOnly", false );
		}else{
			$("#bank_name").val("");
			$("#cheque").val("");
			$( "#bank_name" ).attr( "readOnly", true );
			$( "#cheque" ).attr( "readOnly", true );}
	}
	
	
	<?php $urlreceipt =  $this->url(array('module'=>'sales','controller'=>'payment','action'=>'get-receipt')); ?>
	function getReceipt(){
		cus_id=$("#cus_id").val();
		mong_id = $('#customer_id').val();
		if(cus_id>0 && mong_id>0){
			//alert(cus_id+"-"+mong_id);
			$.ajax({
				url:"<?php echo $urlreceipt;?>",
				type:"post",
				data:{'mong_id':mong_id,'cus_id':cus_id,'type_id':1},
				success: function(data){	
					$("#table_order").html("");
					template='<tr height="33px" align="center" style="font-weight: bold;">';
						template+='<td><?php echo $tr->translate("NUM");?></td>';
						template+='<td style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃបង់");?></td>';
						template+='<td><?php echo $tr->translate("លេខបង្កាន់ដៃ");?></td>';
						template+='<td><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></td>';
						template+='<td><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></td>';
						template+='<td><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></td>';
					template+='</tr>';
					
					$('#identity').val("");
					data = $.parseJSON(data);
					
					for(i=0;i<data.length;i++){
						/*if(i==0){
							$("#customer_id").val(data[i].customer_id);
							$("#customer_id").select2();
						}*/
						index=i+1;
						template+='<tr style="height:30px;" align="center">';
							template+='<td >'+index+'</td>';
							template+='<td >'+data[i].receipt_date+'</td>';
							template+='<td >'+data[i].receipt_no+'<input type="hidden" value='+data[i].id+' id="invoice_no'+index+'" name="invoice_no'+index+'"/></td>';
							template+='<td >'+data[i].begining_balance+'<input type="hidden" value='+data[i].net_total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
							if(data[i].paid==null){data[i].paid=0;}
							template+='<td >'+data[i].paid+'<input type="hidden" value='+data[i].paid+' id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
							template+='<td >'+data[i].balance+'<input type="hidden" value='+data[i].balance+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
						template+="</tr>";
						
						if($('#identity').val()!="") {
							var identity = $('#identity').val();
							$('#identity').val(identity+','+index);
						} else {$('#identity').val(index);}
					}
					$('#table_order').append(template);
					
					//if(data.length>0){netTotal();}else{$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}
				},
				error:function(e){
					alert("error"+e);
				}
			});	
		}
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		$("#row_order_"+index).remove();
		netTotal();
	}
	function doRemain() {
		var all_total = Number($('#all_total').val());
		var paid = Number($('#paid').val());
		if(paid > all_total){
			var paid = $('#paid').val(all_total);
			 $('#balance').val(0);
	   }else{
		   remain = all_total-paid;
		   $('#balance').val(remain.toFixed(2));
		}	
	}

	<?php $url =  $this->url(array('module'=>'sales','controller'=>'payment','action'=>'get-customer-info')); ?>
	function getCustomerInfo(type){
		if(type==1){
			var id = $('#customer_id').val();
			$('#invoice_id').val(id).select2();
		}else{
			var id = $('#invoice_id').val();
			$('#customer_id').val(id).select2();
		}
		//alert(id);
		if(id>0){
			$.ajax({
				url: "<?php echo $url;?>",
				type: "post",
				data: {'id':id},
				success: function(data){
					rs = $.parseJSON(data);
					if(data){
						$('#cus_id').val(rs.customer_id);
						customer_info = "Code : "+rs.cu_code+", "+"Phone : "+rs.phone+", Address : "+rs.address;
						$('#customer_info').val(customer_info);
						$('#all_total').val(rs.balance_after);
						$('#paid').val(rs.balance_after);
						doRemain();
						
						getReceipt();
					}
				},
				error:function(err){
					alert("failed");
				}
			});
		}

	}

</script>	