<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form_sale;
	$url_submit = $this->url(array('module'=>'sales','controller'=>'payment','action'=>'edit'));
?>
<title><?php echo $tr->translate("កែប្រែបង់ប្រាក់ថ្លៃលក់");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("កែប្រែបង់ប្រាក់ថ្លៃលក់")?>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post" autocomplete="off">
					
					<div class="form-body" style="background:#fbf9f9;">
						<div class="form-group">
							<label class="control-label col-md-2"> <?php echo $tr->translate("អតិថិជន");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<select name="customer_id" id="customer_id" class="form-control select2me" onchange="getCustomerInfo(1);" >
										<option value="-1">ជ្រើសរើសអតិថិជន</option>
										<?php if(!empty($this->customer_name)){foreach($this->customer_name as $customer){?>
										<option value="<?php echo $customer['id']?>" <?php if($customer['id']==$this->row['invoice_id']){echo "selected='selected'";}?>><?php echo $customer['name']." - ".$customer['place_bun']." - ".$customer['phone']?></option>
										<?php }}?>
									</select>
								</div>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("លេខវិក័យបត្រ");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<select name="invoice_id" id="invoice_id" class="form-control select2me" onchange="getCustomerInfo(2);" >
										<option value="-1">ជ្រើសរើសវិក័យបត្រ</option>
										<?php if(!empty($this->customer_invoice)){foreach($this->customer_invoice as $invoice){?>
										<option value="<?php echo $invoice['id']?>" <?php if($invoice['id']==$this->row['invoice_id']){echo "selected='selected'";}?>><?php echo $invoice['name']?></option>
										<?php }}?>
									</select>
								</div>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2">Customer Information
							</label>
							<div class="col-md-4">
								<input type="text" class="form-control" name="customer_info" id="customer_info" readonly />
								<input type="hidden" id="cus_id" name="cus_id" />
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("លេខបង្កាន់ដៃ");?><span class="required">
								 </span>
							</label>
							<div class="col-md-4">
								<input type="text" class="form-control" style="color:red" value="<?php echo $this->row['receipt_no'];?>" name="receipt" id="receipt" readonly  />
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("បង់ជា");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<select name="payment_id" id="payment_id" class="form-control select2me" onchange="checkpayment();" >
									<option value="1" <?php if($this->row['payment_id']==1){echo "selected='selected'";}?>>Cash</option>
									<option value="2" <?php if($this->row['payment_id']==2){echo "selected='selected'";}?>>Cheque</option>
									<option value="3" <?php if($this->row['payment_id']==3){echo "selected='selected'";}?>>Credit</option>
									<option value="4" <?php if($this->row['payment_id']==4){echo "selected='selected'";}?>>Bank Transtransfer</option>
								</select>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("សែក");?>
								<span class="required">*</span>
							</label>
							<div class="col-md-2">
								<input type="text" class="form-control" name="cheque" id="cheque" value="<?php echo $this->row['cheque_number'];?>" readonly placeholder="លេខសែក"​/>
							</div>
							<div class="col-md-2">
								<input type="text" class="form-control" name="bank_name" id="bank_name" value="<?php echo $this->row['bank_name'];?>" readonly placeholder="ឈ្មោះធនាគារ"/>
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-2">
								<?php echo $tr->translate("សម្គាល់");?>
							</label>
							<div class="col-md-4">
								<textarea name="other_note" id="other_note" class="form-control" rows="1" ><?php echo $this->row['remark'];?></textarea>
							</div>
							
							<label class="control-label col-md-2"><?php echo $tr->translate("កាលបរិច្ឆេទ");?><span class="required">
							*</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa fa-calendar"></i>
									<input class="form-control date-picker" name="date_in" id="date_in" value="<?php echo date("d-m-Y",strtotime($this->row['receipt_date']))?>" data-date-format="dd-mm-yyyy" />
								</div>
							</div>
						</div>
						
						<div class="form-group" style="">
							<label class="control-label col-md-2"><?php echo $tr->translate("ស្ថានភាព");?></span>
							</label>
							<div class="col-md-4">
								<select name="status" id="status" class="form-control select2me" >
									<option value="1" <?php if($this->row['status']==1){echo "selected='selected'";}?>>ប្រើប្រាស់</option>
									<option value="0" <?php if($this->row['status']==0){echo "selected='selected'";}?>>មិនប្រើប្រាស់</option>
								</select>
							</div>
							
							<label class="col-md-2 control-label">
								អ្នកទទួលប្រាក់
							</label>
							<div class="col-md-4">
								<select class="form-control select2me" id="receiver_name" name="receiver_name" onchange="getPopupReceiver()" >
									<option value="0">ជ្រើសរើសអ្នកទទួលប្រាក់</option>
									<option value="-1">បន្ថែមថ្មី</option>
									<?php if(!empty($this->receiver_name)){foreach($this->receiver_name as $rs){?>
										<option value="<?php echo $rs['name'];?>" <?php if($this->row['receiver_name']==$rs['name']){echo "selected='selected'";}?>><?php echo $rs['name'];?></option>
									<?php }}?>
								</select>
							</div>
						</div>
						
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px" align="center" style="font-weight: bold;">
									<td><?php echo $tr->translate("NUM");?></td>
									<td style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃបង់");?></td>
									<td><?php echo $tr->translate("លេខបង្កាន់ដៃ");?></td>
									<td><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></td>
									<td><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></td>
									<td><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></td>
								</tr>
							</table>
						 	<input type="hidden" id="identity" name="identity" />
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-7"><span class="required">
								 </span>
							</label>
							<label class="control-label col-md-2">
								<?php echo $tr->translate("ជំពាក់សរុប​ :");?>Total
							</label>
							<div class="col-md-3">
								<input type="text" class="form-control" name="all_total" id="all_total" value="<?php echo $this->row['total'];?>" readonly />
							</div>
						</div>
						
						<div class="form-group">
							<label class="control-label col-md-7">
							</label>
							<label class="control-label col-md-2">
								<?php echo $tr->translate("ប្រាក់បានបង់");?> (Paid)
							</label>
							<div class="col-md-3">
								<input type="text" class="form-control" name="paid" id="paid" value="<?php echo $this->row['paid'];?>" onkeyup="doRemain();" />
							</div>	
						</div>
						<div class="form-group">
							<label class="control-label col-md-7">
							</label>
							
							<label class="control-label col-md-2">
								ប្រាក់នៅសល់ (Balance)​ :<span class="required">*</span>
							
							</label>
							<div class="col-md-3">
								<input type="text" class="form-control" name="balance" id="balance" value="<?php echo $this->row['balance'];?>" readonly />
							</div>
						</div>
						<div class="form-group">
							<div class="col-md-4"></div>
							<div class="col-md-2">
								<a href="<?php echo $this->baseUrl();?>/sales/payment/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<button type="submit" id="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("កែប្រែទិន្នន័យ")?></button>
								</div>
							</div>
							<div class="col-md-4">
							</div>
						</div>
					</div>	
				</form>
			</div>
		</div>
	</div>
</div>
<!-- end new product -->
<script>
	$(document).ready(function() {
		getCustomerInfo(0);
		setReadonly();
	});
	
	function setReadonly(){
		$('#customer_id').prop('readonly', true);
		$('#invoice_id').prop('readonly', true);
		$('#payment_id').prop('readonly', true);
		$('#date_in').prop('readonly', true);
		$('#other_note').prop('readonly', true);
		$('#receiver_name').prop('readonly', true);
		$('#paid').prop('readonly', true);
		
		status = "<?php echo $this->row['status']?>";
		if(status==0){
			$('#status').prop('readonly', true);
		}
	}
	
	$('#frm').submit(function() {
		customer_id=$("#customer_id").val();
		if(customer_id<=0){
			alert("Please select customer !!!");
			$('#customer_id').select2('open');
			return false;	
		}
		
		paid=$("#paid").val();
		if(paid<=0){
			alert("Please input paid amount");
			$('#paid').focus();
			return false;	
		}
		var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
		if (r == true) {
			$("#save_close").attr("disabled", true);
			return true;
		} else {
		   return false;	    
		}
	});

	function paidtotal(type){//1=dollar,2=riel
		paid_dollar = $("#paid_dollar").val();
		paid_riel = $("#paid_riel").val();
		dollar_fromriel = parseFloat(paid_riel/$("#exchange_rate").val());
		all_paid =  parseFloat(paid_dollar) + parseFloat(dollar_fromriel);
		all_paid = (all_paid).toFixed(2);
		$("#paid").val(all_paid);
		doRemain();
	}
	
	function checkpayment(){
		payment_id = $("#payment_id").val();
		if(payment_id==2){
			$( "#bank_name" ).attr( "readOnly", false );
			$( "#cheque" ).attr( "readOnly", false );
		}else{
			$("#bank_name").val("");
			$("#cheque").val("");
			$( "#bank_name" ).attr( "readOnly", true );
			$( "#cheque" ).attr( "readOnly", true );}
	}
	
	
	<?php $urlreceipt =  $this->url(array('module'=>'sales','controller'=>'payment','action'=>'get-receipt')); ?>
	function getReceipt(){
		cus_id=$("#cus_id").val();
		mong_id = $('#customer_id').val();
		if(cus_id>0 && mong_id>0){
			//alert(cus_id+"-"+mong_id);
			$.ajax({
				url:"<?php echo $urlreceipt;?>",
				type:"post",
				data:{'mong_id':mong_id,'cus_id':cus_id,'type_id':1,'action':'edit'},
				success: function(data){	
					$("#table_order").html("");
					template='<tr height="33px" align="center" style="font-weight: bold;">';
						template+='<td><?php echo $tr->translate("NUM");?></td>';
						template+='<td style="white-space:nowrap;"><?php echo $tr->translate("ថ្ងៃបង់");?></td>';
						template+='<td><?php echo $tr->translate("លេខបង្កាន់ដៃ");?></td>';
						template+='<td><?php echo $tr->translate("ចំនួនទឹកប្រាក់");?></td>';
						template+='<td><?php echo $tr->translate("ទឹកប្រាក់បានបង់");?></td>';
						template+='<td><?php echo $tr->translate("ទឹកប្រាក់នៅខ្វះ");?></td>';
						template+='<td><?php echo $tr->translate("សម្គាល់");?></td>';
						template+='<td><?php echo $tr->translate("ស្ថានភាព");?></td>';
					template+='</tr>';
					
					$('#identity').val("");
					data = $.parseJSON(data);
					
					for(i=0;i<data.length;i++){
						/*if(i==0){
							$("#customer_id").val(data[i].customer_id);
							$("#customer_id").select2();
						}*/
						index=i+1;
						template+='<tr style="height:30px;" align="center">';
							template+='<td >'+index+'</td>';
							template+='<td >'+data[i].receipt_date+'</td>';
							template+='<td >'+data[i].receipt_no+'<input type="hidden" value='+data[i].id+' id="invoice_no'+index+'" name="invoice_no'+index+'"/></td>';
							template+='<td >'+data[i].begining_balance+'<input type="hidden" value='+data[i].net_total+' id="subtotal'+index+'" name="subtotal'+index+'"/></td>';
							if(data[i].paid==null){data[i].paid=0;}
							template+='<td >'+data[i].paid+'<input type="hidden" value='+data[i].paid+' id="paid_amount'+index+'" name="paid_amount'+index+'"/></td>';
							template+='<td >'+data[i].balance+'<input type="hidden" value='+data[i].balance+' id="balance_after'+index+'" name="balance_after'+index+'"/></td>';
							template+='<td >'+data[i].remark+'<input type="hidden" value='+data[i].remark+' id="remark_'+index+'" name="remark_'+index+'"/></td>';
							template+='<td >'+data[i].status_name+'<input type="hidden" value='+data[i].status_name+' id="status_'+index+'" name="status_'+index+'"/></td>';
						template+="</tr>";
						
						if($('#identity').val()!="") {
							var identity = $('#identity').val();
							$('#identity').val(identity+','+index);
						} else {$('#identity').val(index);}
					}
					$('#table_order').append(template);
					
					//if(data.length>0){netTotal();}else{$('#balance').val(0);$('#all_total').val(0);$('#paid').val(0); alert("No invoice to make payment");}
				},
				error:function(e){
					alert("error"+e);
				}
			});	
		}
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		$("#row_order_"+index).remove();
		netTotal();
	}
	function doRemain() {
		var all_total = Number($('#all_total').val());
		var paid = Number($('#paid').val());
		if(paid > all_total){
			var paid = $('#paid').val(all_total);
			 $('#balance').val(0);
	   }else{
		   remain = all_total-paid;
		   $('#balance').val(remain.toFixed(2));
		}	
	}

	<?php $url =  $this->url(array('module'=>'sales','controller'=>'payment','action'=>'get-customer-info')); ?>
	function getCustomerInfo(type){
		if(type==1){
			var id = $('#customer_id').val();
			$('#invoice_id').val(id).select2();
		}else if(type==2){
			var id = $('#invoice_id').val();
			$('#customer_id').val(id).select2();
		}else if(type==0){
			var id = $('#invoice_id').val();
		}
		//alert(id);
		if(id>0){
			$.ajax({
				url: "<?php echo $url;?>",
				type: "post",
				data: {'id':id},
				success: function(data){
					rs = $.parseJSON(data);
					if(data){
						$('#cus_id').val(rs.customer_id);
						customer_info = "Code : "+rs.cu_code+", "+"Phone : "+rs.phone+", Address : "+rs.address;
						$('#customer_info').val(customer_info);
						getReceipt();
						if(type!=0){
							$('#all_total').val(rs.balance_after);
							$('#paid').val(rs.balance_after);
							doRemain();
						}
					}
				},
				error:function(err){
					alert("failed");
				}
			});
		}

	}
	
	function getPopupReceiver(){
		val = $('#receiver_name').val();
		if(val==-1){
			$('#receiverpopup').modal('show');
		}
	}
	
	function addNewReceiver(){
		name = $("#name_receiver").val();
		if(name==''){
			$("#name_receiver").focus();
			return false;
		} 
		$('#save_receiver').attr("disabled", true);
		$('#receiver_name').append($("<option></option>").attr("value",name).attr("selected",true).text(name));  
		$("#receiver_name").select2();	
		$('#receiverpopup').modal('hide');
		$('#save_receiver').attr("disabled", false);
	}

</script>	


 <div id="receiverpopup" class="modal fade" tabindex="-1" data-width="1000">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">   
				<div class="row">
					<div class="col-md-12">
						<div class="portlet box blue">
							<div class="portlet-title">
								<div class="caption">
									<i class="icon-home"></i><?php echo $tr->translate("បន្ថែមអ្នកទទួលប្រាក់");?>
								</div>
								<div class="caption pull-right">
									<a href="<?php //echo $url_new;?>" >
										 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
									</a>
								</div>
							</div>
							<div class="portlet-body form">
								<form id="frmreceiver" name="frmreceiver" dojoType="dijit.form.Form" autoComplete="off" enctype="application/x-www-form-urlencoded" class="form-horizontal" enctype="multipart/form-data" method="post">
									<div class="form-body">
										<div class="form-group">
											<label class="control-label col-md-3">
												<?php echo $tr->translate("ឈ្មោះអ្នកទទួលប្រាក់");?>
											</label>
											<div class="col-md-9">
												<div class="input-icon right">
													<input name="name_receiver" id="name_receiver" class="form-control" />
												</div>
											</div>
										</div>
										<div class="form-group">
											<label  class="col-md-12 center">
												<button type="button" id="save_receiver" name="save_receiver" onclick="addNewReceiver();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("រក្សាទុក")?> </button>
											</label>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>
    </div>
 </div>
