<title>បង្កាន់ដៃបង់ប្រាក់</title>
<center>
<?php 
	$rs = $this->rs;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<div id="PrintReceipt" style="border:1px dashed #ccc;width:22cm !important; padding: 0px; margin-bottom:30px; ">
		<style>
			.hearder_table{height:25px !important;}
			.defaulheight{line-height: 22px !important;}
			#PrintReceipt{display: table;}
			#pageFooter {
			    display: table-footer-group;
			}
			#pageFooter:after {
			    counter-increment: page;
			    content:"Page " counter(page);
			    left: 0; 
			    top: 100%;
			    white-space: nowrap; 
			    z-index: 20px;
			    -moz-border-radius: 5px; 
			    -moz-box-shadow: 0px 0px 4px #222;  
			    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
			    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
		  	}
		</style>
	<table class="print" cellspacing="0" cellpadding="0" style="width:98%;font-family: 'Khmer OS Battambang'; margin-top: 10px;white-space:nowrap;">
		<tbody>
			<tr height="40px;">
			    <td colspan="10" style="" align="center" valign="top">
					<table width="100%" border="0" style="font-size: 14px;margin-bottom: 0px; white-space: nowrap;"   >
						<tr>
							<td width="35%" valign="top">
								
							</td>
							<td width="30%" align="center" valign="top" style="line-height: 35px;">
								<div style="font-size: 32px;font-family:'Khmer OS Muol Light'; color:red !important;">ចៅ ប៊ុនណា 73</div>
								<div style="font-size: 23px;font-family:'Khmer OS Muol Light'; color:black;">សេវាកម្មបុណ្យសពតាំងពីឆ្នាំ 1982</div>
								<div style="font-size: 23px;font-family:'Khmer OS Muol Light';font-weight: bold; color:red !important;">周德福棺木店</div>
								<div style="font-size: 23px;font-family:'Khmer OS Muol Light';font-weight: bold; color:blue !important;"><i class="fa fa-facebook-square" style="font-size: 32px;"></i> Chao Bunna 73 Funeral Service</div>
								<div style="font-size: 22px;font-family:'Khmer OS Muol Light'; color: red !important;">បង្កាន់ដៃបង់ប្រាក់</div>
								<div style="font-size: 20px;font-family:Times New Roamn;font-weight: bold; color: red !important;">OFFICIAL RECEIPT</div>
							</td>
							<td width="35%" valign="top" align="center">
								<img style="height:115px; width:150px; alt="<?php ?>" src="<?php echo $this->baseUrl()?>/images/logosbona.jpg"><br />
								<div style="font-size: 19px;font-family:'Khmer OS Muol Light';text-align: center;width:90%;"><?php echo $tr->translate("PHONE_BUNA");?></div>
								
							</td>
							
						</tr>
					</table>                
			    </td>
			</tr>
			<style>
				.bold{
					font-weight:bold;
					}
				.tablesorter td{font-family:'khmer os battambang';}
				.one{line-height: 15px;font-weight: bold;font-size: 16px;}
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				footer {
				  font-size: 9px;
				  color: black !important;
				 text-align:center;
				}
				
				@page {
				  size: A4;
				  margin: 11mm 17mm 17mm 17mm;				
					
				}
				
				@media print {
				  footer {
				    position: fixed;
				    bottom: 0;
				  	text-align:center; 
				  	padding-left:16%; 
				  	margin-bottom: -12px;
				  }				
				  html, body {
				    width: 210mm;
				    height: 297mm;
				  }
				}
				@page {
				       @bottom-left {
				            content: counter(page) "/" counter(pages);
				        }
				     }
				@media print {
				    footer {page-break-after: always;}
				}
			</style>	
			
			<tr>
			    <td colspan="10">
			    	&nbsp;
			    </td>
			</tr>		
			<tr height="80px">
				<td colspan="6" width="60%" valign="top">
					<table width="100%" style=" ;font-size: 16px;border: 1px solid #000;">
						<tr>
							<td width="110px;">&nbsp;ឈ្មោះអតិថិជន</td>
							<td width="1px"> :&nbsp;</td>
							<td style="padding-top:5px;">
								<label id="lbl_customer" class="one" style="font-size: 14px;"><?php echo $rs['customer_name']?></label>
							</td>
						</tr>
						<tr>
							<td>&nbsp;ទូរសព្ទ</td>
							<td colspan="1"> :&nbsp;</td>
							<td><label id="lbl_phone" class="one"><?php echo $rs['contact_phone']?></label></td>
						</tr>
						<tr>
							<td>&nbsp;អាសយដ្ឋាន </td>
							<td> :&nbsp;</td>
							<td><label id="lbl_address" class="one"><?php echo $rs['address']?></label></td>
						</tr>
					</table>
				</td>
				<td colspan="4" valign="top">
					<table width="100%" style="margin-left:5px;font-size: 16px;border: 1px solid #000;white-space: nowrap;">
						<tr>
							<td width="95px;">&nbsp;លេខបង្កាន់ដៃ</td>
							<td width="1px" style=""> :&nbsp;</td>
							<td style="font-weight: bold;">
								<label id="lb_invoice" >
									<strong><?php echo $rs['receipt_no'];?></strong>
								</label>
							</td>
						</tr>
						<tr>
							<td>&nbsp;ថ្ងៃបង់ប្រាក់</td>
							<td> :&nbsp;</td>
							<td><label class="one"><?php echo date("d-M-Y",strtotime($rs['receipt_date']));?></label></td>
						</tr>
						<tr>
							<td>&nbsp;អ្នកលក់</td>
							<td colspan="1"> :&nbsp;</td>
							<td>
								<label class="one"><?php echo $rs['user_name']?></label>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td colspan="10">
					&nbsp;
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class="defaulheight" width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:14px;white-space:nowrap;margin-top:-5px;line-height: 14px;">
						<tr>
							<td colspan="6" valign="top">
								<table class="tablesorter" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:14px;font-family:Khmer OS Battambang !important;  " id="table">
									<thead>
										<tr class="hearder_table" style="font-size:15px;font-family:khmer os battambang;text-align:center;background:#b0bdfd !important;font-weight:bold;">
											<td style="border:1px solid #000; color:#000;">លរ</td>
											<td style="border:1px solid #000;"><strong style="color:#000;">ពណ៌នា</strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">ប្រាក់សរុប</strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">ប្រាក់បានបង់</strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">ប្រាក់ជំពាក់</strong></td>
										</tr>
									</thead>
									<tbody>
										<?php 
										$index=1;
										$all_total=0;
										$all_paid = 0;
										$all_balance = 0;
										if(!empty($this->rs)){ ?>
										<tr style=" font-size:15px !important; text-align:center;font-weight:bold;">
											<td style="border:1px solid #000;"><?php echo $index;?></td>
											<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;<?php echo "បង់លើ វិក្កយបត្រលេខ  # ".$this->rs['invoice'];?> </strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($this->rs['total'],3);?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($this->rs['paid'],3);?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($this->rs['balance'],3);?></strong></td>
										</tr>
										<?php }
										for($index;$index<=4;$index++){
										?>
										<tr style=" font-size:15px !important; text-align:center;font-weight:bold;height: 30px;">
											<td style="border:1px solid #000;"><?php echo $index+1;?></td>
											<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;</strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
										</tr>
										<?php }?>
										<tr style=" font-size:15px; text-align:right;font-weight:bold;height: 30px;">
											<td style="border:1px solid #fff;border-right:1px solid #000" colspan="2"></td>
											<td style="border:1px solid #000;" colspan="2"><strong style=" color:#000;">ប្រាក់សរុប</strong>&nbsp;</td>
											<td style="border:1px solid #000;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($this->rs['total'],3)?></strong>&nbsp;</td>
										</tr>
										<tr style=" font-size:15px; text-align:right;font-weight:bold;height: 30px;">
											<td style="border:1px solid #fff;border-right:1px solid #000" colspan="2"></td>
											<td style="border:1px solid #000;" colspan="2"><strong style=" color:#000;">ប្រាក់បានបង់</strong>&nbsp;</td>
											<td style="border:1px solid #000;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($this->rs['paid'],3)?></strong>&nbsp;</td>
										</tr>
										<tr style=" font-size:15px; text-align:right;font-weight:bold;">
											<td style="border:1px solid #fff;border-right:1px solid #000" colspan="2"></td>
											<td style="border:1px solid #000;" colspan="2"><strong style="color:#000;">នៅខ្វះ&nbsp;</strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($this->rs['balance'],3)?></strong>&nbsp;</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="6">
								&nbsp;
							</td>
						</tr>
						<tr>
							<td colspan="6">
								<table border="0" width="100%" style="font-size:15px;font-weight: bold;">
									<tr>
										<td width="30%" align="center">អតិថិជន</td>
										<td width="40%"></td>
										<td width="30%" align="center">អ្នកទទួល</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
					<footer style="margin-top: 20%;">
						 <p><?php echo $tr->translate("FOOTER_BUNA");?></p>						
					</footer>				
				</td>
			</tr>
		</tbody>	
	</table>
</div>
    <div style="text-align: center;margin: 0 auto;clear:both;"> 
    <lable class="col-md-4" style=""></lable>
    <div class="col-md-2">
		<a href="<?php echo $this->baseUrl();?>/sales/payment/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a>
	</div>
    <lable class="col-md-2" style="">
    	<button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i>បោះ ពុម្ភ </button>
	</lable>
	<lable class="col-md-4" style=""></lable>
	</div>
</center>
<script>
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	//document.getElementById("office_receipt").submit();
}
</script>
   