<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
?>						 
<title>ដៃគូសេវាកម្មខាងក្រៅ</title>
<body>
	<form class="form-horizontal" id="frm" method="post" action="" autocomplete="off">				
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i><strong>ដៃគូសេវាកម្មខាងក្រៅ</strong>
				</div>
				<div class="tools">
					<label><a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a></label>
				</div>
			</div>
			<div class="portlet-body">
				<div class="tabbable-custom ">
					<div class="portlet-body form">
						<div class="form-body">
							<div class="row">
								<div class="col-md-3">
								</div>
								<div class="col-md-6" style="text-align: left !important;border:1px solid #ccc;">
										<h3 style="border-bottom: 1px solid #ccc;" class="center">ដៃគូសេវាកម្មខាងក្រៅ</h3>
									<div class="form-group" >
										<label class="col-md-4 control-label">
											<strong>ឈ្មោះដៃគូ*</strong>
										</label>
										<div class="col-md-8">
											<input type="text" id="partner_name" name="partner_name" class="validate[required] form-control" />	
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											ភេទ
										</label>
										<div class="col-md-8">
											<select name="gender" id="gender" class="form-control">
										    <option value="1" label="Active">ប្រុស</option>
										    <option value="2" label="Deactive">ស្រី</option>
										</select>	
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											លេខទូរស័ព្ទ
										</label>
										<div class="col-md-8">
											<input type="text" id="tel" name="tel"  class="form-control" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											អាស័យដ្ឋាន
										</label>
										<div class="col-md-8">
											<input type="text" id="addresss" name="addresss"  class="form-control" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											សេវាកម្មផ្តល់អោយ
										</label>
										<div class="col-md-8">
											<select  name="service_cate" id="service_cate"  class="form-control select2me" value="1">
												<?php if(!empty($this->rsservice)){foreach ($this->rsservice as $rs){?>
													<option value="<?php echo $rs["id"];?>"><?php echo $rs["item_name"].' - '.$rs["barcode"];?></option>
												<?php }}?>
											</select>
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											តម្លៃជួល
										</label>
										<div class="col-md-8">
											<input type="text" id="service_fee" name="service_fee" class="validate[required,custom[number]] form-control" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											ពណ៍នា
										</label>
										<div class="col-md-8">
											<input type="text" id="description" name="description"  class="form-control" />
										</div>
									</div>
								</div>
								<div class="col-md-3" style="text-align: left !important;">
								</div>
							</div>
							<div class="form-group">
								<br />
								<div class="col-md-3"></div>
								<div class="col-md-3">
									<a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" class="btn red btn-block btn-lg"><i class="icon-refresh icon-white"></i> ត្រឡប់ក្រោយ</button></a>
								</div>
								<div class="col-md-3">
									<div class="input-icon right">
										<button type="submit" name="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> រក្សាទុក</button>
									</div>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>	
</body>
</html>