<?php 
	$url_new = $this->url(array('module'=>'rsvacl','controller'=>'branch','action'=>'add',));
	$url_cancel = $this->url(array('module'=>'rsvacl','controller'=>'branch','action'=>'index',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("បន្ថែមសាខា");?></title>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("បន្ថែមសាខា");?>
			</div>
			<div class="tools">
				<a href="<?php echo $url_cancel;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="<?php echo $url_new;?>" enctype="multipart/form-data"  >
				<div class="form-body">
					<div class="form-group">
						<div class="col-md-2">
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label class="col-md-4 control-label"><?php echo $tr->translate("BRANCH_NAME");?></label>
								<div class="col-md-8">
									<?php echo $formFilter->getElement('branch_name');?>
								</div>
							</div>
							<div class="form-group">					
								<label class="col-md-4 control-label"><?php echo $tr->translate("PHONE_NUM");?></label>
								<div class="col-md-8">
									<?php echo $formFilter->getElement('contact_num');?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label"><?php echo $tr->translate("EMAIL");?></label>
								<div class="col-md-8">
									<?php echo $formFilter->getElement('email');?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-4 control-label"><?php echo $tr->translate("អាស័យដ្ឋាន");?></label>
								<div class="col-md-8">
									<?php echo $formFilter->getElement('address');?>
								</div>
							</div>
							<div class="form-group">	
								<label class="col-md-4 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-8">
									<?php echo $formFilter->getElement('remark');?>
								</div>
							</div>
							<br>
							<br>
							<div class="form-group">
								<div class="col-md-6">
								</div>
								<div class="col-md-4">
									<button type="submit" name="save_close" id="save_close" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("រក្សាទុក")?> </button>
								</div>
								<div class="col-md-2">
								</div>
							</div>
						</div>		
						<div class="col-md-4">
						</div>	
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
