<?php 					
	$url_new = $this->url(array('module'=>'sales','controller'=>'index','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = $this->baseUrl();
	$url_back = $this->url(array('module'=>'sales','controller'=>'index','action'=>'index',));
	
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
?>
<style>
table.calculate td,table.calculate th{padding:0px 3px !important; line-height: 20px; }
.dijitTextBox, .dijitValidationTextBox, .dijitInputField, .dijitInputContainer, .dijitInputInner, dijitReset, .dijitRight, .dijitButtonNode, .dijitArrowButton, .dijitDownArrowButton, .dijitArrowButtonContainer {
  height: 30px;
}
.dijitValidationTextBoxError input.dijitValidationInner, .dijitSelect input, .dijitTextBox input.dijitArrowButtonInner {
	line-height:38px;
}
.fullside{ width:100%; height: 35px;}
.fullblog{ width:100%; height: 28px;font-size: 15px !important;}
td{padding: 1px !important;}
.aligncenter{text-align: center;background:#4b8df8;color:#ececec;
white-space: nowrap;font-size: 14px;line-height:33px;}
.hover:hover{background: #eee;}
.full_width{width:100%;}
</style>
<title>បន្ថែមការលក់</title>
<script src="<?php echo $base_url;?>/js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>/js/dojo-1.6.1/dijit/themes/soria/soria.css"/>
<meta charset="utf-8" />
<form class="form-horizontal" id="frm" method="post" action="" enctype="multipart/form-data" autocomplete="off" >	
<script type="dojo/method" event="onSubmit">   
   if(this.validate()) {
		customer_id=$("#customer_id").val();
		if(customer_id=='' || customer_id==0){
			alert("សូមបញ្ចុលទឹកប្រាក់ដែលបានបង់");
			return false;	
		}
		alert("do");
		return false;
   }else {
		return false;
   }
</script>
<div class="portlet box blue">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-gift"></i><strong>បន្ថែមការលក់</strong>
		</div>
		<div class="tools">
			<label><a href="<?php echo $this->url(array('module'=>"sales",'controller'=>"index",'action'=>'index'),null,true); ?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a></label>
		</div>
	</div>
	<div class="portlet-body">
		<div class="tabbable-custom">
			<div class="portlet-body form">
				<div class="form-body">
					<div class="row">
						<div class="col-md-12">
							<ul class="nav nav-tabs ">
								<li class="active">
									<a href="#tab_1" data-toggle="tab">
									<strong><i class="fa fa-money" aria-hidden="true"></i> ការលក់</strong></a>
								</li>
								<li>
									<a href="#tab_2" data-toggle="tab"><strong><i class="fa fa-users" aria-hidden="true"></i> ការជួលដៃគូខាងក្រៅ</strong></a>
								</li>
								
							</ul>
						</div>
						<div class="tab-content">
							<div class="tab-pane active" id="tab_1">
								<div class="row">
									<div class="col-md-4" style="text-align: left !important;">
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												<strong>ឈ្មោះអតិថិជន</strong>
											</label>
											<div class="col-md-8">
												<select class="form-control select2me" id="customer_id" name="customer_id" onChange="getPopupCustomer();">
													<option value="">ជ្រើសរើសអតិថិជន</option>
													<option value="-1">បន្ថែមអតិថិជន</option>
													<?php if(!empty($this->rscustomer)){foreach($this->rscustomer as $rs){?>
														<option value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
													<?php }}?>
												</select>
											</div>
										</div>
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												<strong>ជ្រើសរើសសព</strong>
											</label>
											<div class="col-md-8">
												<select class="form-control select2me" id="program_id" name="program_id">
													<option value="0">ជ្រើសរើសសព-កម្មវិធីបុណ្យ</option>
													<?php if(!empty($this->diepeople)){foreach($this->diepeople as $rs){?>
														<option value="<?php echo $rs['id'];?>"><?php echo $rs['dead_name'].'-'.$rs['dead_name_chinese'].'-';echo !empty($rs['dead_dob'])?date("d-m-Y",strtotime($rs['dead_dob'])):"";?></option>
													<?php }}?>
												</select>
											</div>
										</div>
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												សម្គាល់
											</label>
											<div class="col-md-8">
												<textarea name="note" id="note" class="form-control"></textarea>
											</div>
										</div>
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												ថ្ងៃគិតប្រាក់
											</label>
											<div class="col-md-8">
												<div class="input-icon right">
													<i class="fa fa-calendar"></i>
													<input type="text" class="form-control date-picker" name="date_clearpayment" id="date_clearpayment" value="<?php echo date("d-m-Y")?>" data-date-format="dd-mm-yyyy" />
												</div>
											</div>
										</div>
									</div>
									<!-- end blog1 -->
									<div class="col-md-4" style="text-align: left !important;">
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												លេខវិក័យបត្រ
											</label>
											<div class="col-md-8">
												<input type="text" class="form-control" readOnly value="<?php echo $this->invoice?>"/>
											</div>
										</div>
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												ថ្ងៃលក់
											</label>
											<div class="col-md-8">
												<div class="input-icon right">
													<i class="fa fa-calendar"></i>
													<input type="text" class="form-control date-picker" name="sale_date" id="sale_date" value="<?php echo date("d-m-Y")?>" data-date-format="dd-mm-yyyy" />
												</div>
											</div>
										</div>
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												<strong>អ្នកណែនាំ</strong>
											</label>
											<div class="col-md-8">
												<select class="form-control select2me" id="saleagent_id" name="saleagent_id">
													<option value="0">ជ្រើសរើសអ្នកណែនាំ</option>
													<?php if(!empty($this->saleagent)){foreach($this->saleagent as $rs){?>
														<option value="<?php echo $rs['id'];?>"><?php echo $rs['name'];?></option>
													<?php }}?>
													<option value="-1">បន្ថែមថ្មី</option>
												</select>
											</div>
										</div>
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												កំរៃជើងសា
											</label>
											<div class="col-md-8">
												<input type="text" class="form-control validate[required,custom[number]]" name="comission" id="comission" value="0" />
											</div>
										</div>
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												អ្នកទទួលប្រាក់
											</label>
											<div class="col-md-8">
												<input type="text" class="form-control" name="receiver_name" id="receiver_name" />
											</div>
										</div>
									</div>
									<div class="col-md-4" style="text-align: left !important;">
										<div class="form-group" style="">
											<label class="col-md-4 control-label">
												សម្គាល់ផ្សេងៗ
											</label>
											<div class="col-md-7">
												<textarea name="other_note" id="other_note" class="form-control" rows="5"></textarea>
											</div>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="form-group">
										<div class="col-md-2" style="text-align: left !important;">
										</div>
										<div class="col-md-6" style="text-align: left !important;">
											  <input id="product_id" />
											  <input type="hidden" name="identity" id="identity" />
											  <input type="hidden" name="identity_partner" id="identity_partner" />
											  <input type="hidden" name="branch_id" id="branch_id" value="1" />
											  <input type="hidden" name="invoice" id="invoice" value="<?php echo $this->invoice;?>" /> 
										</div>
										<div class="col-md-2" style="text-align: left !important;">
											<button type="button" onclick="popupProduct();" class="btn red delete col-md-12">
												<i class="fa fa-plus"></i><span>&nbsp;&nbsp;បន្ថែមមុខទំនិញថ្មី</span>
											</button>
										</div>
										<div class="col-md-1">
											<button type="button" class="btn red delete col-md-12" onclick="getRefreshProduct();" >
												<i class="fa fa-refresh"></i>Refresh
											</button>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<table id="table_row" border="1px" style="border-collapse: collapse; border:1px solid #ccc;width:100%;">
											<thead>
												<tr id="head-title" class="table table-bordered" align="right" style="border:1px solid #4c6184 !important;">
													<th class="aligncenter">#</th>
													<th class="aligncenter">មុខទំនិញ/សេវាកម្ម</th>
													<th class="aligncenter">ស្តុក</th>
													<th class="aligncenter">បរិ.ដុំ</th>
													<th class="aligncenter">បរិ.រាយ</th>
													<th class="aligncenter">បរិមាណសរុប</th>
													<th class="aligncenter">តម្លៃលក់</th>
													<th class="aligncenter">សរុប</th>
													<th class="aligncenter">លុប</th>
												</tr>
												<tr>
													<td colspan="10" id="lbl_noproduct" align="center">មិនមាន ទំនិញ ក្នុងកន្រ្តក</td>
												</tr>
											</thead>
										</table>
									</div>
								</div>
								<div class="col-md-4">
								</div>
								<div class="col-md-4">
								</div>
								<div class="col-md-4" style="text-align: left !important;font-weight: bold;">
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
										</label>
										<div class="col-md-8">
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											<strong style="font-size: 16px;">តម្លៃសរុប</strong>
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" dojoType="dijit.form.NumberTextBox"  name="sub_total" id="sub_total" readOnly />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											បានបង់ពីមុនសុរប
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" dojoType="dijit.form.NumberTextBox" name="paid_before" id="paid_before" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											<strong style="font-size: 16px;color: red;">បានបង់សរុប</strong>
										</label>
										<div class="col-md-8">
											<input style="font-size: 16px;" type="text" class="form-control" dojoType="dijit.form.NumberTextBox" name="paid" id="paid" onkeyup="calCualtepaid();" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											<strong>នៅខ្វះ</strong>
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" dojoType="dijit.form.NumberTextBox" name="balance" id="balance" readOnly />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											ប្រាក់អាប់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" dojoType="dijit.form.NumberTextBox" name="return_amount" id="return_amount" readOnly />
										</div>
									</div>
								</div>
								<div class="form-group">
									<div class="col-md-3"></div>
									<div class="col-md-3">
										<a href="<?php echo $this->url(array('module'=>$module,'controller'=>'index','action'=>'index'),null,true); ?>"><button type="button" class="btn red btn-block btn-lg"><i class="icon-refresh icon-white"></i> ត្រឡប់ក្រោយ</button></a>
									</div>
									<div class="col-md-3">
										<div class="input-icon right">
											<button type="submit" id="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> រក្សាទុក</button>
										</div>
									</div>
									<div class="col-md-3"></div>
								</div>
							
						</div>	
						<div class="tab-pane" id="tab_2">
							<div class="row">
								<div class="form-group">
									<div class="col-md-2" style="text-align: left !important;">
									</div>
									<div class="col-md-6" style="text-align: left !important;">
										  <input id="service_id" />
									</div>
									<div class="col-md-2" style="text-align: left !important;">
										<button type="button" name="calcel" class="btn blue col-md-12"><i class="fa fa-search"></i>ស្វែងរកមុខទំនិញ</button>
									</div>
									<div class="col-md-2">
									</div>
								</div>
							</div>
							
							<div class="row">
								<div class="col-md-12">
									<table id="table_row_partner" border="1px" style="border-collapse: collapse; border:1px solid #ccc;width:100%;">
										<thead>
											<tr id="head-title" class="table table-bordered" align="right" style="border:1px solid #4c6184 !important;">
												<th class="aligncenter">#</th>
												<th class="aligncenter">សេវាកម្ម</th>
												<th class="aligncenter">អ្នកផ្គត់ផ្គង់</th>
												<th class="aligncenter">តម្លៃជួល</th>
												<th class="aligncenter">សម្គាល់</th>
												<th class="aligncenter">លុប</th>
											</tr>
											<tr>
												<td colspan="10" id="lbl_partnerservice" align="center">មិនមាន ទំនិញ ក្នុងកន្រ្តក</td>
											</tr>
										</thead>
									</table>
								</div>
							</div>
							<div class="form-group" style="">
								<label class="col-md-12 control-label">
									&nbsp;
								</label>
							</div>
							<div class="form-group" style="">
								<label class="col-md-6 control-label">
								</label>
								<label class="col-md-2 control-label">
									<strong style="font-size: 16px;">តម្លៃសរុប</strong>
								</label>
								<div class="col-md-4">
									<input type="text" class="form-control" dojoType="dijit.form.NumberTextBox"  name="total_partner_service" id="total_partner_service" readOnly />
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			</div>
		</div>
	</div>
</div>
</form>

<script>
	$('#frm').submit(function() {
		customer_id=$("#customer_id").val();
		if(customer_id=='' || customer_id==0){
			alert("Please select customer name");
			$('#customer_id').select2('open');
			return false;	
		}
		identity =$("#identity").val();
		if(identity=='' || identity==-1){
			alert("Please add product row");
			//$('#product_id').select2('open');
			dijit.byId("product_id").focus();
			return false;
		}
		
		order_date=$("#sale_date").val();
		if(order_date==''){
			alert("Please select date");
			$('#sale_date').select2('open');
			return false;
		}
		
		var r = confirm("សូមត្រួតពិនិត្យទិន្នន័យ អោយបានត្រឹមត្រូវ !\nតើលោកអ្នកពិតជាចង់រក្សាទុកទិន្នន័យនេះមែនឫទេ?");
		if (r == true) {
			return true;
		} else {
		   return false;	    
		}
		
	});
	
	function getPopupCustomer(){
		val = $('#customer_id').val();
		if(val==-1){
			$('#customerpopup').modal('show');
		}
	}
	
	function popupProduct(){
		window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/product/index/add";?>','_blank');
	}
	
	var url_refreshproduct = '<?php echo $this->url(array("module"=>"sales","controller"=>"possale","action"=>"refresh-product"));?>';										
	function getRefreshProduct(){
		loading();
		dojo.xhrPost({
			url:url_refreshproduct,
			handleAs:"json",
			load: function(data) {
				product_store  = getDataStorefromJSON('id','name', data.product);
				dijit.byId('product_id').set('store',product_store); 
				
				service_store  = getDataStorefromJSON('id','name', data.service);
				dijit.byId('service_id').set('store',service_store); 
				
				document.getElementsByClassName("overlay")[0].style.display="none";
			},
			error: function(err) {
				document.getElementsByClassName("overlay")[0].style.display="none";
			}
		});
	}
	
	
	function loading(){
		document.getElementsByClassName("overlay")[0].style.display="block";
	}
	
</script>


<div class="dijitHidden" style="width: 20cm !important; height: 12cm ; padding: 0px; margin: 0px;">
<div id="invoice" data-dojo-type="dijit.Dialog" style="width:24cm;height: 18cm ;" align="center" data-dojo-props="title:'<?php echo $tr->translate("OFFICIAL_RECEIPT");?>'"  >
	<div id="PrintReceipt" style="border:1px dashed #ccc;width:18cm !important; padding: 0px; margin-bottom:30px; ">
	<style>
		.hearder_table{height:25px !important;}
		.defaulheight{line-height: 22px !important;}
		#PrintReceipt{display: table;}
		#pageFooter {
		   display: table-footer-group;
	}
	#pageFooter:after {
	    counter-increment: page;
	    content:"Page " counter(page);
	    left: 0; 
	    top: 100%;
	    white-space: nowrap; 
	    z-index: 20px;
	    -moz-border-radius: 5px; 
	    -moz-box-shadow: 0px 0px 4px #222;  
	    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
	    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
	  }
	</style>
		<table class="print" cellspacing="0"  cellpadding="0" style="width:98%;font-family: 'Khmer OS Battambang' !important; font-size:11px !important; margin-top:0 auto;white-space:nowrap;">
			<tr height="40px;">
			    <td colspan="10"  style="" align="center" valign="top">
					<table width="100%" style="font-size: 10px;margin-bottom: 0px;"   >
						<tr>
							<td width="40%" valign="top" align="center">
								<img style="height:45px" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.jpg'?>"><br />
								<div style="font-size: 10px;font-family:'Khmer MEF2';text-align: center;width:100%;"><?php echo $tr->translate("COMPANY_CUSTOMER"); ?></div>
							</td>
							<td width="20%" align="center" valign="top" style=""><div style="font-size: 14px;font-family:'Khmer MEF2';">វិក្កយបត្រ</div>INVOICE
							</td>
							<td width="40%" valign="top">
								<div style="white-space: nowrap;"><?php echo $tr->translate("ADDRESS_COMPANY"); ?></div>
								លេខទូរសព្ទ<?php echo $tr->translate("TEL_COMPANY"); ?>
							</td>
						</tr>
					</table>
			    </td>
			</tr>
			<style>
			.bold{
				font-weight:bold;
				}
			.tablesorter td{font-family:'khmer os battambang' !important;}
			.one{line-height: 15px;}
			table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			#footer {
			  display: table-footer-group;
			}
			@page {
			       @bottom-left {
			            content: counter(page) "/" counter(pages);
			        }
			     }
			@media print {
			    footer {page-break-after: always;}
			}
			</style>			
			<tr height="80px">
				<td colspan="6" width="60%" valign="top" >
					<table width="100%" style=" ;font-size: 11px;border: 1px solid #000;" >
						<tr>
							<td width="100px;">&nbsp;ឈ្មោះអតិថិជន</td>
							<td width="1px"> :</td>
							<td style="padding-top:5px;">
								<label id="lbl_customer" class="one" style="font-size: 11px;"></label>
							</td>
						</tr>
						<tr >
							<td>&nbsp;ទូរសព្ទ</td>
							<td colspan="1"> :</td>
							<td><label id="lbl_phone" class="one"></label></td>
						</tr>
						<tr >
							<td>&nbsp;អាសយដ្ឋាន </td>
							<td> :</td>
							<td><label id="lbl_address" class="one"></label></td>
						</tr>
					</table>
				</td>
				<td colspan="4" valign="top">
					<table width="100%" style="margin-left:2px;font-size: 11px;border: 1px solid #000;">
						<tr>
							<td width="90px;" style="white-space: nowrap;">&nbsp;លេខវិក្កយបត្រ</td>
							<td width="1px" style="padding-top:5px;">:</td>
							<td><label id="lb_invoice" class="one"><?php echo $this->invoice;?></label></td>
						</tr>
						<tr >
							<td>&nbsp;ថ្ងៃចេញ</td>
							<td colspan="1"> :</td>
							<td></td>
						</tr>
						<tr>
							<td>&nbsp;អ្នកលក់</td>
							<td colspan="1"> :</td>
							<td>
								<div style="font-weight:bold;color:#000; font-size: 11px;font-family:'Khmer OS Battambang';margin-top: -3px;"> 
								<?php 
								   $session_user=new Zend_Session_Namespace('auth');
								   $username = $session_user->fullname;
								   echo $username;
								?>
								</div>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class='defaulheight' width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:-5px;line-height: 11px;">
						<tr>
							<td colspan="6" valign="top">
								<div id="t_amountmoneytype"></div>
							</td>
						</tr>
						<tr>
							<td colspan="6">
								<table border="0" width="100%" style="font-size:12px; white-space:nowrap;line-height:15px;margin-top:3px;border-collapse:collapse;">
									<tr>
										<td colspan="4">
											<table width="100%" border="0" style="white-space:nowrap;border-collapse:collapse;font-size:12px;line-height:16px;">	
												<tr>
													<td width="25%" align="center">អតិថិជន</td>
													<td width="25%" align="center">អ្នកទទួល</td>
													<td width="25%" align="center">អ្នកដឹក</td>
													<td width="25%" align="center">អ្នកចេញទំនិញ</td>
												</tr>	
											</table>	
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		</table>
    </div>
	    <lable class="col-md-4"></lable>
		<lable class="col-md-4">
	         <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn red btn-block btn-lg"><i class="fa fa-print"></i> រក្សាទុកនិងបោះពុម្ភ</button>
		</lable>
		<lable class="col-md-4"></lable>
	</div>
</div>
<?php $form = $this->form_customer; ?>
<div id="customerpopup" class="modal fade" tabindex="-1" data-width="1200">
       <div class="modal-dialog">
		      <div class="modal-content">
		      <div class="modal-header">   
				<div class="row">
				<div class="col-md-12">
					<div class="portlet box blue">
					<div class="portlet-title">
						<div class="caption">
							<i class="icon-home"></i><?php echo $tr->translate("ADD_NEW_CUSTOMER");?>
						</div>
						<div class="caption pull-right">
							<a href="<?php echo $url_new;?>" >
								 <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
							</a>
						</div>
					</div>
					<div class="portlet-body form">
						<form id="frmcustomer" name="frmcustomer" dojoType="dijit.form.Form" autoComplete="off" enctype="application/x-www-form-urlencoded" class="form-horizontal" enctype="multipart/form-data" method="post">
							<div class="form-body">
								<div class="form-group">
									<label class="control-label col-md-3"><?php echo $tr->translate("សាខា");?><span class="required">
										</span>
									</label>
									<div class="col-md-9">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement("branch_id");?>
										</div>
									</div>
									
								</div>
								
								<div class="form-group">
									<label class="control-label col-md-3">
										<?php echo $tr->translate("លេខកូដអតិថិជន");?>
									</label>
									<div class="col-md-9">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('cu_code'); ?>
										</div>
									</div>
								</div>
								
								<div class="form-group">
									<label class="control-label col-md-3"><?php echo $tr->translate("ឈ្មោះអតិថិជន");?><span class="required"></span>
									</label>
									<div class="col-md-9">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('txt_name'); ?>
										</div>
									</div>
								</div>
								
								
								<div class="form-group">
									<label class="control-label col-md-3">
									<?php echo $tr->translate("លេខទំនាក់ទំនង");?><span class="required">
										</span>
									</label>
									<div class="col-md-9">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('txt_phone'); ?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3">
										<?php echo $tr->translate("អាសយដ្ឋាន");?>
									</label>
									<div class="col-md-9">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement("txt_address");?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3">
										<?php echo $tr->translate("អ៊ីម៉ែល");?>
									</label>
									<div class="col-md-9">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('txt_mail'); ?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-md-3">
										<?php echo $tr->translate("សម្គាល់");?>
									</label>
									<div class="col-md-9">
										<div class="input-icon right">
											<i class="fa"></i>
											<?php echo $form->getElement('remark'); ?>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label  class="col-md-12 center">
										<button type="button" id="save_customer" name="btnsavenew" onclick="addNewCustomer();" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("រក្សាទុក")?> </button>
									</label>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
          </div>
        </div>
    </div>
 </div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>			
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>

dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.form.TextBox");
dojo.require('dijit.form.FilteringSelect');
dojo.require("dijit.form.NumberTextBox");  
dojo.require('dijit.form.Button');
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dijit.form.Form");
dojo.require("dijit.Dialog");
dojo.require("dojo.number");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.Editor");
dojo.require("dijit.form.DateTextBox");

var product_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->rsproduct));?> );
var service_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->rsservice));?> );

require(["dojo/ready"], function(ready){
	 
		new dijit.form.FilteringSelect({
			store: product_store,
			required: false,		           
			name: "product_id",
			id: "product_id",
			searchAttr: "name",
			queryExpr: "*${0}*",
			autoComplete: false,
			placeHolder: "ជ្រើសរើសមុខទំនិញ រឺ សេវាកម្ម ",
			class: 'fullside',
			onChange: function() {
				product_name = dijit.byId("product_id").attr("displayedValue");
				product_id = dijit.byId("product_id").get('value');
				getType(product_id,product_name);
				//addProductRow();
			}
		}, "product_id");

		new dijit.form.FilteringSelect({
			store: service_store,
			required: false,		           
			name: "service_id",
			id: "service_id",
			searchAttr: "name",
			queryExpr: "*${0}*",
			autoComplete: false,
			class: 'fullside',
			onChange: function() {
				addServicePartner(2);
			}
		}, "service_id");

		

});
function checkTime(i) {
	  if (i < 10) {
	    i = "0" + i;
	  }
	  return i;
}

function showReceipt(){
	if(dijit.byId('office_receipt').validate()){
	balance = dijit.byId("balance").get("value");
	customer_id = dijit.byId("customer_id").get("value");
	if(balance> 0 && (customer_id=='' || customer_id==1)){alert("សូមជ្រើសរើស អតិថិជន");dijit.byId("customer_id").focus();return false;}
	var rowId = $('#identity').val();
	if(rowId==''){alert("មិនមាន ទំនិញ ក្នុងកន្រ្តក");dijit.byId("product_id").focus();return false;}

	dojo.byId("lbl_customer").innerHTML=dijit.byId('customer_id').attr("displayedValue");
	 var rowIDArray = rowId.split(',');
	 temp='<table class="collape tablesorter"  align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important;  " id="table">'
		  temp+='<thead><tr class="hearder_table" style="font-family:khmer os battambang;text-align:center;background:#f2f2f2 !important;font-weight:bold;">';
		  temp+='<td style="border:1px solid #000;font-size:12px;">លរ</td>';
	      temp+='<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ឈ្មោះមុខទំនិញ</strong></td>';
		  temp+='<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ចំនួន</strong></td>';
		  temp+='<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">តម្លៃរាយ</strong></td>';
		  temp+='<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">សរុប</strong></td>';
		  temp+='</tr></thead>';
		  var rowId = $('#identity').val();
		  var rowIDArray = rowId.split(',');
		  i=0;		  	
		for(var n = 0; n < rowIDArray.length; n++) {
			  i++;
			  temp+='<tr style=" font-size:12px !important; text-align:center;font-weight:bold;">';
			  temp+='<td style="border:1px solid #000;">'+i+'</td>';
			  temp+='<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;'+$('#product_name'+rowIDArray[n]).val();+'</strong></td>';
			  label = $('#measur_name'+rowIDArray[n]).val();
			  qtydetail = $('#qtydetail_'+rowIDArray[n]).val();
			  if(qtydetail>0){
					unit_label = $('#unit_label'+rowIDArray[n]).val();
					label = label+" "+qtydetail+""+unit_label;
			  }
			  temp+='<td style="border:1px solid #000;"><strong style="color:#000;">'+dijit.byId('qty_'+rowIDArray[n]).get("value")+' '+label;'</strong></td>';
			  temp+='<td style="border:1px solid #000;"><strong style="color:#000;">$ '+dojo.number.format(dijit.byId('price_'+rowIDArray[n]).get("value"),{places:3});+'</strong></td>';
			  temp+='<td style="border:1px solid #000;"><strong style="color:#000;">$ '+dojo.number.format(dijit.byId('sub_total'+rowIDArray[n]).get("value"),{places:3});+'</strong></td>';
		  	  temp+='</tr>';
		}
		
		 for(j=i;i<=13;i++){
			 j++;
	    	 temp+='<tr style="height:25px;;text-align:right;font-weight:bold;">';
			 temp+='<td style="border:1px solid #000;text-align:center;" >'+j+'</td>';
			 temp+='<td style="border:1px solid #000;">&nbsp;</td>';
			 temp+='<td style="border:1px solid #000;" ></td>';
			 temp+='<td style="border:1px solid #000;"></td>';
			 temp+='<td style="border:1px solid #000;" ></td>';
		     temp+='</tr>';
		     }
			 temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
			 temp+='<td style="border:1px solid #fff;border-right:1px solid #000" colspan="3"> '+dojo.number.format(dijit.byId('total_riel').get("value"),{places:0})+' រៀល&nbsp;</td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">សរុប</strong>&nbsp;</td>';
			 temp+='<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;" >$ '+dojo.number.format(dijit.byId('sub_total').get('value')+transport_fee,{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';

		     if(dijit.byId('receive_riel').get('value')!=0){
		     temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
			 temp+='<td style="border:1px solid #fff;border-right:1px solid #000" colspan="3"></td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">ទទួលជារៀល&nbsp;</strong></td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">៛ '+dojo.number.format(dijit.byId('receive_riel').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';
		     }

		     temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
		     temp+='<td style="border:1px solid #fff;border-right:1px solid #000;text-align:left;" colspan="3">- សូមពិនិត្យទំនិញអោយបានត្រឹមត្រូវ</td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">ទទួលជាដុលា&nbsp;</strong></td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">$ '+dojo.number.format(dijit.byId('receive_dollar').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';

		     temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
		     temp+='<td style="border:1px solid #fff;border-right:1px solid #000;text-align:left;" colspan="3">- ទំនិញដែលទិញហើយមិនអាចប្តូរវិញបានទេ</td>';
			 temp+='<td style="border:1px solid #000;><strong style="color:#000;">ប្រាក់ទទួលសរុប&nbsp;</strong></td>';
			 temp+='<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ '+dojo.number.format(dijit.byId('total_paid').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';

		     if(dijit.byId('balance_reil').get('value')!=0){
		     temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
			 temp+='<td style="border:1px solid #fff;border-right:1px solid #000" colspan="3"></td>';
			 temp+='<td style="border:1px solid #000;font-size:12px !important;"><strong style="color:#000;">នៅខ្វះជារៀល&nbsp;</strong></td>';
			 temp+='<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;">៛ '+dojo.number.format(dijit.byId('balance_reil').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';
		     }
		     
		     temp+='<tr style=" font-size:12px; text-align:right;font-weight:bold;">';
			 temp+='<td style="border:1px solid #fff;border-right:1px solid #000" colspan="3"></td>';
			 temp+='<td style="border:1px solid #000;font-size:12px !important;"><strong style="color:#000;">នៅខ្វះជាដុលា&nbsp;</strong></td>';
			 temp+='<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ '+dojo.number.format(dijit.byId('balance').get('value'),{places:3})+'</strong>&nbsp;</td>';
		     temp+='</tr>';
		     
	temp+='</table>';
	dojo.byId('t_amountmoneytype').innerHTML = temp;
	dijit.byId('invoice').show();
	}
}
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_receipt").submit();
}

<?php $url_add_customer =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'add-customer')); ?>
function addNewCustomer(){
	txt_name = $("#txt_name").val();
	if(txt_name==''){
		alert("សូមបញ្ជូលឈ្មោះអតិថិជន!");
		$("#txt_name").focus();
		return false;
	} 
	
	$('#save_customer').attr("disabled", true);
	
	$.ajax({
		url: "<?php echo $url_add_customer;?>",
		type: "post",
		data: $('#frmcustomer').serialize(),
		success: function(data){
			rs = $.parseJSON(data);
			$('#customer_id').append($("<option></option>").attr("value",rs['cus_id']).attr("selected",true).text(txt_name));                       
			$("#customer_id").select2();
			$('#customerpopup').modal('hide');
			//$("#frmcustomer")[0].reset();
		},
		error:function(err){
			alert("faile insert");
		}
	});
	
}
<?php $url_getcustomerinfo =  $this->url(array('module'=>'sales','controller'=>'customer','action'=>'get-customerinfo')); ?>
function getCustomerInfo(){
	customer_id = dijit.byId("customer_id").get("value");
	if(customer_id==-1){
	}else{
		dojo.xhrPost({
		    url: "<?php echo $url_getcustomerinfo;?>",
		    content : { 
		    	'customer_id':customer_id,
			},				    
		   handleAs:"json", 
		   load: function(data) {
			   dojo.byId("lbl_customer").innerHTML=data.cust_name;
			   dojo.byId("lbl_phone").innerHTML=data.contact_phone+'/'+data.phone;
			   dojo.byId("lbl_address").innerHTML=data.address;
		   },		
		    error: function(err) {
				   alert(err);
			}
		});
	}
}
function deleteRecord(index) {	
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).forEach(dojo.destroy);
	netTotal();
}

term = 0;
templateterm='';
tmpterm = '';

col=0;
no=0;
title=0;
temp='';
function addProductRow(product_id,product_name,qty){
	// product_name = dijit.byId("product_id").attr("displayedValue");
	// product_id = dijit.byId("product_id").get('value');
	if(product_name=='' ){return false;}
	col++;no++;
	template='';
	if(title!=1){    
		title=1;
		dojo.byId('lbl_noproduct').innerHTML = '';
	}
	template+='<td style="min-width:20px;text-align:center">'+col+'</td>';
	template+='<td style="min-width:230px;font-size:13px;"><input type="hidden" value="'+product_name+'" id="product_name'+col+'">'+product_name+'<input type="hidden"  value="'+product_id+'" id="product_id'+col+'" name="product_id'+col+'" /></td>';
	template+='<td style="min-width:170px"><lable style="font-size:12px;" id="lblcurrent_qty'+col+'"></lable><input type="hidden" name="qty_perunit'+col+'" id="qty_perunit'+col+'"/><input type="hidden" readonly dojoType="dijit.form.TextBox" id="current_qty'+col+'" name="current_qty'+col+'" /><input type="hidden" dojoType="dijit.form.TextBox" name="measur_name'+col+'" id="measur_name'+col+'"/></td>';
	template+='<td style="min-width:50px"><input type="hidden" dojoType="dijit.form.TextBox" name="unit_label'+col+'" id="unit_label'+col+'"/><input type="text" value="'+qty+'" onkeyup="calCualtePrice('+col+');" name="qty_'+col+'" class="fullblog" id="qty_'+col+'" dojoType="dijit.form.NumberTextBox" placeholder=""/></td>';
	template+='<td style="min-width:50px"><input type="text" onkeyup="calCualtePrice('+col+');" name="qtydetail_'+col+'" class="fullblog" id="qtydetail_'+col+'" dojoType="dijit.form.NumberTextBox" placeholder=""/></td>';
	template+='<td style="min-width:50px"><input required="1" readonly name="qty_sold'+col+'" class="fullblog" id="qty_sold'+col+'" dojoType="dijit.form.NumberTextBox" placeholder=""/></td>';
	template+='<td style="min-width:50px"><input required="1" type="text" tabindex="'+col+'"  onkeyup="calCualtePrice('+col+');" name="price_'+col+'" class="fullblog" id="price_'+col+'" dojoType="dijit.form.NumberTextBox" placeholder=""/><input type="hidden" name="cost_price'+col+'" id="cost_price'+col+'" dojoType="dijit.form.TextBox" /></td>';
	template+='<td style="min-width:60px"><input type="text" name="sub_total'+col+'" class="fullblog" id="sub_total'+col+'" dojoType="dijit.form.NumberTextBox" readonly/></td>';
	template+='<td width="60px"><button style="height:30px" type="button" onclick="deleteRecord('+col+')" name="save_close" class="btn default red">លុប</button></td>';
	tmp='<tr id="row'+col+'" class="hover">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
		 parseContent: true,
	});
	dijit.byId("product_id").attr("value",'');
	dijit.byId("product_id").focus();
	getProductinfo(col,product_id);
}
function calCualtePrice(index){
	main_qty= $("#qty_"+index).val();
	if(main_qty==''){main_qty=0;}
	detail_qty= $("#qtydetail_"+index).val();//ចំនួនរាយ
	if(detail_qty==''){detail_qty=0;}
	qty_perunit= $("#qty_perunit"+index).val();//ចំនួនក្នុង១ឯកកតា
	if(qty_perunit==''){qty_perunit=0;}
	qty_sold = parseFloat(main_qty) + parseFloat(detail_qty/(qty_perunit));
	$('#qty_sold'+index).val(qty_sold);
	
	price = dijit.byId("price_"+index).get("value");
	dijit.byId("qty_sold"+index).attr("value",qty_sold);

	total = (price*qty_sold);
	dijit.byId("sub_total"+index).attr("value",total);
	
	netTotal();
}
function netTotal() {//use
	var netTotal=0;
	var rowId = $('#identity').val();
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			netTotal += Number(dijit.byId('sub_total'+rowIDArray[n]).get('value'));
		}
	}
	dijit.byId("sub_total").attr("value",netTotal);
	dijit.byId('paid').attr('value',netTotal);
	calCualtepaid();
}
function calCualtepaid(){
	paid = dijit.byId('paid').get('value');
	total_received = isNaN(paid)?0:paid;
	
	total_dollar = dijit.byId('sub_total').get('value');
	return_amount = total_received-total_dollar;
	
	dijit.byId('balance').attr('value',0);
	if(return_amount<0){
		return_amount = -return_amount;
		dijit.byId('balance').attr('value',return_amount);
		return_amount=0;
	}
	
	dijit.byId('return_amount').attr('value',return_amount);
	
}
function Fullpaid(){
	total_dollar = dijit.byId('total_dollar').get('value');
	total_dollar = isNaN(total_dollar)?0:total_dollar;
	dijit.byId("receive_dollar").attr("value",total_dollar);
	dijit.byId("total_paid").attr("value",total_dollar);
	dijit.byId("return_amount").attr("value",0);
	dijit.byId("balance").attr("value",0);
	dijit.byId("balance_reil").attr("value",0);
}

var url_getproduct = '<?php echo $this->url(array('module'=>'sales','controller'=>'possale','action'=>'getproduct')); ?>';
function getProductinfo(index,product_id){
	dojo.xhrPost({
	    url: url_getproduct,
	    content : { 
	    	'product_id':product_id,'branch_id':1,
		},				    
	   handleAs:"json", 
	   load: function(data) {
			dijit.byId("current_qty"+index).attr('value',data.qty);
			dijit.byId("price_"+index).attr('value',data.selling_price);
			dijit.byId("cost_price"+index).attr('value',data.price);
			dijit.byId("measur_name"+index).attr('value',data.measue_name);
			dijit.byId("unit_label"+index).attr('value',data.unit_label);

			//dijit.byId("qty_"+index).attr('value',1);
			//dijit.byId("qty_sold"+index).attr('value',1);

			qty = data.qty;
			if(qty==null){qty=0;}
			qtyall_detail = qty*(data.qty_perunit);//eg;qty 1.5 and 1unit =24cans; =>1.5*24 =36cans.
			qty_unitlable = (qtyall_detail % (data.qty_perunit)).toFixed(0);//រកចំនួនរាយ
			//qty_unitlable = qty_unitlable.toFixed(2)
			if(qty_unitlable>0){qty_unitlable=qty_unitlable+""+data.unit_label;}else{qty_unitlable=""; }
			qty=parseInt(qty);
            measure_name = data.measue_name;
			if(data.measue_name==null){measure_name='';}
			
			/*if(qty_unitlable==''){
				qty_unitlable = "";
			}else{
				qty_unitlable = "និង"+qty_unitlable;
			}*/
			
			current_stock = qty+""+measure_name;//data.unit_label;
			if(qty<=0){
				current_stock = '';
			}else if(qty>0 && qty_unitlable!=''){
				current_stock = current_stock + " និង ";
			}
			dojo.byId("lblcurrent_qty"+index).innerHTML=current_stock+""+qty_unitlable;
			$("#qty_perunit"+index).val(data.qty_perunit);
			calCualtePrice(index);
	   },		
	   
	    error: function(err) {
			   alert(err);
		}
	});
}


col1=0;
no1=0;
title1=0;
temp='';
function addServicePartner(from_type){
	
	if(from_type==1){
		service_name = dijit.byId("product_id").attr("displayedValue");
		service_id = dijit.byId("product_id").get('value');
	}else{
		service_name = dijit.byId("service_id").attr("displayedValue");
		service_id = dijit.byId("service_id").get('value');
	}
	if(service_name=='' ){return false;}
	
	col1++;no1++;
	template='';
	if(title1!=1){    
		title1=1;
		dojo.byId('lbl_partnerservice').innerHTML = '';
	}
	template+='<td style="min-width:20px;text-align:center">'+col1+'</td>';
	template+='<td style="min-width:230px;font-size:13px;"><input type="hidden" value="'+service_name+'" id="service_name'+col1+'">'+service_name+'<input type="hidden"  value="'+service_id+'" id="service_id_'+col1+'" name="service_id_'+col1+'" dojoType="dijit.form.TextBox" /></td>';
	
	template+='<td width="20%"><select class="fullside" onchange="getServicePartnerPrice('+col1+');"  dojoType="dijit.form.FilteringSelect" id="partner_'+col1+'" name="partner_'+col1+'" >';
		template+='<option value="">ជ្រើសរើសដៃគូសេវាកម្ម</option>';
		<?php foreach($this->partner as $partner){?>
			template+='<option value="'+<?php echo $partner['id']?>+'"><?php echo $partner['name'];?></option>';
		<?php }?>
	template+='</select></td>';
	
	
	template+='<td style="min-width:60px"><input type="text" id="price_service_'+col1+'" name="price_service_'+col1+'" onkeyup="netTotalPartner();" class="fullside"  dojoType="dijit.form.NumberTextBox" /></td>';
	template+='<td style="min-width:60px"><input type="text" name="note_'+col1+'" class="fullside" id="note_'+col1+'" dojoType="dijit.form.TextBox" /></td>';
	template+='<td width="60px"><button style="height:30px" type="button" onclick="deleteRecordPartner('+col1+')" name="save_close" class="btn default red">លុប</button></td>';
	tmp='<tr id="row_partner_'+col1+'" class="hover">';
	tmp+="</tr>";
	dojo.query("#table_row_partner").append(tmp);

	if($("#identity_partner").val()!="") {
		var identity_partner = $("#identity_partner").val();
		$("#identity_partner").val(identity_partner+','+col1);
	} else {$("#identity_partner").val(col1);}
	dojo.html.set(dojo.byId("row_partner_"+col1),template , {
		 parseContent: true,
	});
	dijit.byId("service_id").attr("value",'');
	dijit.byId("service_id").focus();
}
function deleteRecordPartner(index) {	
	var identity_partner = $('#identity_partner').val();
	var arrays = identity_partner.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity_partner').val(strings);
	dojo.query("#row_partner_"+index).forEach(dojo.destroy);
	netTotalPartner();
}
function netTotalPartner() {//use
	var netTotal=0;
	var rowId = $('#identity_partner').val();
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			netTotal += Number(dijit.byId('price_service_'+rowIDArray[n]).get('value'));
		}
	}
	dijit.byId("total_partner_service").attr("value",netTotal);
}

var url_getservicepartnerprice = '<?php echo $this->url(array('module'=>'sales','controller'=>'possale','action'=>'get-service-partner-price')); ?>';
function getServicePartnerPrice(index){
	partner_id = dijit.byId('partner_'+index).get('value');
	service_id = dijit.byId('service_id_'+index).get('value');
	//alert("partner = "+partner_id+", service = "+service_id);
	if(partner_id>0 && service_id>0){
		dojo.xhrPost({
			url: url_getservicepartnerprice,
			content : {
				'partner_id':partner_id,
				'service_id':service_id,
			},				    
		    handleAs:"json", 
		    load: function(data) {
				dijit.byId("price_service_"+index).attr('value',data);
				netTotalPartner();
		    },		
			error: function(err) {
				   alert(err);
			}
		});
	}
}


var url_gettype = '<?php echo $this->url(array('module'=>'sales','controller'=>'possale','action'=>'get-type')); ?>';
function getType(product_id,product_name){
	if(product_id>0){
		dojo.xhrPost({
			url: url_gettype,
			content : {
				'product_id':product_id,
			},				    
		    handleAs:"json", 
		    load: function(data) {
				if(data.is_package==1){// product package
					getPackageProduct(product_id);
				}else{
					addProductRow(product_id,product_name,"");
					if(data.is_service==1){
						dijit.byId("service_id").attr('value',product_id);
						addServicePartner();
					}
				}
		    },		
			error: function(err) {
				   alert(err);
			}
		});
	}
}

var url_getpackage = '<?php echo $this->url(array('module'=>'sales','controller'=>'possale','action'=>'get-packageproduct')); ?>';
function getPackageProduct(product_id){
	dojo.xhrPost({
		url: url_getpackage,
		content : {
			'product_id':product_id,
		},				    
		handleAs:"json", 
		load: function(data) {
			if(data){
				//alert(data);
				for(i=0;i<data.length;i++){
					//alert(data[i]['name']);
					addProductRow(data[i]['product_id'],data[i]['name'],data[i]['qty']);
				}
			}
		},		
		error: function(err) {
			   alert(err);
		}
	});
}
</script>

<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 150%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .5;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           text-align: center;
           background: #fff url("/psst/trunk/public/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>