<center>
<?php 
	$rs = $this->rs;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title>បញ្ជីទំនិញ</title>
<div id="PrintReceipt" style="border:1px dashed #ccc;width:25cm !important; padding: 1px; margin-bottom:30px; ">

	<table class="print" cellspacing="0" cellpadding="0" style="width:98%;font-family: 'Khmer OS Battambang' !important; font-size:11px !important; margin-top:0 auto;white-space:nowrap;">
		<tbody>
			<tr height="40px;">
			    <td colspan="10" style="" align="center" valign="top">
					<table width="100%" border="0" style="font-size: 14px;margin-bottom: 0px; white-space: nowrap;"   >
						<tr>
							<td width="38%" valign="top">								
							</td>
							<td width="30%" align="center" style="line-height: 37px;">
								<div style="font-size: 32px;font-family:'Khmer OS Muol Light'; color:red;">ចៅ ប៊ុនណា 73</div>
								<div style="font-size: 23px;font-family:'Khmer OS Muol Light'; color:black;">សេវាកម្មបុណ្យសពតាំងពីឆ្នាំ 1982</div>
								<div style="font-size: 23px;font-family:'Khmer OS Muol Light';">បញ្ជីទំនិញ</div>
							</td>
							<td width="28%" valign="top" align="center">
								<img style="height:115px; width:150px; alt="<?php ?>" src="<?php echo $this->baseUrl()?>/images/logosbona.jpg"><br />
								<div style="font-size: 20px;font-family:'Khmer OS Muol Light';text-align: center;width:100%;">Tel: 012/015 737303</div>
							</td>							
						</tr>
					</table>                
			    </td>
			</tr>
			<style>
				.bold{
					font-weight:bold;
					}
				.tablesorter td{font-family:'khmer os battambang' !important;}
				.one{line-height: 15px;font-weight: bold;font-size: 16px;}
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				#footer {
				  display: table-footer-group;
				}
				@page {
					   @bottom-left {
							content: counter(page) "/" counter(pages);
						}
					 }
				@media print {
					footer {page-break-after: always;}
				}
			</style>			
			
			<tr height="80px">
				<td colspan="4"  valign="top">
					<table width="100%" style=" font-size: 16px;border: 1px solid #000;">
						<tbody>
							<tr>
								<td>&nbsp;ទីតាំងបុណ្យ </td>
								<td> :</td>
								<td><label id="lbl_address" class="one">&nbsp;&nbsp;<?php echo $rs['place_bun']?></label></td>
							</tr>
							<tr>
								<td>&nbsp;អាសយដ្ឋាន </td>
								<td> :</td>
								<td><label id="lbl_address" class="one">&nbsp;&nbsp;<?php echo $rs['address']?></label></td>
							</tr>
							<tr>
								<td width="110px;">&nbsp;ឈ្មោះអតិថិជន</td>
								<td width="1px"> :</td>
								<td style="padding-top:5px;">
									<label id="lbl_customer" class="one" ">&nbsp;&nbsp;<?php echo $rs['customer_name']?></label>
								</td>
							</tr>
							<tr>
								<td>&nbsp;ទូរសព្ទ </td>
								<td colspan="1"> :</td>
								<td><label id="lbl_phone" class="one">&nbsp;&nbsp;<?php echo $rs['phone']?></label></td>
							</tr>
							<tr>
								<td>&nbsp;ពេលវេលាចេញ</td>
								<td colspan="1"> :</td>
								<td><label id="lbl_phone" class="one">&nbsp;&nbsp;<?php echo $rs['date_deleivery']?></label></td>
							</tr>
							
						</tbody>
					</table>
				</td>
				<td colspan="6" width="33%" valign="top">
					<table width="100%" style="margin-left:5px;font-size: 16px;border: 1px solid #000;">
						<tbody>
							<tr>
								<td width="90px;" style="white-space: nowrap;">&nbsp;លេខវិក្កយបត្រ</td>
								<td width="1px" style="">:</td>
								<td><label id="lb_invoice" class="one">&nbsp;&nbsp;<?php echo $rs['sale_no']?></label></td>
							</tr>
							<tr>
								<td>&nbsp;ថ្ងៃលក់</td>
								<td colspan="1"> :</td>
								<td><label class="one">&nbsp;&nbsp;<?php echo date("d/m/Y",strtotime($rs['date_sold']));?></label></td>
							</tr>
							<tr>
								<td>&nbsp;អ្នកលក់</td>
								<td colspan="1"> :</td>
								<td>
									<label class="one">&nbsp;&nbsp;<?php echo $rs['user_name']?></label>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			
			<tr>
				<td colspan="10">
					&nbsp;
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class="defaulheight" width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:-5px;line-height: 11px;">
						<tbody>
							<tr>
								<td colspan="6" valign="top">
									<table class="tablesorter" align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important;  " id="table">
										<thead>
											<tr bgcolor="#b0bdfd" class="hearder_table" style="font-size:15px;font-family:khmer os battambang;text-align:center;background:#f2f2f2 !important;font-weight:bold;">
												<td style="border:1px solid #000;">លរ</td>
												<td style="border:1px solid #000;"><strong style="color:#000;">លេខកូតទំនិញ</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">ឈ្មោះ/名称</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">ចំនួន/数量</strong></td>
											</tr>
										</thead>
										<tbody>
											<?php $index=0;
											if(!empty($this->rsdetail)){foreach($this->rsdetail as $key => $item){ $index++;?>
											<tr style=" font-size:15px !important; text-align:center;font-weight:bold;">
												<td style="border:1px solid #000;"><?php echo $key+1;?></td>
												<td style="border:1px solid #000;text-align: left;"><strong style="color:#000;">&nbsp;<?php if($item['package_id']>0){echo "&nbsp;&nbsp;&nbsp; - ";}echo $item['pro_name'];?> </strong></td>
												<td style="border:1px solid #000;text-align: left;"><strong style="color:#000;">&nbsp;<?php if($item['package_id']>0){echo "&nbsp;&nbsp;&nbsp; - ";}echo $item['item_code'];?> </strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"><?php echo number_format($item['qty_order'],0);if(/*$item['is_service']==0 && */ $item['is_package']==0){echo " ".$item['measure_name'];}?></strong></td>
											</tr>
											<?php } }
											for($index;$index<15;$index++){
											?>
											<tr style=" font-size:15px !important; text-align:center;font-weight:bold;">
												<td style="border:1px solid #000;"><?php echo $index+1;?></td>
												<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											</tr>
											<?php }?>
										</tbody>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</div>
    <div style="text-align: center;margin: 0 auto;"> 
    	<lable class="col-md-3" style=""></lable>
    	<div class="col-md-2">
			<a href="<?php echo $this->baseUrl();?>/sales/index"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ចាកចេញ</button></a>
		</div>
    	<lable class="col-md-2" style="">
             <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i>បោះ ពុម្ភ </button>
		</lable>
		<lable class="col-md-3" style=""></lable>
	</div>
</center>
<script>
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_receipt").submit();
}
</script>
   