<center>
<?php 
	$rs = $this->rs;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title>វិក្កយបត្រលក់</title>
<div id="PrintReceipt" style="border:1px dashed #ccc;width:25cm !important; padding: 0px; margin-bottom:30px; ">
	<style>
		.hearder_table{height:25px !important;}
		.defaulheight{line-height: 22px !important;}
		#PrintReceipt{display: table;}
		#pageFooter {
		    display: table-footer-group;
		}
		#pageFooter:after {
		    counter-increment: page;
		    content:"Page " counter(page);
		    left: 0; 
		    top: 100%;
		    white-space: nowrap; 
		    z-index: 20px;
		    -moz-border-radius: 5px; 
		    -moz-box-shadow: 0px 0px 4px #222;  
		    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
		    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
		}
	</style>
	<table class="print" cellspacing="0" cellpadding="0" style="width:98%;font-family: 'Khmer OS Battambang' !important; font-size:11px !important; margin-top:0 auto;white-space:nowrap;">
		<tbody>
			<tr height="40px;">
				<td colspan="10" style="" align="center" valign="top">
					<table width="100%" style="font-size: 10px;margin-bottom: 0px;"   >
						<tr>
							<td width="40%" valign="top" align="center">
								<img style="height:65px" alt="<?php ?>" src="<?php echo $this->baseUrl()?>/images/logosbona.jpg"><br />
								<div style="font-size: 12px;font-family:'Khmer MEF2';text-align: center;width:100%;"><?php echo $tr->translate("COMPANY_CUSTOMER"); ?></div>
							</td>
							<td width="20%" align="center" valign="top" style="">
								<div style="font-size: 25px;font-family:'Khmer MEF2';">វិក្កយបត្រ</div>
								<div  style="font-size: 22px;font-family:Times New Roman;font-weight: bold;">INVOICE</div>
							</td>
							<td width="40%" valign="top">
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<style>
				.bold{
					font-weight:bold;
					}
				.tablesorter td{font-family:'khmer os battambang' !important;}
				.one{line-height: 15px;font-weight: bold;font-size: 16px;}
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				#footer {
				  display: table-footer-group;
				}
				@page {
					   @bottom-left {
							content: counter(page) "/" counter(pages);
						}
					 }
				@media print {
					footer {page-break-after: always;}
				}
			</style>			
			
			<tr height="80px">
				<td colspan="6" width="60%" valign="top">
					<table width="100%" style=" ;font-size: 16px;border: 1px solid #000;">
						<tbody>
							<tr>
								<td width="110px;">&nbsp;ឈ្មោះអតិថិជន</td>
								<td width="1px"> :</td>
								<td style="padding-top:5px;">
									<label id="lbl_customer" class="one" ">&nbsp;&nbsp;<?php echo $rs['customer_name']?></label>
								</td>
							</tr>
							<tr>
								<td>&nbsp;ទូរសព្ទ</td>
								<td colspan="1"> :</td>
								<td><label id="lbl_phone" class="one">&nbsp;&nbsp;<?php echo $rs['phone']?></label></td>
							</tr>
							<tr>
								<td>&nbsp;អាសយដ្ឋាន </td>
								<td> :</td>
								<td><label id="lbl_address" class="one">&nbsp;&nbsp;<?php echo $rs['address']?></label></td>
							</tr>
						</tbody>
					</table>
				</td>
				<td colspan="4" valign="top">
					<table width="100%" style="margin-left:5px;font-size: 16px;border: 1px solid #000;">
						<tbody>
							<tr>
								<td width="90px;" style="white-space: nowrap;">&nbsp;លេខវិក្កយបត្រ</td>
								<td width="1px" style="">:</td>
								<td><label id="lb_invoice" class="one">&nbsp;&nbsp;<?php echo $rs['sale_no']?></label></td>
							</tr>
							<tr>
								<td>&nbsp;ថ្ងៃចេញ</td>
								<td colspan="1"> :</td>
								<td><label class="one">&nbsp;&nbsp;<?php echo date("d/m/Y",strtotime($rs['date_sold']));?></label></td>
							</tr>
							<tr>
								<td>&nbsp;អ្នកលក់</td>
								<td colspan="1"> :</td>
								<td>
									<label class="one">&nbsp;&nbsp;<?php echo $rs['user_name']?></label>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			
			<tr>
				<td colspan="10">
					&nbsp;
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class="defaulheight" width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:-5px;line-height: 11px;">
						<tbody>
							<tr>
								<td colspan="6" valign="top">
									<table class="tablesorter" align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important;  " id="table">
										<thead>
											<tr class="hearder_table" style="font-size:15px;font-family:khmer os battambang;text-align:center;background:#f2f2f2 !important;font-weight:bold;">
												<td style="border:1px solid #000;">លរ</td>
												<td style="border:1px solid #000;"><strong style="color:#000;">ឈ្មោះមុខទំនិញ</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">លេខកូតទំនិញ</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">ចំនួន</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">តម្លៃរាយ</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">សរុប</strong></td>
											</tr>
										</thead>
										<tbody>
											<?php $index=0;
											if(!empty($this->rsdetail)){foreach($this->rsdetail as $key => $item){ $index++;?>
											<tr style=" font-size:15px !important; text-align:center;font-weight:bold;">
												<td style="border:1px solid #000;"><?php echo $key+1;?></td>
												<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;<?php echo $item['pro_name'];?> </strong></td>
												<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;<?php echo $item['item_code'];?> </strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"><?php echo number_format($item['qty_order'],0);if(/*$item['is_service']==0 && */ $item['is_package']==0){echo " ".$item['measure_name'];}?></strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($item['price'],2);?></strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($item['sub_total'],2);?></strong></td>
											</tr>
											<?php } }
											for($index;$index<15;$index++){
											?>
											<tr style=" font-size:15px !important; text-align:center;font-weight:bold;">
												<td style="border:1px solid #000;"><?php echo $index+1;?></td>
												<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											</tr>
											<?php }?>
											<tr style=" font-size:15px; text-align:right;font-weight:bold;">
												<td style="border:1px solid #fff;border-right:1px solid #000;text-align:left;" colspan="4" valign="bottom" >- សូមពិនិត្យទំនិញអោយបានត្រឹមត្រូវ</td>
												<td style="border:1px solid #000;"><strong style="color:#000;">សរុប&nbsp;</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($rs['all_total'],3)?></strong></td>
											</tr>
											<tr style=" font-size:15px; text-align:right;font-weight:bold;">
												<td style="border:1px solid #fff;border-right:1px solid #000;text-align:left;" colspan="4" valign="bottom">- ទំនិញដែលទិញហើយមិនអាចប្តូរវិញបានទេ</td>
												<td style="border:1px solid #000;"><strong style=" color:#000;">បានបង់&nbsp;</strong></td>
												<td style="border:1px solid #000;"><strong style=" color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($rs['paid'],3)?></strong></td>
											</tr>
											<tr style=" font-size:15px; text-align:right;font-weight:bold;">
												<td style="border:1px solid #fff;border-right:1px solid #000" colspan="4"></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">នៅខ្វះ&nbsp;</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($rs['balance_after'],3)?></strong></td>
											</tr>	
										</tbody>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="6">
									<table border="0" width="100%" style="font-size:15px;font-weight: bold;">
										<tr>
											<td width="30%" align="center">អតិថិជន</td>
											<td width="40%"></td>
											<td width="30%" align="center">អ្នកទទួល</td>
										</tr>	
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
	</table>
</div>
    <div style="text-align: center;margin: 0 auto;"> 
    	<lable class="col-md-3" style=""></lable>
    	<div class="col-md-2">
			<a href="<?php echo $this->baseUrl();?>/sales/index"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ចាកចេញ</button></a>
		</div>
    	<lable class="col-md-2" style="">
             <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i>បោះ ពុម្ភ </button>
		</lable>
		<lable class="col-md-3" style=""></lable>
	</div>
</center>
<script>
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_receipt").submit();
}
</script>
   