<center>
<?php 
	$rs = $this->rs;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title>វិក្កយបត្រលក់</title>
<style>
	#print-footer{display: none !important;}
</style>
<div id="PrintReceipt" style="border:1px dashed #ccc;width:25cm !important; padding: 0px; margin-bottom:30px; width:23cm;margin: 0 auto;min-height: 26cm; ">
	<table class="print" cellspacing="0" cellpadding="0" style="width:99%;font-family: 'Khmer OS Battambang' !important; font-size:11px !important; margin-top: 10px; white-space:nowrap; margin-top: 6px;">
		<tbody>
			<tr height="40px;">
			    <td colspan="10" style="" align="center" valign="top">
					<table width="100%" border="0" style="font-size: 14px;margin-bottom: 0px; white-space: nowrap;"   >
						<tr>
							<td width="35%" valign="top">
								
							</td>
							<td width="30%" align="center" valign="top" style="line-height: 35px;">
								<div style="font-size: 32px;font-family:'Khmer OS Muol Light'; color:red !important;"><?php echo $tr->translate("JAV_BONA");?></div>
								<div style="font-size: 23px;font-family:'Khmer OS Muol Light'; color:black;"><?php echo $tr->translate("NAME_COMPANT_BUNA");?></div>
								<div style="font-size: 23px;font-family:'Khmer OS Muol Light';font-weight: bold; color:red !important;"><?php echo $tr->translate("NAME_CHINESE");?></div>
								<div style="font-size: 23px;font-family:'Khmer OS Muol Light';font-weight: bold; color:blue !important;"><i class="fa fa-facebook-square" style="font-size: 32px;"></i> <?php echo $tr->translate("JAV_NOA_FUNERAL");?></div>
								<div style="font-size: 20px;font-family:Khmer OS Muol Light;color: red !important;"><?php echo $tr->translate("បង្កាន់ដៃបង់ថ្លៃជួលសេវាកម្ម");?></div>
							</td>
							<td width="35%" valign="top" align="center">
								<img style="height:115px; width:150px; alt="<?php ?>" src="<?php echo $this->baseUrl()?>/images/logosbona.jpg"><br />
								<div style="font-size: 19px;font-family:'Khmer OS Muol Light';text-align: center;width:90%;"><?php echo $tr->translate("PHONE_BUNA");?></div>
								
							</td>
							
						</tr>
					</table>                
			    </td>
			</tr>
			<style>
				.bold{
					font-weight:bold;
					}
				.tablesorter td{font-family:'khmer os battambang' !important;}
				.one{line-height: 15px;font-weight: bold;font-size: 16px;}
				
				table { page-break-before: avoid; }
				tr{ page-break-inside:avoid; page-break-after:avoid;}
				
				#print-footer {
					display: block;
					position: fixed;
					bottom:0;
					left:15%;
				}
				
			</style>						
			<tr height="80px">
				<td colspan="6" width="65%" valign="top">
					<table width="100%" height="100%" style=" ;font-size: 17px;border: 1px solid #000;margin-top:10px;">
						<tbody>
							<tr>
								<td width="110px">&nbsp;ឈ្មោះដៃគូរ</td>
								<td width="1px"> :</td>
								<td style="padding-top:5px;">
									<label id="lbl_address" class="one">&nbsp;&nbsp;<?php echo $rs['partner_name']?></label>
								</td>
							</tr>
							<tr>
								<td>&nbsp;ទូរស័ព្ទ </td>
								<td> :</td>
								<td><label id="lbl_address" class="one">&nbsp;&nbsp;<?php echo $rs['phone']?></label></td>
							</tr>
							
							<tr>
								<td>&nbsp;អាស័យដ្ឋាន </td>
								<td> :</td>
								<td><label id="lbl_address" class="one">&nbsp;&nbsp;<?php echo $rs['address']?></label></td>
							</tr>
						</tbody>
					</table>
				</td>
				<td colspan="4" width="35%" valign="top">
					<table width="100%" style="margin-left:5px;font-size: 17px;border: 1px solid #000;margin-top:10px;">
						<tbody>
							<tr>
								<td width="90px;" style="white-space: nowrap;">&nbsp;តម្លៃសរុប</td>
								<td width="1px" style="">:</td>
								<td><label id="lb_invoice" class="one">&nbsp;&nbsp;<?php echo "$ ".number_format($rs['total_payment'],2);?></label></td>
							</tr>
							<tr>
								<td>&nbsp;ថ្ងៃបង់</td>
								<td colspan="1"> :</td>
								<td><label class="one">&nbsp;&nbsp;<?php echo date("d/m/Y",strtotime($rs['date_payment']));?></label></td>
							</tr>
							<tr>
								<td>&nbsp;អ្នកលក់</td>
								<td colspan="1"> :</td>
								<td>
									<label class="one">&nbsp;&nbsp;<?php echo $rs['user_name']?></label>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
			<tr>
				<td colspan="10">
					&nbsp;
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class="defaulheight" width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:0px;line-height: 11px;">
						<tbody>
							<tr>
								<td colspan="6" valign="top">
									<table class="tablesorter" align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:11px;font-family:Khmer OS Battambang !important;  " id="table">
										<thead>
											<tr class="hearder_table" style="font-size:15px;font-family:khmer os battambang;text-align:center; background:#b0bdfd !important;font-weight:bold;">
												<td style="border:1px solid #000;">លរ</td>
												<td style="border:1px solid #000;"><strong style="color:#000;">ទីតាំងបុណ្យ</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">លេខវិក័យបត្រ</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">សេវាកម្ម</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">តម្លៃ</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;">សម្គាល់</strong></td>
											</tr>
										</thead>
										<tbody>
											<?php 
												$db = new Sales_Model_DbTable_DbPartnerServicepayment();
												$index=0;
												$array = $rs['array_sale_partner_id'];
												$ids=explode(',',$array);
												
											if(!empty($ids)){foreach($ids as $key => $item){ $index++;
												$result = $db->getSalePartnerServiceById($item);
												
											?>
											<tr style=" font-size:15px !important; text-align:center;">
												<td style="border:1px solid #000;"><?php echo $index;?></td>
												<td style="border:1px solid #000;text-align:left;">&nbsp;<?php echo $result['place_bun']?></td>
												<td style="border:1px solid #000;"><?php echo $result['sale_no']?></td>
												<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;<?php echo $result['service_name']?></strong></td>
												<td style="border:1px solid #000;"><?php echo "$ ".number_format($result['price'],2)?></td>
												<td style="border:1px solid #000;text-align:left;">&nbsp;<?php echo $result['note']?></td>
											</tr>
											<?php } } 
											for($index;$index<15;$index++){
											?>
											
											<tr style=" font-size:15px !important; text-align:center;font-weight:bold;">
												<td style="border:1px solid #000;"><?php echo $index+1;?></td>
												<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;</strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
												<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											</tr>
											
											<?php }?>
										</tbody>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="6">
									&nbsp;
								</td>
							</tr>
							
							<tr>
								<td colspan="6">
									<table border="0" width="100%" style="font-size:15px;font-weight: bold;">
										<tr>
											<td width="30%" align="center">អតិថិជន</td>
											<td width="40%"></td>
											<td width="30%" align="center">អ្នកទទួល</td>
										</tr>	
									</table>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
			</tr>
		</tbody>
		<footer>
			<tr height="20px">
				<td colspan="10">
					<div id="print-footer" style="font-size:15px; color:blue !important;"><?php echo $tr->translate("FOOTER_BUNA");?></div>
				</td>
			</tr>
		</footer>
	</table>	
</div>

    <div style="padding-left:16%; margin: 0 auto;"> 
    	<lable class="col-md-3" style=""></lable>
    	<div class="col-md-2">
			<a href="<?php echo $this->baseUrl();?>/sales/index"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ចាកចេញ</button></a>
		</div>
    	<lable class="col-md-2" style="">
             <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i>បោះ ពុម្ភ </button>
		</lable>
		<lable class="col-md-3" style=""></lable>
	</div>
</center>
<script>
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_receipt").submit();
}
</script>
   