<title>បង្កាន់ដៃបង់ប្រាក់</title>

<center>
<?php 
	$rs = $this->rs;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<div id="PrintReceipt" style="border:1px dashed #ccc;width:22cm !important; padding: 0px; margin-bottom:30px; ">
			<style>
		.hearder_table{height:25px !important;}
		.defaulheight{line-height: 22px !important;}
		#PrintReceipt{display: table;}
		#pageFooter {
		    display: table-footer-group;
		}
#pageFooter:after {
    counter-increment: page;
    content:"Page " counter(page);
    left: 0; 
    top: 100%;
    white-space: nowrap; 
    z-index: 20px;
    -moz-border-radius: 5px; 
    -moz-box-shadow: 0px 0px 4px #222;  
    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
  }
	</style>
	<?php for($i=0;$i<=1;$i++){?>
		<table class="print" cellspacing="0" cellpadding="0" style="width:98%;font-family: 'Khmer OS Battambang' !important; font-size:14px !important; margin-top:0 auto;white-space:nowrap;">
			<tbody><tr height="40px;">
			    <td colspan="10" style="" align="center" valign="top">
					<table width="100%" style="font-size: 14px;margin-bottom: 0px;"   >
						<tr>
							<td width="40%" valign="top" align="center">
								<img style="height:45px" alt="<?php ?>" src="<?php echo $this->baseUrl().'/images/logo.jpg'?>"><br />
								<div style="font-size: 14px;font-family:'Khmer MEF2';text-align: center;width:100%;"><?php echo $tr->translate("COMPANY_CUSTOMER"); ?></div>
							</td>
							<td width="20%" align="center" valign="top" style="">
								<div style="font-size: 16px;font-family:'Khmer MEF2';">បង្កាន់ដៃបង់ប្រាក់</div>
								<div><strong>OFFICIAL RECEIPT</strong></div>
							</td>
							<td width="40%" valign="top">
								
							</td>
						</tr>
					</table>                
			    </td>
			</tr>
			<style>
			.bold{
				font-weight:bold;
				}
			.tablesorter td{font-family:'khmer os battambang' !important;}
			.one{line-height: 15px;}
			table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			#footer {
			  display: table-footer-group;
			}
			@page {
			       @bottom-left {
			            content: counter(page) "/" counter(pages);
			        }
			     }
			@media print {
			    footer {page-break-after: always;}
			}
			</style>			
			<tr height="80px">
				<td colspan="6" width="60%" valign="top">
					<table width="100%" style=" ;font-size: 14px;border: 1px solid #000;">
						<tbody><tr>
							<td width="100px;">&nbsp;ឈ្មោះអតិថិជន</td>
							<td width="1px"> :&nbsp;</td>
							<td style="padding-top:5px;">
								<label id="lbl_customer" class="one" style="font-size: 14px;"><?php echo $rs['customer_name']?></label>
							</td>
						</tr>
						<tr>
							<td>&nbsp;ទូរសព្ទ</td>
							<td colspan="1"> :&nbsp;</td>
							<td><label id="lbl_phone" class="one"><?php echo $rs['contact_phone']?></label></td>
						</tr>
						<tr>
							<td>&nbsp;អាសយដ្ឋាន </td>
							<td> :&nbsp;</td>
							<td><label id="lbl_address" class="one"><?php echo $rs['address']?></label></td>
						</tr>
					</tbody></table>
				</td>
				<td colspan="4" valign="top">
					<table width="100%" style="margin-left:2px;font-size: 14px;font-weight: bold;">
						<tbody>
						<tr style="background: #dedcdc;font-weight: bold;">
							<td width="90px;" style="white-space: nowrap;">&nbsp;លេខបង្កាន់ដៃ</td>
							<td width="1px" style=""> :&nbsp;</td>
							<td style="font-weight: bold;"><label id="lb_invoice" ><strong><?php echo $rs['receipt_no'];?></strong></label></td>
						</tr>
						<tr>
							<td>&nbsp;ថ្ងៃបង់ប្រាក់</td>
							<td colspan="1"> :&nbsp;</td>
							<td><div style="text-align:left;font-size:14px; white-space: nowrap;"><?php echo date("d-M-Y",strtotime($rs['receipt_date']));?></div></td>
						</tr>
						<tr style="background: #dedcdc;">
							<td>&nbsp;អ្នកលក់</td>
							<td colspan="1"> :&nbsp;</td>
							<td>
								<div style="font-weight:bold;color:#000; font-size: 14px;font-family:'Khmer OS Battambang';"><?php echo $rs['user_name']?></div>
							</td>
						</tr>
					</tbody></table>
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class="defaulheight" width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:14px;white-space:nowrap;margin-top:-5px;line-height: 14px;">
						<tbody><tr>
							<td colspan="6" valign="top">
								<div id="t_amountmoneytype">
									<br />
									<table class="collape tablesorter" align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:14px;font-family:Khmer OS Battambang !important;  " id="table">
										<thead>
											<tr class="hearder_table" style="font-family:khmer os battambang;text-align:center;background:#f2f2f2 !important;font-weight:bold;">
												<td style="border:1px solid #000;font-size:14px;">លរ</td>
												<td style="border:1px solid #000;font-size:14px;"><strong style="color:#000;">ពណ៍នា</strong></td>
												<td style="border:1px solid #000;font-size:14px;"><strong style="color:#000;">ប្រាក់សរុប</strong></td>
												<td style="border:1px solid #000;font-size:14px;"><strong style="color:#000;">ប្រាក់បានបង់</strong></td>
												<td style="border:1px solid #000;font-size:14px;"><strong style="color:#000;">ប្រាក់ជំពាក់</strong></td>
											</tr>
										</thead>
										<tbody>
										<?php 
										$index=1;
										$all_total=0;
										$all_paid = 0;
										$all_balance = 0;
										if(!empty($this->rs)){ ?>
										<tr style=" font-size:14px !important; text-align:center;font-weight:bold;">
											<td style="border:1px solid #000;"><?php echo $index;?></td>
											<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;<?php echo "បង់លើ វិក្កយបត្រលេខ  # ".$this->rs['invoice'];?> </strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($this->rs['total'],3);?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($this->rs['paid'],3);?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($this->rs['balance'],3);?></strong></td>
										</tr>
										<?php }
										for($index;$index<=3;$index++){
										?>
										<tr style=" font-size:14px !important; text-align:center;font-weight:bold;height: 30px;">
											<td style="border:1px solid #000;"><?php echo $index+1;?></td>
											<td style="border:1px solid #000;text-align:left;"><strong style="color:#000;">&nbsp;</strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;"></strong></td>
										</tr>
										<?php }?>
										<tr style=" font-size:14px; text-align:right;font-weight:bold;height: 30px;font-size: 14px;">
											<td style="border:1px solid #fff;border-right:1px solid #000" colspan="2"></td>
											<td style="border:1px solid #000;" colspan="2"><strong style=" color:#000;font-size: 14px;">ប្រាក់សរុប</strong>&nbsp;</td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($this->rs['total'],3)?></strong>&nbsp;</td>
										</tr>
										<tr style=" font-size:14px; text-align:right;font-weight:bold;height: 30px;font-size: 14px;">
											<td style="border:1px solid #fff;border-right:1px solid #000" colspan="2"></td>
											<td style="border:1px solid #000;" colspan="2"><strong style=" color:#000;font-size: 14px;">ប្រាក់បានបង់</strong>&nbsp;</td>
											<td style="border:1px solid #000;"><strong style="color:#000;">$ <?php echo number_format($this->rs['paid'],3)?></strong>&nbsp;</td>
										</tr>
										<tr style=" font-size:14px; text-align:right;font-weight:bold;font-size: 14px;">
											<td style="border:1px solid #fff;border-right:1px solid #000" colspan="2"></td>
											<td style="border:1px solid #000;font-size:14px !important;font-size: 14px;" colspan="2"><strong style="color:#000;">នៅខ្វះ&nbsp;</strong></td>
											<td style="border:1px solid #000;font-size:14px !important;"><strong style="color:#000;font-family:arial;font-weight:bold;">$ <?php echo number_format($this->rs['balance'],3)?></strong>&nbsp;</td>
										</tr>
											</tbody>
									</table>
								</div>
							</td>
						</tr>
						<tr>
							<td colspan="6">
								<table border="0" width="100%" style="font-size:14px; white-space:nowrap;line-height:15px;margin-top:3px;margin-bottom:14px;border-collapse:collapse;">
									<tbody>
										<tr>
											<td colspan="4">
												&nbsp;
											</td>
										</tr>
										<tr>
											<td colspan="4">
												<table width="100%" border="0" style="white-space:nowrap;border-collapse:collapse;font-size:14px;line-height:16px;">	
													<tbody><tr>
														<td width="25%" align="center">អ្នកទទួល</td>
														<td width="25%" align="center"></td>
														<td width="25%" align="center"></td>
														<td width="25%" align="center">អ្នកប្រគល់</td>
													</tr>	
												</tbody></table>	
												<br/><br/><br/>
											</td>
										</tr>
									</tbody>
								</table>
							</td>
						</tr>
					</tbody></table>
				</td>
			</tr>
		</tbody>	
	</table>
	<?php if($i==0){?>
		<hr size="2" style="border: 1px dashed #000;" />
	<?php }?>
	<?php }?>
    </div>
    <div style="text-align: center;margin: 0 auto;clear:both;"> 
    	<lable class="col-md-3" style=""></lable>
    	<div class="col-md-2">
			<a href="<?php echo $this->baseUrl();?>/mong/customerpayment/"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a>
		</div>
    	<lable class="col-md-4" style="">
             <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i> រក្សាទុក/បោះ ពុម្ភ </button>
		</lable>
		<lable class="col-md-3" style=""></lable>
	</div>
</center>
<script>
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	//document.getElementById("office_receipt").submit();
}
</script>
   