<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
?>						 
<title>គ្រប់គ្រង ការលក់</title>
<body>
	<form class="form-horizontal" id="product_id" method="post" action="" >				
		
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i><strong>គ្រប់គ្រង ការលក់</strong>
				</div>
				<div class="tools">
					<label><a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a></label>
				</div>
			</div>
			<div class="portlet-body">
				<div class="tabbable-custom ">
					<div class="portlet-body form">
						<div class="form-body">
							<div class="row">
								<div class="col-md-6" style="text-align: left !important;border:1px solid #ccc;">
										<h4 style="border-bottom: 1px solid #ccc;" class="center">គ្រប់គ្រង ការលក់</h4>
									<div class="form-group" >
										<label class="col-md-4 control-label">ឈ្មោះអតិថិជន</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">ភេទ</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											លេខទូរស័ព្ទ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											អាស័យដ្ឋានកម្មវិធី
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" >
										<label class="col-md-4 control-label">ជ្រើសរើសសព</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											សម្គាល់ផ្សេងៗ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											ថ្ងៃគិតប្រាក់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
								</div>
								<div class="col-md-6" style="text-align: left !important;border:1px solid #ccc;border-left:1px solid #fff;">
									<h4 style="border-bottom: 1px solid #ccc;" class="center">ការបង់ប្រាក់</h4>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											លេខវិក័យបត្រ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											ថ្ងៃលក់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">អ្នកណែនាំ</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											លេខទូរស័ព្ទ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											កំរៃជើងសា
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											អ្នកទទួលប្រាក់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											សម្គាល់ផ្សេងៗ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-8">
									<div class="form-group" style=""></div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											<strong>ស្វែងរកមុខទំនិញ</strong>
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
								</div>
								<div class="col-md-1"></div>
							</div>
							<div class="row">
								<div class="col-md-12">
									 <table id="table_row"  style=";border-collapse: collapse; border:1px solid #ccc;width:100%;">
										<thead>
											<tr id="head-title" class="table table-bordered" align="right" style="background:#ccc">
												<th class="aligncenter">#</th>
												<th class="aligncenter">មុខទំនិញ/សេវាកម្ម</th>
												<th class="aligncenter">ស្តុក</th>
												<th class="aligncenter">បរិ.ដុំ</th>
												<th class="aligncenter">បរិ.រាយ</th>
												<th class="aligncenter">បរិមាណ</th>
												<th class="aligncenter">តម្លៃលក់</th>
												<th class="aligncenter">សរុប</th>
												<th class="aligncenter">លុប</th>
											</tr>
											<tr>
												<td colspan="11" id="lbl_noproduct" align="center">មិនមាន ទំនិញ ក្នុងកន្រ្តក</td>
											</tr>
										</thead>
									</table>
								</div>
							</div>
							<div class="row">
								<div class="col-md-1"></div>
								<div class="col-md-6"></div>
								<div class="col-md-5" style="text-align: left !important;">
									<div class="form-group" style=""></div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											តម្លៃសរុប
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											បានបង់ពីមុនសុរប
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											បានបង់សរុប
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											នៅខ្វះ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control" name="" id="" />
										</div>
									</div>
								</div>
							</div>
							<div class="form-group">
								<br />
								<div class="col-md-3"></div>
								<div class="col-md-3">
									<a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" class="btn red btn-block btn-lg"><i class="icon-refresh icon-white"></i> ត្រឡប់ក្រោយ</button></a>
								</div>
								<div class="col-md-3">
									<div class="input-icon right">
										<button type="submit" name="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> រក្សាទុក</button>
									</div>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>	
</body>
</html>