<?php 
	$url_new = $this->url(array('module'=>'sales','controller'=>'program','action'=>'add',));
	$url_edit = $this->url(array('module'=>'sales','controller'=>'program','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'sales','controller'=>'program','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	$rs = $this->product;
?>
<title>កម្មវិធីបុណ្យ</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("កម្មវិធីបុណ្យ");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-bg blue  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			<div class="portlet-body form frmfilter">
				<form id="frm" method="post" autocomplete="off" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group">
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('ad_search');?>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('branch');?>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('start_date');?>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('end_date');?>
							</label>
							<label class="control-label col-md-2">
								<?php echo $formFilter->getElement('status');?>
							</label>
							<label class="control-label col-md-2">
								<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-search"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
							</label>
						</div>				
				</form> 
				<div class="contain_form" style="clear: both;width: 500px;">
						<?php //echo $this->list; ?>						
					<table class="display nowrap dataTable dtr-inline collapsed" id="datatable-responsive" width="100%">
						<thead>
							<tr style="white-space:nowrap;">
								<th rowspan="2" class="tdheader">ល.រ</th>
								<th colspan="6" class="tdheader">ព័ត៌មានលម្អិតរបស់សព</th>
								<th colspan="6" class="tdheader">ព័ត៌មានលម្អិតរបស់ដៃគូសព</th>
								<th colspan="2" class="tdheader">ព័ត៌មានទីតាំង</th>
								<th rowspan="2" class="tdheader" width="6%">ថ្ងៃបង្កើត</th>
								<th rowspan="2" class="tdheader">អ្នកប្រើប្រាស់</th>	
								<th rowspan="2" class="tdheader">ស្ថានការ</th>	
							</tr>
							<tr style="white-space:nowrap;">
								<th class="tdheader" width="7%">ឈ្មោះ</th>
								<th class="tdheader" width="7%">ឈ្មោះ(ចិន)</th>
								<th class="tdheader">ភេទ</th>
								<th class="tdheader">ឆ្នាំ</th>
								<th class="tdheader">អាយុ</th>
								<th class="tdheader" width="8%">ស្លាប់នៅថ្ងៃ</th>
								
								<th class="tdheader" width="7%">ឈ្មោះ</th>
								<th class="tdheader" width="7%">ឈ្មោះ(ចិន)</th>
								<th class="tdheader">ភេទ</th>
								<th class="tdheader">ឆ្នាំ</th>
								<th class="tdheader">អាយុ</th>
								<th class="tdheader" width="8%">ស្លាប់នៅថ្ងៃ</th>
								
								<th class="tdheader">ទីតាំងបុណ្យ</th>
								<th class="tdheader">ទីតាំងបញ្ចុះ/បូជា</th>
							</tr>
						</thead>						
						<?php 
							$link=$this->baseUrl()."/sales/program/edit/id/";
							$link1=$this->baseUrl()."/sales/program/travel/id/";
							$link2=$this->baseUrl()."/sales/program/copy/id/";
							//echo $link;
						?>					
						<tbody>
							<?php $i=0;if(!empty($this->rs)){foreach ($this->rs as $rs){ $i++; ?>
							<tr oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;" class="context-menu-one normal" style="white-space:nowrap;height:40px;"> 
								<td class="items-no"><?php echo $i;?></td>
								<td class="items" ><a href="<?php echo $link.$rs['id'];?>" target="_blank"><?php echo $rs['dead_name'];?></a></td>
								<td class="items" ><a href="<?php echo $link.$rs['id'];?>" target="_blank"><?php echo $rs['dead_name_chinese'];?></a></td>
								<td class="items" align="center" ><?php echo $rs['dead_sex'];?></td>
								<td class="items" align="center"><?php echo $rs['dead_khmer_year'];?></td>
								<td class="items" align="center"><?php echo $rs['dead_age'];?></td>
								<td class="items" align="center"><a href="<?php echo $link.$rs['id'];?>" target="_blank"><?php if(!empty($rs['date_time_dead'])){echo date("d-m-Y H:i",strtotime($rs['date_time_dead']));}?></a></td>								
								<td class="items" ><a href="<?php echo $link.$rs['id'];?>" target="_blank"><?php echo $rs['partner_name'];?></a></td>
								<td class="items" ><a href="<?php echo $link.$rs['id'];?>" target="_blank"><?php echo $rs['partner_name_chinese'];?></a></td>
								<td class="items" align="center"><?php echo $rs['partner_sex'];?></td>
								<td class="items" align="center"><?php echo $rs['partner_khmer_year'];?></td>
								<td class="items" align="center"><?php echo $rs['partner_age'];?></td>
								<td class="items" align="center"><a href="<?php echo $link.$rs['id'];?>" target="_blank"><?php if(!empty($rs['date_time_female'])){echo date("d-m-Y H:i",strtotime($rs['date_time_female']));}?></a></td>								
								<td class="items" ><?php echo $rs['place_of_program'];?></td>
								<td class="items" ><?php echo $rs['place_pjos_sop'];?></td>
								<td class="items" align="center"><?php echo date("d-m-Y",strtotime($rs['create_date']));?></td>
								<td class="items" align="center"><?php echo $rs['user_id'];?></td>
								<td class="items" align="center"><?php echo $rs['status'];?></td>
							</tr>
							<?php }}?>
						</tbody>
					</table>	
			    </div>
			    
			    <div class="footer_list">
			    <?php if(!empty($this->rs)){?>
			    
				    <script type="text/javascript">
						$(document).ready(function(){
							$("#table").tablesorter();
							$("#table").tablesorter().tablesorterPager({container: $("#pagination_table"),size:15});
							$("#pagedisplay").focus(function(){ this.blur(); 
							
		                    });
						});
					</script>
					<div id="pagination_table" class="pager" >
						<form >
							<table  style="width: 200px;"><tr>
							<td><img src="/bunastock/trunk/public/images/first.gif" class="first"/></td>
							<td><img src="/bunastock/trunk/public/images/previous.gif" class="prev"/></td>
							<td><input id="pagedisplay" type="text" class="pagedisplay"/></td>
							<td><img src="/bunastock/trunk/public/images/next.gif" class="next"/></td>
							<td><img src="/bunastock/trunk/public/images/last.gif" class="last"/></td>
							<td><select class="pagesize" >
								<option   value="10">10</option>
								<option selected="selected"  value="15">15</option>
								<option value="20">20</option>
								<option value="30">30</option>
								<option value="40">40</option>
								<option value="50">50</option>
								<option value="60">60</option>
								<option value="70">70</option>
								<option value="80">80</option>
								<option value="90">90</option>
								<option value="100">100</option>
								</select>
						    </td>
							</tr>
							</table>
						</form>
					</div>
					<span class="row_num">ចំនួនជួរ<?php echo $i;?></span>
				
				<?php }else{?>
						<center style="font-size:18pt;">No record</center>
				<?php }?>
				</div>
		   </div>
		</div>
	</div>
</div>
<script>
var row=0;
var url="";
$(function(){	
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {		
			var m = "clicked: " + key;
			if(key=="edit"){
				url='<?php echo $this->baseUrl()."/sales/program/edit/id/";?>';
			}else if(key=="travel"){
				url='<?php echo $this->baseUrl()."/sales/program/travel/id/";?>';
			}else if(key=="copy"){
				url='<?php echo $this->baseUrl()."/sales/program/copy/id/";?>';
			}
			
			gotoAction();
		},
		items: {
			"edit": {name: "កែប្រែ", icon: "edit", accesskey: "e"},
			"travel": {name: "វេលាកម្មវិធី", icon:  "fa-clock-o", accesskey: "e"},
			"copy": {name: "copy", icon:  "copy", accesskey: "e"},
		}
	});
});
function setrowdata(index){
	  row = index;
	}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>





















