<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
	$row = $this->row;
?>
<div id="Printtimemol" >
<div class="wrapper" id="borderimg1" background: #fff;width:24cm;margin: 0 auto; min-height: 25cm;padding: 0.5cm;">
		<style>
	    	.wrapper{
	    		width: 100%;
	    		margin: 0px;
	    		padding: 0px;
	    	}
	    	.contain{
	    		width: 1024px;
	    		margin: 0 auto;
	    	}
			table {
	    		border-collapse: collapse;
	    		width: 100%;
			}
			th, td {
	    		padding: 4px;
			}
			#borderimg1 { 
			    border: 12px solid transparent;
			    border-image: url(/bunastock/trunk/public/images/kiifo.jpg) 35 round;
			}
	    </style>
		<table cellpadding="0" cellspacing="0" width="100%">
			<tr class="no-boder">
				<td>
				<table width="100%" >
					<tr>
						<td width="20%" align="center">
							<img style="width: 135%;height: 125px;" alt="<?php ?>" src="<?php echo $this->baseUrl()?>/images/logosbona.jpg"><br>
							<span style="font-family: Freestyle Script;font-size: 20px;"></span>
							
						</td>
						<td width="60%">
							<table   style="text-align:center;border:solid 1px #FFF;">
								<tr style="list-style:12px; font-family:  Khmer OS Muol; font-size:45px;font-weight: bold;color:red;">
									<td>ព័ត៌មានផ្លាកម៉ុង</td>
								</tr>	
							</table>
						</td>
						<td width="20%" >&nbsp;</td>
					</tr>
				</table>
				</td>
			</tr>
		  	<tr>
		  		<td>
	  			<table style="font-size:15px;font-family: Khmer OS Battambang, Times New Roman;">  			
	  				<tr style="list-style:25px; font-family:  Khmer OS Muol;line-height:53px; font-size:29px;font-weight: bold; list-style:none; color:#800080;">
	  					<td>
	  						<li>ទីតាំង៖ &nbsp; <?php echo $this->row['place_of_program']?></li>
	  						<li>ទូរស័ទ្ទ៖ &nbsp; <?php echo $this->row['membersone']?> - <?php echo $this->row['memberstwo']?></li>
	  					</td>
	  				</tr>
	  				<tr style="list-style:25px; font-family:  Khmer OS Muol;line-height:53px; font-size:25px;font-weight: bold; list-style:none; color:#009900;">
	  					<td>
	  						<li>ព័ត៌មានរបស់សព៖ (<?php echo $this->row['dead_status']?>)</li>
	  						<li>&nbsp;&nbsp;<i class="fa fa-bullseye" style="font-size:20px;"></i>ឈ្មោះ(ខ្មែរ)  <?php echo $this->row['dead_name']?></li>
	  						<li>&nbsp;&nbsp;<i class="fa fa-bullseye" style="font-size:20px;"></i>ឈ្មោះ(ចិន)  <?php echo $this->row['dead_name_chinese']?></li>
	  					</td>
	  				</tr>
	  				<tr style="list-style:25px; font-family:  Khmer OS Muol;line-height:53px; font-size:25px;font-weight: bold; list-style:none; color:#009900;">
	  					<td>
	  						<li>ព័ត៌មានរបស់ដៃគូសព៖</li>
	  						<li>&nbsp;&nbsp;<i class="fa fa-bullseye" style="font-size:20px;"></i>ឈ្មោះ(ខ្មែរ)  <?php echo $this->row['partner_name']?></li>
	  						<li>&nbsp;&nbsp;<i class="fa fa-bullseye" style="font-size:20px;"></i>ឈ្មោះ(ចិន)  <?php echo $this->row['partner_name_chinese']?></li>
	  					</td>
	  				</tr>
	  				<tr style="list-style:25px; font-family:  Khmer OS Muol;line-height:53px; font-size:25px;font-weight: bold; list-style:none; color:#B22222;">
	  					
	  					<td>
	  						<li><i class="fa fa-chevron-circle-right" style="font-size:25px;"></i>ថ្ងៃកើត៖  <?php echo $this->row['dead_dob']?> </li>
	  						<li><i class="fa fa-chevron-circle-right" style="font-size:25px;"></i>ថ្ងៃស្លាប់៖   <?php echo $this->row['date_time_dead']?></li>
	  						<li><i class="fa fa-chevron-circle-right" style="font-size:25px;"></i>ស្រុកកំណើតសព៖ <?php echo $this->row['dead_pob']?></li>
	  					<li><i class="fa fa-chevron-circle-right" style="font-size:25px;"></i>ឆ្នាំកូនប្រុស៖
	  					<?php     
		              		  if(!empty($this->khmer_year_boy))foreach ($this->khmer_year_boy AS $index => $rs){?>-
	  					<?php echo $rs["khmer_year_name"];?>				  						
	  					<?php }?></li>
	  					<li><i class="fa fa-chevron-circle-right" style="font-size:25px;"></i>ឆ្នាំកូនស្រី៖
	  					<?php     
		              		  if(!empty($this->khmer_year_girl))foreach ($this->khmer_year_girl AS $index => $rs){?>-
	  					<?php echo $rs["khmer_year_name"];?>				  						
	  					<?php }?></li>
	  					</td>		
	  				</tr>
	  			</table>
	  			<table style="font-size:15px;font-family: Khmer OS Battambang, Times New Roman;">  			
	  				<tr style="list-style:25px; font-family:  Khmer OS Muol;line-height:38px; font-size:29px;font-weight: bold; list-style:none; color:#800080;">
	  					<td>
	  					&nbsp;
	  					</td>
	  				</tr>
	  			</table>
		</table>
	</div>
</div>
<div style="padding-left:14%; margin: 0 auto;"> 
    	<lable class="col-md-3" style=""></lable>
    	<div class="col-md-2">
			<a href="<?php echo $this->baseUrl();?>/mong/index"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ចាកចេញ</button></a>
		</div>
    	<lable class="col-md-2" style="">
             <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i> បោះពុម្ភ </button>
		</lable>
		<lable class="col-md-3" style=""></lable>
</div>
<script>
function printinvoice(){
	var printContents = document.getElementById('Printtimemol').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_timemol").submit();
}
</script>


