<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
	$row = $this->row;
?>
<title>កែប្រែកម្មវិធីបុណ្យ</title>
<div id="Printdonate">
	<div class="wrapper" id="borderimg1" style="background: #fff;width:26cm;margin: 0 auto;min-height: 37cm;padding: 0.5cm;">
		<style>
	    	.wrapper{
	    		width: 100%;
	    		margin: 0px;
	    		padding: 0px;
	    	}
			table {
	    		border-collapse: collapse;
	    		width: 100%;
			}
			th, td {
	    		padding: 4px;
			}
			#borderimg1 { 
			    border: 85px dotted ;
			    border-image: url("<?php echo $this->baseUrl()?>/images/ifrmas.jpg") 125 stretch;
			}
			
	    </style>
		<table cellpadding="0" cellspacing="0" width="100%" style="font-family:  Khmer OS Muol; font-weight: bold; margin-top: -40px; white-space: nowrap">		 
			<tr>
				<td width="20%" align="center">
					<img style="max-height:230px; width: 110%;" alt="<?php ?>" src="<?php echo $this->baseUrl()?>/images/logosbona.jpg"><br>
					<span style="font-family: Freestyle Script;font-size: 20px;"></span>
				</td>
				<td align="center" width="63%" style="color:red !important;font-size: 68px;">
					ចៅ ប៊ុនណា
				</td>
				<td width="20%" >&nbsp;</td>
			</tr>
		  	<tr>
		  		<td colspan="3" align="center" style="color:blue !important;font-size: 45px;">
	  				លើកសពចូលម្ឈូស
	  			</td>
	  		</tr>		
  			<tr >
  				<td colspan="3" align="center" style="color: #000;font-size: 32px;">
  					ថ្ងៃទី <?php echo date("d",strtotime($row['lerk_sop_date']));?> ខែ <?php echo date("m",strtotime($row['lerk_sop_date']));?> ឆ្នាំ 20<?php echo date("y",strtotime($row['lerk_sop_date']));?> 
  					វេលាម៉ោងៈ  <?php echo $this->row['lerk_sop_time']?> <br />
  					ឆុងនឹងឆ្នាំៈ <?php echo $this->row['hae_sop_jol_mchhos']?>
  				</td>
  			</tr>
  			<tr>
  				<td colspan="3" align="center" style="color:blue !important;font-size: 45px;"> 
  					ហែរសពចេញ
  				</td>
  			</tr>
  			<tr >
  				<td colspan="3" align="center" style="color: #000;font-size: 32px;">
  					ថ្ងៃទី <?php echo date("d",strtotime($row['hae_sop_date']));?> ខែ <?php echo date("m",strtotime($row['hae_sop_date']));?> ឆ្នាំ 20<?php echo date("y",strtotime($row['hae_sop_date']));?> 
  					វេលាម៉ោងៈ  <?php echo $this->row['hae_sop_time']?> <br />
  					ឆុងនឹងឆ្នាំៈ  <?php echo $this->row['hae_sop_jenh']?>
  				</td>
	  		</tr>
  			<tr>
  				<td colspan="3" align="center" style="color:red !important;font-size: 45px;">
  					បញ្ចុះ/បូជា
  				</td>
  			</tr>
  			<tr>
  				<td colspan="3" align="center" style="color: #000;font-size: 32px;">
  					ថ្ងៃទី <?php echo date("d",strtotime($row['pjos_sop_date']));?> ខែ <?php echo date("m",strtotime($row['pjos_sop_date']));?> ឆ្នាំ 20<?php echo date("y",strtotime($row['pjos_sop_date']));?> 
  					វេលាម៉ោងៈ  <?php echo $this->row['pjos_sop_time']?> <br />
  					ឆុងនឹងឆ្នាំៈ  <?php echo $this->row['pjos_sop']?>
  				</td>
  			</tr>
	  		<tr>
  				<td colspan="3" align="center" style="font-size: 40px; ">
  					<u style="color:#22B424 !important;">កូនចៅកាន់ទុក្ខមិនឆុងទេ!</u>
  				</td>
  			</tr>
  			<tr align="center" style="list-style:25px; font-family:  Khmer OS Muol; line-height: 55px; color: #000; font-size:30px;font-weight: bold; list-style:none;">
  				<td  colspan="3" align="center" style="color: #black !important; ">
  					<i class="fa fa-home" style="font-size: 38px;"></i> ផ្ទះលេខ ៧៣ ផ្លូវមាត់ទន្លេកែងផ្លូវលេខ១០០ <br>(មុខក្រសួងប្រៃសណីយ៍វត្តភ្នំ)<br >
  					<i class="fa fa-facebook-square" style="font-size: 35px;"></i> Chao Bunna 73 Funeral Service <br >
  					<i class="fa fa-phone-square" style="font-size: 35px;"></i> <?php echo $tr->translate("PHONE_BUNA");?> , 012 31 73 73
  				</td>
  			</tr>	  								  	
		</table>
	</div>
</div>
<div style="padding-left:16%; margin: 0 auto;"> 
	<lable class="col-md-3" style=""></lable>
	<div class="col-md-2">
		<a href="<?php echo $this->baseUrl();?>/mong/index"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ចាកចេញ</button></a>
	</div>
	<lable class="col-md-2" style="">
		<button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i> បោះពុម្ភ </button>
	</lable>
	<lable class="col-md-3" style=""></lable>
</div>

<script>
function printinvoice(){
	var printContents = document.getElementById('Printdonate').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
}
</script>


