<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
?>						 
<title>ផ្នែក កញ្ចប់ទំនិញ/សេវាកម្ម</title>
<body>
	<form class="form-horizontal" id="frmproduct_id" method="post" action="" >				
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i><strong>ផ្នែក កញ្ចប់ទំនិញ/សេវាកម្ម</strong>
				</div>
				<div class="tools">
					<label><a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a></label>
				</div>
			</div>
			<div class="portlet-body">
				<div class="tabbable-custom">
					<div class="portlet-body form">
						<div class="form-body">
							<div class="row">
								<div class="form-body">
									<div class="row">
										<div class="col-md-3" style="text-align: left !important;">
										</div>
										<div class="col-md-6" style="text-align: left !important;">
											<div class="form-group">
												<label class="col-md-4 control-label"><strong>ទំនិញ/សេវាកម្ម</strong></label>
												<div class="col-md-8">
													<select name="product_type" class="form-control"><option value="0">ប្រភេទទំនិញ</option><option value="1">ប្រភេទសេវាកម្ម</option></select>
												</div>
											</div>
											<div class="form-group" >
												<label class="col-md-4 control-label">កញ្ចប់ទំនិញ/សេវាកម្ម</label>
												<div class="col-md-8">
													<input type="text" class="form-control" required="true" name="product_name" id="product_name" />
												</div>
											</div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">លេខកូដ</label>
												<div class="col-md-8">
													<input type="text" readonly="readonly" class="form-control" name="product_code" id="product_code" value="<?php echo $this->pro_code;?>" />
												</div>
											</div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">
													ប្រភេទទំនិញ
												</label>
												<div class="col-md-8">
													<select name="cate_id" id="cate_id" class="form-control select2me">
														<option value="-1">សូមជ្រើសរើសប្រភេទទំនិញ-សេវាកម្ម</option>
														<?php if(!empty($this->caters)){ foreach($this->caters as $rs){?>
														<option value="<?php echo $rs['id']?>"><?php echo $rs['name'];?></option>
														<?php }}?>
									    			</select>
												</div>
											</div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">
													តម្លៃលក់សរុប
												</label>
												<div class="col-md-8">
													<input type="text" readonly="readonly" class="form-control" name="total_cost" id="total_cost" />
												</div>
											</div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">
													សម្គាល់
												</label>
												<div class="col-md-8">
													<input type="text" class="form-control" name="noted" id="noted" />
												</div>
											</div>
										</div>
										<div class="col-md-3" style="text-align: left !important;">
										</div>
									</div>
									<div class="row">
										<div class="col-md-3"></div>
										<div class="col-md-6">
											<div class="form-group" style=""></div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">
													<strong>ស្វែងរកមុខទំនិញ</strong>
												</label>
												<div class="col-md-8">
													<select name="product_id" id="product_id" onchange="addProductRow();" class="form-control select2me">
														<option value="-1">សូមជ្រើសរើសទំនិញ-សេវាកម្ម</option>
														<?php if(!empty($this->rsproduct)){ foreach($this->rsproduct as $rs){?>
														<option value="<?php echo $rs['id']?>"><?php echo $rs['name'].'-'.$rs['item_code']?></option>
														<?php }}?>
									    			</select>
												</div>
											</div>
										</div>
										<div class="col-md-3"></div>
									</div>
									<div class="row">
										<div class="col-md-1"></div>
										<div class="col-md-10">
											 <div class="portlet box blue">
												<div class="portlet-title">
													<div class="caption">
														<i class="fa fa-cogs"></i>ទំនិញ/សេវាកម្ម
													</div>
												</div>
												 <div class="portlet-body">
													<div class="table-responsive">
														 <table id="table_row" class="table table-bordered" style="font-size:12px !important;">
															<thead>
																<tr style="text-align: center !important;">
																	<th class="aligncenter">#</th>
																	<th class="aligncenter" style="min-width:200px;white-space: nowrap;">ឈ្មោះ/ទំនិញសេវាកម្ម</th>
																	<th class="aligncenter">ចំនួន</th>
																	<th class="aligncenter">តម្លៃ</th>
																	<th class="aligncenter">សរុប</th>
																	<th class="aligncenter">សម្គាល់</th>
																	<th class="aligncenter">លុប</th>
																</tr>
															</thead>
															<tbody id="lbl_noproduct">
															</tbody>
														</table>
													</div>
												</div>
											</div>
										</div>
										<div class="col-md-1">
											<input id="identity" name="identity" type="text" />
										</div>
									</div>
								</div>
							</div>
							<div class="form-group">
								<div class="col-md-3"></div>
								<div class="col-md-3">
									<a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" class="btn red btn-block btn-lg"><i class="icon-refresh icon-white"></i> ត្រឡប់ក្រោយ</button></a>
								</div>
								<div class="col-md-3">
									<div class="input-icon right">
										<button type="submit" name="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> រក្សាទុក</button>
									</div>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>	
</body>
</html>
<script>

index=0;
title=0;
temp='';
function addProductRow(){
	index++;
	var branch_text = $("#product_id");
	var txt_br = $("option:selected",branch_text).text();
	var pro_id = $("#product_id").val();
	
	if(pro_id<0){return false;}
	template='<tr id="row_location_'+index+'">';
	template+='<td>'+index+'</td>';
	template+='<td>'+txt_br+'<input type="hidden" id="product_id'+index+'" name="product_id'+index+'" value="'+pro_id+'" </td>';
	template+='<td><input type="text" onkeyup="totalQty('+index+');return isNumberKey(event);" id="qty_'+index+'"  name="qty_'+index+'" value="0" class="form-control"></td>'; 
	template+='<td><input type="text" onkeyup="totalQty('+index+');return isNumberKey(event);" id="price_'+index+'" name="price_'+index+'" value="0" class="form-control"></td>'; 
	template+='<td><input readonly="readonly" type="text" id="total_'+index+'" name="total_'+index+'"  class="form-control"></td>'; 
	template+='<td><input type="text" id="note_'+index+'" name="note_'+index+'" value="0" class="form-control"></td>';
	template+='<td><button type="button" onClick="deleteRecord('+index+')" name="save_close" class="btn default red">លុប</button></td>';
	template+='</tr>';
	$('#lbl_noproduct').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index);
	} else {$('#identity').val(index);}
}
function totalQty(index){
	qty=$("#qty_"+index).val();
	price=$("#price_"+index).val();
	total = qty*price;
	$("#total_"+index).val(total);
	netTotal();
}
function netTotal(){//use
	var netTotal=0;
	$('#total_cost').val(0);
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += Number($('#total_'+rowIDArray[n]).val());
	}
	if(isNaN(netTotal)){
		netTotal=0;
	}
	$('#total_cost').val(netTotal.toFixed(2));
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_location_"+index).remove();
	netTotal();
}
</script>