<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
?>						 
<title>ផ្នែក កញ្ចប់ទំនិញ/សេវាកម្ម</title>
<body>
	<form class="form-horizontal" id="product_id" method="post" action="" >				
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i><strong>ផ្នែក កញ្ចប់ទំនិញ/សេវាកម្ម</strong>
				</div>
				<div class="tools">
					<label><a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a></label>
				</div>
			</div>
			<div class="portlet-body">
				<div class="tabbable-custom">
					<div class="portlet-body form">
						<div class="form-body">
							<div class="row">
								<div class="form-body">
									<div class="row">
										<div class="col-md-3" style="text-align: left !important;">
										</div>
										<div class="col-md-6" style="text-align: left !important;">
											<div class="form-group" >
												<label class="col-md-4 control-label">កញ្ចប់ទំនិញ/សេវាកម្ម</label>
												<div class="col-md-8">
													<input type="text" class="form-control" name="" id="" />
												</div>
											</div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">លេខកូដ</label>
												<div class="col-md-8">
													<input type="text" class="form-control" name="" id="" />
												</div>
											</div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">
													ប្រភេទទំនិញ
												</label>
												<div class="col-md-8">
													<input type="text" class="form-control" name="" id="" />
												</div>
											</div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">
													តម្លៃលក់សរុប
												</label>
												<div class="col-md-8">
													<input type="text" class="form-control" name="" id="" />
												</div>
											</div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">
													សម្គាល់
												</label>
												<div class="col-md-8">
													<input type="text" class="form-control" name="" id="" />
												</div>
											</div>
										</div>
										<div class="col-md-3" style="text-align: left !important;">
										</div>
									</div>
									<div class="row">
										<div class="col-md-3"></div>
										<div class="col-md-6">
											<div class="form-group" style=""></div>
											<div class="form-group" style="">
												<label class="col-md-4 control-label">
													<strong>ស្វែងរកមុខទំនិញ</strong>
												</label>
												<div class="col-md-8">
													<select name="product_id" id="product_id" onchange="addProductRow();" class="form-control select2me">
														<option value="-1">សូមជ្រើសរើសទំនិញ-សេវាកម្ម</option>
														<?php if(!empty($this->rsproduct)){ foreach($this->rsproduct as $rs){?>
														<option value="<?php echo $rs['id']?>"><?php echo $rs['name'].'-'.$rs['item_code']?></option>
														<?php }}?>
									    			</select>
												</div>
											</div>
										</div>
										<div class="col-md-3"></div>
									</div>
									<div class="row">
										<div class="col-md-1"></div>
										<div class="col-md-10">
											 <table id="table_row"  style=";border-collapse: collapse; border:1px solid #ccc;width:100%;">
												<thead>
													<tr>
														<th class="aligncenter">#</th>
														<th class="aligncenter">ឈ្មោះ/ទំនិញសេវាកម្ម</th>
														<th class="aligncenter">ចំនួន</th>
														<th class="aligncenter">តម្លៃ</th>
														<th class="aligncenter">សរុប</th>
														<th class="aligncenter">សម្គាល់</th>
													</tr>
												</thead>
												<tbody id="lbl_noproduct">
												</tbody>
											</table>
										</div>
										<div class="col-md-1">
											<input id="identity" name="identity" type="text" />
										</div>
									</div>
								</div>
							</div>
							<div class="form-group">
								<div class="col-md-3"></div>
								<div class="col-md-3">
									<a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" class="btn red btn-block btn-lg"><i class="icon-refresh icon-white"></i> ត្រឡប់ក្រោយ</button></a>
								</div>
								<div class="col-md-3">
									<div class="input-icon right">
										<button type="submit" name="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> រក្សាទុក</button>
									</div>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>	
</body>
</html>
<script>

index=0;
title=0;
temp='';
function addProductRow(){
	index++;
	var branch_text = $("#product_id");
	var txt_br = $("option:selected",branch_text).text();
	var branch_id = $("#product_id").val();
	
	template='<tr id="row_location_'+index+'">';
	template+='<td>'+index+'</td>';
	template+='<td>'+txt_br+'<input type="hidden" id="branch_id_'+index+'" name="branch_id_'+index+'" value="'+branch_id+'" </td>';
	template+='<td><input type="text" id="current_qty_'+index+'" onKeyup="totalQty('+index+')" name="current_qty_'+index+'" value="0" class="form-control"></td>'; 
	template+='<td><input type="text" id="other_qty_'+index+'" onKeyup="totalQty('+index+')" name="other_qty_'+index+'" value="0" class="form-control"></td>'; 
	template+='<td><input type="text" id="total_qty_'+index+'" name="total_qty_'+index+'" value="0" class="form-control"></td>'; 
	template+='<td><input type="text" id="qty_warning_'+index+'" name="qty_warnning_'+index+'" value="0" class="form-control"></td>';
	template+='<td><button type="button" onClick="deleteRecord('+index+')" name="save_close" class="btn default">DELETE</button></td>';
	template+='</tr>';
	$('#lbl_noproduct').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index);
	} else {$('#identity').val(index);}
}
function deleteRecord(index) {
	
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_location_"+index).remove();
}
</script>