<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<title>អត្រាប្តូរប្រាក់</title>
<form class="form-horizontal" id="frm" method="post" action="<?php ?>" enctype="multipart/form-data" autocomplete="off">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-gift"></i><?php echo $tr->translate("អត្រាប្តូរប្រាក់");?>
			</div>
		</div>
		
		<style>
			.form-control{
				border: 1px solid #ffffff !important;
				text-align: center;
				font-size: 16px;
				font-weight: bold;
			}
		</style>
		
		<div class="portlet-body">
			<div class="tabbable-custom ">
				<div class="portlet-body form">
					<div class="form-body">
						<div class="row">
							<div class="form-group" >
								<div class="col-md-1">
								</div>
								<div class="col-md-10">
									<table width="100%" border="1" style="font-weight: bold;border:1px solid #000; border-collapse: collapse;text-align: center;">
										<tr height="40px" style="font-size: 18px;background: #65879a;color: #FFFFFF; " >
											<td width="34%">ប្រភេទប្តូរ (ដុល្លារ ->រៀល )</td>
											<td width="33%">ដុល្លារ</td>
											<td width="33%">រៀល</td>
										</tr>
										<tr height="40px" style="font-size: 16px;">
											<td width="34%">ទិញចូល</td>
											<td width="33%">
												<?php echo $this->rs[0]['dollar']?>
											</td>
											<td width="33%">
												<input name="reil1" id="reil1" class="form-control" value="<?php echo $this->rs[0]['reil']?>"/> 
												<input type="hidden" name="id1" id="id1" class="form-control" value="<?php echo $this->rs[0]['id']?>"/> 
											</td>
										</tr>
										
										<tr height="40px" style="font-size: 16px;">
											<td width="34%">លក់ចេញ</td>
											<td width="33%">
												<?php echo $this->rs[1]['dollar']?>
											</td>
											<td width="33%">
												<input name="reil2" id="reil2" class="form-control" value="<?php echo $this->rs[1]['reil']?>"/> 
												<input type="hidden" name="id2" id="id2" class="form-control" value="<?php echo $this->rs[1]['id']?>"/> 
											</td>
										</tr>
									</table>
								</div>
								<div class="col-md-1">
								</div>
							</div>
							
							<div class="form-group" >
								<div class="col-md-5">
								</div>
								<div class="col-md-2">
									<div class="input-icon right">
										<button type="submit" id="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> <?php echo $tr->translate("រក្សាទុក")?></button>
									</div>
								</div>
								<div class="col-md-5">
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>	
</form>