<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
?>						 
<title>ការឧបត្ថមរបស់សប្បុរសជន</title>
<body>
	<form class="form-horizontal" id="product_id" method="post" action="" >				
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i><strong>ការឧបត្ថមរបស់សប្បុរសជន</strong>
				</div>
				<div class="tools">
					<label><a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a></label>
				</div>
			</div>
			<div class="portlet-body">
				<div class="tabbable-custom ">
					<div class="portlet-body form">
						<div class="form-body">
							<div class="row">
								<div class="col-md-1">
								</div>
								<div class="col-md-5" style="text-align: left !important;border:1px solid #ccc;">
										<h4 style="border-bottom: 1px solid #ccc;" class="center">ការឧបត្ថមរបស់សប្បុរសជន</h4>
									<div class="form-group" >
										<label class="col-md-4 control-label">ឈ្មោះសប្បុរសជន</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">លេខទូរស័ព្ទ</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											អាស័យដ្ឋាន
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											តម្រូវការប្រើប្រាស់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" >
										<label class="col-md-4 control-label">ខែប្រើប្រាស់យូរបំផុត</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											សម្គាល់ផ្សេងៗ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
								</div>
								<div class="col-md-5" style="text-align: left !important;border:1px solid #ccc;">
									<h4 style="border-bottom: 1px solid #ccc;" class="center">ការបង់ប្រាក់</h4>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											លេខបង្កាន់ដៃបង់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											ថ្ងៃបង់ប្រាក់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">ចំនួនម្ឈូស</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											តម្លៃរាយ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											តម្លៃសរុប
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											សម្គាល់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control select2me" />
										</div>
									</div>
								</div>
								<div class="col-md-1" style="text-align: left !important;">
								</div>
							</div>
							<div class="form-group">
								<br />
								<div class="col-md-3"></div>
								<div class="col-md-3">
									<a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" class="btn red btn-block btn-lg"><i class="icon-refresh icon-white"></i> ត្រឡប់ក្រោយ</button></a>
								</div>
								<div class="col-md-3">
									<div class="input-icon right">
										<button type="submit" name="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> រក្សាទុក</button>
									</div>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>	
</body>
</html>