<?php 
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$module = $request->getModuleName();
	$controller=$request->getControllerName();
?>						 
<title>ការឧបត្ថមរបស់សប្បុរសជន</title>
<body>
	<form id="frm" class="form-horizontal" id="product_id" method="post" action="" autocomplete="off" >				
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-gift"></i><strong>ការឧបត្ថមរបស់សប្បុរសជន</strong>
				</div>
				<div class="tools">
					<label><a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" name="calcel" class="btn red"><i class="fa fa-times"></i>ត្រលប់ក្រោយ</button></a></label>
				</div>
			</div>
			<div class="portlet-body">
				<div class="tabbable-custom ">
					<div class="portlet-body form">
						<div class="form-body">
							<div class="row">
								<div class="col-md-1">
								</div>
								<div class="col-md-5" style="text-align: left !important;border:1px solid #ccc;">
										<h4 style="border-bottom: 1px solid #ccc;" class="center">ការឧបត្ថមរបស់សប្បុរសជន</h4>
									<div class="form-group" >
										<label class="col-md-4 control-label">ឈ្មោះប្ដី</label>
										<div class="col-md-8">
											<input type="text" class="validate[required] form-control " id="donor_name" name="donor_name"  />
										</div>
									</div>
									<div class="form-group" >
										<label class="col-md-4 control-label">ឈ្មោះប្រពន្ទ</label>
										<div class="col-md-8">
											<input type="text" class="validate[required] form-control " id="donor_female" name="donor_female"  />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">លេខទូរស័ព្ទ</label>
										<div class="col-md-8">
											<input type="text" class="form-control " id="tel" name="tel"  />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											អាស័យដ្ឋាន
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control " id="address" name="address"  />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											តម្រូវការប្រើប្រាស់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control " id="required_using" name="required_using"  />
										</div>
									</div>
									<div class="form-group" >
										<label class="col-md-4 control-label">ខែប្រើប្រាស់យូរបំផុត</label>
										<div class="col-md-8">
											<div class="input-icon right">
												<i class="fa fa-calendar"></i>
												<input type="text" class="form-control date-picker" name="invalid_date" id="invalid_date" value="<?php echo date("d-m-Y")?>" data-date-format="dd-mm-yyyy" />
											</div>
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											សម្គាល់ផ្សេងៗ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control " name="note" id="note" />
										</div>
									</div>
								</div>
								<div class="col-md-5" style="text-align: left !important;border:1px solid #ccc;">
									<h4 style="border-bottom: 1px solid #ccc;" class="center">ការបង់ប្រាក់</h4>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											លេខបង្កាន់ដៃ
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control " name="receipt_no" id="receipt_no" value="<?php echo $this->receipt_no;?>" readonly />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											ថ្ងៃបង់ប្រាក់
										</label>
										<div class="col-md-8">
											<div class="input-icon right">
												<i class="fa fa-calendar"></i>
												<input type="text" class="form-control date-picker" name="paid_date" id="paid_date" value="<?php echo date("d-m-Y")?>" data-date-format="dd-mm-yyyy" />
											</div>
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">ចំនួនម្ឈូស</label>
										<div class="col-md-8">
											<input type="number" class="validate[required] form-control " name="qty" id="qty" onclick="calculateTotal();" onkeyup="calculateTotal();" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											តម្លៃរាយ ($)
										</label>
										<div class="col-md-8">
											<input type="number" class="validate[required] form-control " name="unit_price" id="unit_price" onclick="calculateTotal();" onkeyup="calculateTotal();" />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											តម្លៃសរុប ($)
										</label>
										<div class="col-md-8">
											<input type="text" class="validate[required] form-control " name="total_amount" id="total_amount" readonly />
										</div>
									</div>
									<div class="form-group" style="">
										<label class="col-md-4 control-label">
											សម្គាល់
										</label>
										<div class="col-md-8">
											<input type="text" class="form-control " name="payment_note" id="payment_note" />
										</div>
									</div>
								</div>
								<div class="col-md-1" style="text-align: left !important;">
								</div>
							</div>
							<div class="form-group">
								<br />
								<div class="col-md-3"></div>
								<div class="col-md-3">
									<a href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><button type="button" class="btn red btn-block btn-lg"><i class="icon-refresh icon-white"></i> ត្រឡប់ក្រោយ</button></a>
								</div>
								<div class="col-md-3">
									<div class="input-icon right">
										<button type="submit" name="save_close" class="btn blue btn-block btn-lg" ><i class="fa fa-save"></i> រក្សាទុក</button>
									</div>
								</div>
								<div class="col-md-3"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</form>	
</body>
</html>

<script>
	function calculateTotal(){
		var qty = $('#qty').val();
		var unit_price = $('#unit_price').val();

		qty = isNaN(qty)?0:qty;
		unit_price = isNaN(unit_price)?0:unit_price;

		total = qty * unit_price;
		$('#total_amount').val(total);
		
	}
	
</script>


