<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'category','action'=>'add',));
	$url_cancel = $this->url(array('module'=>'product','controller'=>'category','action'=>'index',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title>បញ្ជីប្រភេទទំនិញ</title>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("បន្ថែមប្រភេទ");?>
			</div>
			<div class="tools">
				<label><a href="<?php echo $url_cancel;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a></label>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" id="frm" method="post" action="<?php echo $url_new;?>" autocomplete="off">
					<script>
					$('#frm').submit(function() {
				        $("#saveclose").attr("disabled", true);
				        $("#btnsavenew").attr("disabled", true);
				      });
					</script>
				<div class="form-body ">
					<div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("ប្រភេទ");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('parent');?>
								</div>
								<label class="col-md-2 control-label"><?php echo $tr->translate("CATEGORY_NAME");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('cat_name');?>
								</div>
												
							</div>
							<div class="form-group">
												
								<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('status');?>
								</div>
								<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('remark');?>
								</div>
							</div>
						
							<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
									<a href="<?php echo $this->baseUrl();?>/product/category/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
									<button type="submit" id="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
									<button type="submit" id="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
									
								</label>
							</div>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>