<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  $rpt_purchase=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-purchase'), null, true);
  $rpt_purcahsedetail=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-purchaseitem'), null, true);
  $rpt_sale=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-sales'), null, true);
  $rpt_saledetail=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-saleitem'), null, true);
  $rpt_customer=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-customer'), null, true);
  $rpt_saleperson=$this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-saleperson'), null, true);
  $rpt_expense = $this->url(array('module'=>'report','controller'=>'index','action'=>'rpt-expense'), null, true);
   
   $user_info = new Application_Model_DbTable_DbGetUserInfo();
	$result = $user_info->getUserInfo();
	$tr = Application_Form_FrmLanguages::getCurrentlanguage(); 
	$session_user=new Zend_Session_Namespace('auth');
	$request=Zend_Controller_Front::getInstance()->getRequest();
	 $level = $result["level"];
  
  ?>
 <title>របាយការណ៍ ចំនាយ-ទិញ-លក់</title> 
<div class="row">
	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="dashboard-stat blue-madison">
			<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'expense','action'=>'rpt-purchase'), null, true);?>">
			<div class="visual">
				<i class="fa fa-comments"></i>
			</div>
			<div class="details">
				<div class="number">
				</div>
				<div class="desc">
					 <?php echo $tr->translate("របាយការណ៍ បញ្ជាទិញ");?>
				</div>
			</div>
			</a>
			<a class="more" href="javascript:;">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="dashboard-stat red-intense">
			<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'expense','action'=>'rpt-purchaseitem'), null, true);?>">
			<div class="visual">
				<i class="fa fa-bar-chart-o"></i>
			</div>
			<div class="details">
				<div class="number">
				</div>
				<div class="desc">
					  <?php echo $tr->translate("របាយការណ៍ បញ្ជាទិញលម្អិត");?>
				</div>
			</div>
			</a>
			<a class="more" href="javascript:;">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	
	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="dashboard-stat purple-plum">
			<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'expense','action'=>'rpt-expense'), null, true);?>">
			<div class="visual">
				<i class="fa fa-globe"></i>
			</div>
			<div class="details">
				<div class="number">
					 
				</div>
				<div class="desc">
					<?php echo $tr->translate("របាយការណ៍ចំណាយផ្សេងៗ");?>
				</div>
			</div>
			</a>
			<a class="more" href="javascript:;">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="dashboard-stat blue-madison">
			<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'expense','action'=>'rpt-expense-by-type'), null, true);?>">
			<div class="visual">
				<i class="fa fa-globe"></i>
			</div>
			<div class="details">
				<div class="number">
				</div>
				<div class="desc">
				 <?php echo $tr->translate("របាយការណ៍ចំណាយតាមប្រភេទ");?>
				</div>
			</div>
			</a>
			<a class="more" href="javascript:;">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="dashboard-stat purple-plum">
			<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'expense','action'=>'rpt-vandorbalance'), null, true);?>">
			<div class="visual">
				<i class="fa fa-globe"></i>
			</div>
			<div class="details">
				<div class="number">
				</div>
				<div class="desc">
					  <?php echo $tr->translate("របាយការណ៍ ជំពាក់អ្នកផ្គត់ផ្គង់");?>
				</div>
			</div>
			</a>
			<a class="more" href="javascript:;">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	
	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="dashboard-stat green-haze">
			<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'expense','action'=>'rpt-paid-to-supplyer'), null, true);?>">
			<div class="visual">
				<i class="fa fa-globe"></i>
			</div>
			<div class="details">
				<div class="number">
				</div>
				<div class="desc">
					  <?php echo $tr->translate("របាយការណ៍ បង់ប្រាក់ទៅអ្នកផ្គត់ផ្គង់");?>
				</div>
			</div>
			</a>
			<a class="more" href="javascript:;">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	
	<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
		<div class="dashboard-stat red-intense">
			<a class="more" href="<?php echo $this->url(array('module'=>'report','controller'=>'expense','action'=>'rpt-all-expense'), null, true);?>">
			<div class="visual">
				<i class="fa fa-globe"></i>
			</div>
			<div class="details">
				<div class="number">
				</div>
				<div class="desc">
					  <?php echo $tr->translate("របាយការណ៍ចំណាយសរុបទាំងអស់");?>
				</div>
			</div>
			</a>
			<a class="more" href="javascript:;">
			View more <i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
	
	
</div>
