<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
?>
<title>របាយការណ៍ ជំពាក់អ្នកផ្គត់ផ្គង់</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("របាយការណ៍ ជំពាក់អ្នកផ្គត់ផ្គង់");?>
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
					 <ul class="dropdown-menu" role="menu">
						<li>
							<a href="#" onclick="doPrint();">
								<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
							</a>
						</li>
						<li>
							<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
						</li>
					 </ul>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<div class="form-group" style="padding-top: 6px;">
						<?php $formFilter = $this->formFilter; ?>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch_id');?></label>					
						<label class="control-label col-md-2">
							<select name="type" id="type" class="form-control select2me" >
								<option value="0" <?php if($this->rssearch['type']==0){echo "selected='selected'";}?>>ជ្រើសរើសប្រភេទ</option>
								<option value="1" <?php if($this->rssearch['type']==1){echo "selected='selected'";}?>>ចំណាយថ្លៃបញ្ជាទិញ</option>
								<option value="2" <?php if($this->rssearch['type']==2){echo "selected='selected'";}?>>ចំណាយថ្លៃជួលសេវាកម្ម</option>
								<option value="3" <?php if($this->rssearch['type']==3){echo "selected='selected'";}?>>ចំណាយថ្លៃជាង</option>
								<option value="4" <?php if($this->rssearch['type']==4){echo "selected='selected'";}?>>ចំណាយផ្សេងៗ</option>
							</select>
						</label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 11px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 29px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
			            	<tbody>
				            	<tr>
				                	<td align="center" width="16%" valign="top"><img  height="95px" src="<?php echo $this->baseUrl();?>/images/logosbona.jpg"></td>
				                	<td width="70%" valign="top">
				                		<ul>
				                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light'; color: #F31A1A  !important"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
				                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'; color: #F31A1A  !important">របាយការណ៍ ជំពាក់អ្នកផ្គត់ផ្គង់</li>
				                			<li style="text-align:center; font-size:14px; color: #F31A1A  !important"><?php if(!empty($this->rssearch['start_date'])){?><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));}?></li>
				                		</ul>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
			            	</tbody>
			            </table>
			        </td>
			    </tr>
				<tr>
			    	<td>
						&nbsp;
					</td>
				</tr>	
			    <tr>
			    	<td class="table2excel" id="exportExcel">
			            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
			                 <tbody>
								<tr bgcolor="#b0bdfd" align="center" style="font-weight:bold; line-height: 26px; font-size:14px !important;white-space: nowrap; ">
									<td>&nbsp;<?php echo $tr->translate("ចំណាយថ្លៃបញ្ជាទិញ");?></td>
									<td>&nbsp;<?php echo $tr->translate("ចំណាយថ្លៃជួលសេវាកម្ម");?></td>
									<td>&nbsp;<?php echo $tr->translate("ចំណាយថ្លៃជាង");?></td>
									<td>&nbsp;<?php echo $tr->translate("ចំណាយផ្សេងៗ");?></td>
								</tr>
								<?php $total_expense=0;?>
								<tr class='hover' align="center" style="font-size:13px;border:1px solid #000; white-space: nowrap;">
								   <td width="25%" style="white-space: nowrap;">&nbsp;<?php if(!empty($this->purchase_expense)){echo "$ ".number_format($this->purchase_expense["total_paid"],2); $total_expense = $total_expense + $this->purchase_expense["total_paid"];}?></td>
								   <td width="25%" style="white-space: nowrap;">&nbsp;<?php if(!empty($this->partner_service_expense)){echo "$ ".number_format($this->partner_service_expense["total_paid"],2); $total_expense = $total_expense + $this->partner_service_expense["total_paid"];}?></td>
								   <td width="25%" style="white-space: nowrap;">&nbsp;<?php if(!empty($this->constructor_expense)){echo "$ ".number_format($this->constructor_expense["total_paid"],2); $total_expense = $total_expense + $this->constructor_expense["total_paid"];}?></td>
								   <td width="25%" style="white-space: nowrap;">&nbsp;<?php if(!empty($this->other_expense)){echo "$ ".number_format($this->other_expense["total_paid"],2); $total_expense = $total_expense + $this->other_expense["total_paid"];}?></td>
								</tr>
			                </tbody>
			           </table>
					   <br>
			           <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;margin-top: 5px;" width="30%" align="center" cellspacing="0">
			           		<tbody>
				                <tr height="30px;" bgcolor="#d4dbff" class="style" align="center" style="">
				                    <td><strong style="font-size: 14px;"><?php echo $tr->translate("ចំណាយសរុប");?></strong></td>
				                </tr>
				                 <tr class="style" style=" line-height: 24px; font-size:13px;">
				                    <td align="center" style="font-family:'Open Sans', sans-serif;font-size: 14px; font-weight: bold;">&nbsp;<?php echo number_format($total_expense,2);?>&nbsp;$</td>
				                 </tr>
			               	</tbody>
			           </table>
					   
			           <br>
			           <br>
			           <table align="center" width="100%">
							   <tbody>
							   <tr style="font-size: 11px;">
							        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
							        <th></th>
							        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
							        <th></th>
							        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
							   </tr>
							</tbody>
						</table>	
		    		</td>
		    	</tr>
			</tbody>
			</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
