<title>កំណត់សិទ្ធអ្នកប្រើប្រាស់</title>
<style>
fieldset.fifthy {	
	border-right: 0px;
	width: 30%;
}
fieldset.fifthy table{
	padding-right: 1px;
}
table.user td{
	vertical-align: top;   
}
</style>       

<?php $rs=$this->rs;
	
	  $acl=($this->acl=='')? array():$this->acl;
	  $acl_name=($this->acl_name=='')? array(): $this->acl_name;
	  $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	  $df=$this->data;
	  $module_str = array(
	  		'product'=>'ស្តុក',
	  		'purchase'=>'គ្រប់គ្រងការបញ្ជាទិញ',
	  		'sales'=>'គ្រប់គ្រងការលក់',
	  		'donors'=>'ផ្នែកសប្បុរសជន',
	  		'mong'=>'ផ្នែកម៉ុង/ចេតិយ',
	  		'report'=>'របាយការណ៍',
	  		'rsvacl'=>'អ្នកប្រើប្រាស់/កំណត់សិទ្ទ',
	  	);
?>
<table style="margin: 0 auto; width: 100%">
	<tr>
		<td>
			<fieldset>
				<legend><?php echo $tr->translate("កំណត់សិទ្ធអ្នកប្រើប្រាស់");?></legend>
				<table cellspacing="20" align="center" style="font-family: Khmer OS Battambang , Times New Roman;">
					<tr>
						<td width="20%"><?php echo $tr->translate("USER_TYPE");?></td>
						<td width="80%" class="add-edit">
							<input type="text" required="true" name="user_type" id="user_type" placeholder="User Type" 
								value="<?php echo $this->rs[0]['user_type'];?>"
								missingMessage="Invalid User type!" class='form-control' disabled/>
						</td>				
					</tr>			
				</table>
			</fieldset>	
		</td>
	</tr>
	<tr>
		<td>
			<fieldset>
				<legend style="font-family: Khmer OS Battambang , Times New Roman;"><?php echo $tr->translate("SEARCH");?></legend>
				<form name="frmsearch" action="" method="post">
					<table cellspacing="20" style="margin: 0 auto; width: 100%;font-family: Khmer OS Battambang , Times New Roman; ">
						<tr>
							<td width="10%">Module</td>
							<td width="30%">
								<select name="fmod" id="fmod" class='form-control select2me' missingMessage="Invalid Parent Name!" >
									<?php echo $this->optoin_mod;?>
								</select>
							</td>	
							<td width="10%"></td>
							<td width="10%">Controller</td>
							<td width="30%">
								<select name="fcon" id="fcon" class='form-control select2me' missingMessage="Invalid Parent Name!" >
									<?php echo $this->optoin_con;?>
								</select>
							</td>
							<td width="10%"></td>
						</tr>	
						<tr>	
							<td>Action</td>
							<td>
								<select name="fact" id="fact" class='form-control select2me'  missingMessage="Invalid Parent Name!" >
									<?php echo $this->optoin_act;?>
								</select>
							</td>	
							<td width="10%"></td>
							<td>Status</td>
							<td>
								<select name="fstatus" id="fstatus" class='form-control select2me' missingMessage="Invalid Parent Name!" >
									<?php echo $this->optoin_status;?>
								</select>
							</td>
							<td class="btn" align="center">
						   		<button type="submit" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-save"></i> <?php echo $tr->translate("Search")?> </button>
						    </td>					
						</tr>	
					</table>
				</form>
			</fieldset>
		</td>
	</tr>
	<tr>
		<td>
			<?php 
				$old_module = "";
			?>
			<div data-dojo-type="dijit/layout/TabContainer" style="width: 98%;height: 400px; overflow-y: auto;" tabPosition="left-h" tabStrip="true">
				
				<?php if(!empty($this->rows)){foreach ($this->rows as $key=>$rs){ ?>
					<?php if($old_module != $rs['module']){
					   if($key==0){
					?>
						<div data-dojo-type="dijit/layout/ContentPane" title="<?php echo $tr->translate($module_str[$rs['module']]);?>" >
							<table width="100%" border="1" style="white-space: nowrap;border: 1px solid #ccc;border-collapse: collapse;font-family: Khmer OS Battambang , Times New Roman;">
								<tr align="center" style="border:1px solid #4c6184 !important;background: #4b8df8;color:#ececec;">
									<td width="45%">
										<?php echo $tr->translate("សិទ្ធអ្នកប្រើប្រាស់");?>
									</td>
									<td width="45%">
										<?php echo $tr->translate("Url");?>
									</td>
									<td width="10%">
										<?php echo $tr->translate("ស្ថានការណ៍");?>
									</td>
								</tr>
							
						<?php }?>
					<?php  if($key>0){?>
							</table>
					 	</div>
					 	<div data-dojo-type="dijit/layout/ContentPane" title="<?php echo $tr->translate($module_str[$rs['module']]);?>" >
					 	<table width="100%" border="1" style="white-space: nowrap;border: 1px solid #ccc;border-collapse: collapse;font-family: Khmer OS Battambang , Times New Roman;">
					 		<tr align="center" style="border:1px solid #4c6184 !important;background: #4b8df8;color:#ececec;">
								<td width="45%">
									<?php echo $tr->translate("សិទ្ធអ្នកប្រើប្រាស់");?>
								</td>
								<td width="45%">
									<?php echo $tr->translate("Url");?>
								</td>
								<td width="10%">
									<?php echo $tr->translate("ស្ថានការណ៍");?>
								</td>
							</tr>
					<?php }}?>
							
							<?php if($rs['is_menu'] == 1){
										$space="";
										$style="style='font-weight:bold;'";
									}else{
										$space="&nbsp;&nbsp;&nbsp;";
										$style="";
									}
							?>
							<style>
								.hover:hover{background: #ccc;}
							</style>
							<tr class="hover">
								<td <?php echo $style;?>>
									&nbsp;&nbsp; <?php echo $space.$tr->translate($rs['label']);?>
								</td>
								<td>
									&nbsp;&nbsp; <?php echo $rs['url']?>
								</td>
								<td align="center">
									<?php echo $rs['img']?>
								</td>
							</tr>
						
					<?php 
						
						//echo $rs['url'].$rs['img']."<br />";
						$old_module = $rs['module'];
					?>
				<?php }}?>
					</table>
				</div>
			</div>
		</td>
	</tr>
</table>
		
<style>
	.pointer{
		cursor: pointer;	
	}
</style>
<script>
	$(function(){		
		$('#fmod').val('<?php echo $df['fmod']?>');
		$('#fcon').val('<?php echo $df['fcon']?>');
		$('#fact').val('<?php echo $df['fact']?>');
		$('#fstatus').val('<?php echo $df['fstatus']?>');
	});
	
	function changeStatus(id, user_type){
		url = "<?php echo BASE_URL;?>/rsvacl/useraccess/update-status";
		status = "no";
		none_src = "<?php echo BASE_URL?>/images/icon/none.png";
		tick_src = "<?php echo BASE_URL?>/images/icon/tick.png";

		if( $("#img_" + id).attr("src") == tick_src){
			status = "yes";
		}
		
		$.post( url, { 'acl_id': id, 'status': status, 'user_type_id':user_type},
	      function( data ) {
			 img_src = none_src;
	         if(data == "yes"){
				img_src = tick_src;
	         }	         
	         $("#img_" + id).attr("src", img_src);
	      }
	    );
	}
</script>