<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title>ប្រវត្តិបង់ប្រាក់ថ្លៃបញ្ជាទិញ</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("តារាងបញ្ជាទិញ");?>
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
					 <ul class="dropdown-menu" role="menu">
						<li>
							<a href="#" onclick="doPrint();">
								<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
							</a>
						</li>
						<li>
							<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
						</li>
					</ul>
				</div>
			</div>
    <div class="portlet-body form frmfilter">
	<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
			            	<tr>
			                	<td width="20%" valign="top"></td>
			                	<td width="60%" valign="top">
			                		<ul>
			                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'">ប្រវត្តិបង់ប្រាក់ថ្លៃបញ្ជាទិញ</li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
		            	</tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel"><br />
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
			                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td width="5%">&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td width="15%"><?php echo $tr->translate("អ្នកផ្គត់ផ្គង់");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("លេខបញ្ជាទិញ");?></td>
								<td width="15%">&nbsp;<?php echo $tr->translate("ថ្ងៃចំណាយ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ចំណាយជា");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("តម្លៃសរុប");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ប្រាក់បានបង់");?></td>
								<td width="10%"><?php echo $tr->translate("ប្រាក់នៅខ្វះ");?></td>
								<td width="15%"><?php echo $tr->translate("សម្គាល់");?></td>
			                </tr>
			                <?php $num=1; 
			                if(!empty($this->purchase_payment)){foreach ($this->purchase_payment AS $index => $rs){?>
							
							<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["vendor_name"];?></td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $rs["order_number"];?></td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["expense_date"]));?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["payment_type"];?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo "$ ".number_format($rs["total"],2);?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo "$ ".number_format($rs["paid"],2);?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo "$ ".number_format($rs["balance"],2);?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["remark"];?></td>
							</tr>
	                    	<?php }}?>
		                </tbody>
		           </table>
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint(){
	var divToPrint = document.getElementById('divPrint');
	var htmlToPrint = '' +'<style type="text/css">' +'</style>';
	htmlToPrint += divToPrint.outerHTML;
	window.document.write(htmlToPrint);
	window.print();
	window.close();
}

</script>
