<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
?>
<title>របាយការណ៍ ជំពាក់អ្នកផ្គត់ផ្គង់</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("Suppliyer Balance");?>
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
					 <ul class="dropdown-menu" role="menu">
						<li>
							<a href="#" onclick="doPrint();">
								<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
							</a>
						</li>
						<li>
							<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
						</li>
					 </ul>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<div class="form-group" style="padding-top: 6px;">
						<?php $formFilter = $this->form_salemong; ?>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('ad_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch');?></label>
						<label class="control-label col-md-2">
							<select name="paid_type" id="paid_type" class="form-control select2me" >
								<option value="0" <?php if($this->rssearch['paid_type']==0){echo "selected='selected'";}?>>ជ្រើសរើសប្រភេទ</option>
								<option value="1" <?php if($this->rssearch['paid_type']==1){echo "selected='selected'";}?>>បង់ប្រាក់ថ្លៃទិញទំនិញ</option>
								<option value="2" <?php if($this->rssearch['paid_type']==2){echo "selected='selected'";}?>>បង់ប្រាក់ថ្លៃជួលសេវាកម្ម</option>
								<option value="3" <?php if($this->rssearch['paid_type']==3){echo "selected='selected'";}?>>បង់ប្រាក់ថ្លៃជាង</option>
							</select>
						</label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div><div style="clear:both;"></div>	
				</form> 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 11px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 29px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
				<tr>
			    	<td align="center">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
			            	<tbody>
				            	<tr>
				                	<td align="center" width="16%" valign="top"><img  height="95px" src="<?php echo $this->baseUrl();?>/images/logosbona.jpg"></td>
				                	<td width="70%" valign="top">
				                		<ul>
				                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light'; color: #F31A1A  !important"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
				                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'; color: #F31A1A  !important">របាយការណ៏ ទិញចូលមិនទាន់ទូទាត់(ជំពាក់)</li>
				                			<li style="text-align:center; font-size:14px; color: #F31A1A  !important"><?php if(!empty($this->rssearch['start_date'])){?><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));}?></li>
				                		</ul>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
			            	</tbody>
			            </table>
			        </td>
			    </tr>
			    <tr>
			    	<td class="table2excel" id="exportExcel">
			            <?php if(!empty($this->purchase_payment)){?>
			            <table style="border-collapse:collapse;" width="100%"  cellspacing="0">
			                <tr>
			                    <td style="font-size:14px;font-weight: bold;">បង់ប្រាក់ថ្លៃទិញទំនិញ</td>
			                </tr>
			            </table>
			            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
			                 <tbody>
			                 <tr bgcolor="#b0bdfd" align="center" style="font-weight:bold; line-height: 28px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td width="5%">&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td width="15%"><?php echo $tr->translate("អ្នកផ្គត់ផ្គង់");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("លេខបញ្ជាទិញ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ថ្ងៃចំណាយ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ចំណាយជា");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("តម្លៃសរុប");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ប្រាក់បានបង់");?></td>
								<td width="10%"><?php echo $tr->translate("ប្រាក់នៅខ្វះ");?></td>
								<td width="12%"><?php echo $tr->translate("សម្គាល់");?></td>
								<td width="8%">&nbsp;<?php echo $tr->translate("ស្ថានភាព");?></td>
			                </tr>
			                <?php $num=1; $purchase_balance=0;
			                foreach ($this->purchase_payment AS $index => $rs){?>
							<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;font-size:13px;">
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["vendor_name"];?></td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $rs["order_number"];?></td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["expense_date"]));?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["payment_type"];?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["total"],2);?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["paid"],2);?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["balance"],2);?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["remark"];?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["status"];?></td>
							</tr>
							<?php }?>
			                </tbody>
			           </table>
			           <?php }?>
			           
			           
			           <?php if(!empty($this->partner_service_payment)){?>
			           <br />
			           <table style="border-collapse:collapse;font-size:12px;" width="100%"  cellspacing="0">
			                <tr>
			                    <td style="font-size:14px;font-weight: bold;">បង់ប្រាក់ថ្លៃជួលសេវាកម្ម</td>
			                </tr>
			           </table>
			            
			            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;margin-top: 0px;" width="100%" cellspacing="0">
			                 <tbody>
			                  <tr bgcolor="#b0bdfd" align="center" style="font-weight:bold; line-height: 28px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td width="5%">&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td width="15%"><?php echo $tr->translate("លេខវិក័យបត្រ");?></td>
								<td width="15%">&nbsp;<?php echo $tr->translate("ថ្ងៃចំណាយ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ចំណាយជា");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("តម្លៃសរុប");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ប្រាក់បានបង់");?></td>
								<td width="10%"><?php echo $tr->translate("ប្រាក់នៅខ្វះ");?></td>
								<td width="12%"><?php echo $tr->translate("សម្គាល់");?></td>
								<td width="8%">&nbsp;<?php echo $tr->translate("ស្ថានភាព");?></td>
			                </tr>
			                <?php $num=1; $partner_service_balance=0;
			                foreach ($this->partner_service_payment AS $index => $rs){?>
							<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;font-size:13px;">
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["sale_no"];?></td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_payment"]));?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["payment_type"];?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["total_payment"],2);?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["paid"],2);?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["balance"],2);?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["note"];?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["status"];?></td>
							</tr>
							<?php }?>
			                </tbody>
			           </table>
			           <?php }?>
			           
			           <?php if(!empty($this->constructor_payment)){?>
			           <br />
			           <table style="border-collapse:collapse;font-size:12px;" width="100%"  cellspacing="0">
			                <tr>
			                    <td style="font-size:14px;font-weight: bold;">បង់ប្រាក់ថ្លៃជាង</td>
			                </tr>
			           </table>
			            
			            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;margin-top: 0px;" width="100%" cellspacing="0">
			                 <tbody>
			                  <tr bgcolor="#b0bdfd" align="center" style="font-weight:bold; line-height: 28px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td width="5%">&nbsp;<?php echo $tr->translate("ល.រ");?></td>
								<td width="15%"><?php echo $tr->translate("លេខវិក័យបត្រ");?></td>
								<td width="15%">&nbsp;<?php echo $tr->translate("ថ្ងៃចំណាយ");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ចំណាយជា");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("តម្លៃសរុប");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("ប្រាក់បានបង់");?></td>
								<td width="10%"><?php echo $tr->translate("ប្រាក់នៅខ្វះ");?></td>
								<td width="12%"><?php echo $tr->translate("សម្គាល់");?></td>
								<td width="8%">&nbsp;<?php echo $tr->translate("ស្ថានភាព");?></td>
			                </tr>
			                <?php $num=1; $partner_service_balance=0;
			                foreach ($this->constructor_payment AS $index => $rs){?>
							<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;font-size:13px;">
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["invoice_no"];?></td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_payment"]));?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["payment_type"];?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["total_payment"],2);?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["paid"],2);?></td>
							   <td style="font-family: 'Open Sans', sans-serif;font-weight: bold;">&nbsp;<?php echo "$ ".number_format($rs["balance"],2);?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["note"];?></td>
							   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["status"];?></td>
							</tr>
							<?php }?>
			                </tbody>
			           </table>
			           <?php }?>
			           <br>
			           <br>
			           <table align="center" width="100%">
							<tbody>
							   <tr style="font-size: 11px;">
							        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
							        <th></th>
							        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
							        <th></th>
							        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
							   </tr>
							</tbody>
						</table>	
		    		</td>
		    	</tr>
			</tbody>
			</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
