<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$brach_name =  $this->branch;
?>
<title><?php echo $tr->translate("RPT_PURCHASE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("RPT_PURCHASE");?>
				</div>
				<div class="btn-group pull-right">
					 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
					   Actions <i class="fa fa-angle-down"></i>
					 </button>
					<ul class="dropdown-menu" role="menu">
						<li>
							<a href="#" onclick="doPrint();">
								<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
							</a>
						</li>
						<li>
							<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
						</li>							
					</ul>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="<?php //echo $formFilter->getAction(); ?>" autocomplete="off">
					<?php $formFilter = $this->form_salemong; ?>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('ad_search');?></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('branch');?></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-2"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2"><?php echo $formFilter->getElement('status');?></label>
					
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>
					<div style="clear:both;"></div>	
				</form> 
			</div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 14px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td align="center" width="16%" valign="top"><img  height="95px" src="/bunastock/trunk/public/images/logosbona.jpg"></td>
		                	<td width="70%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("RPT_PURCHASE");?></li>
		                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->rssearch['start_date'])){?><?php echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));}?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;"></td>
		                				<td width="65%"></td>
		                			</tr>
				                	</tbody>
				                </table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table  border="1" style="border-collapse:collapse;border:1px solid #000; font-size:14px;" width="100%" cellspacing="0">
		                 <thead>
		                 	<tr bgcolor="#b0bdfd" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                    <td><?php echo $tr->translate("ល.រ");?></td>
								<td><?php echo $tr->translate("សាខា");?></td>
								<td><?php echo $tr->translate("អ្នកផ្គត់ផ្គង់");?></td>
								<td><?php echo $tr->translate("លេខបញ្ជាទិញ");?></td>
								<td><?php echo $tr->translate("ថ្ងៃបញ្ជាទិញ");?></td>
								<td><?php echo $tr->translate("ប្រាក់ត្រូវបង់");?></td>
								<td><?php echo $tr->translate("ប្រាក់បានបង់");?></td>
								<td><?php echo $tr->translate("ជំពាក់");?></td>
								<td><?php echo $tr->translate("ស្ថានការ");?></td>
						        <td><?php echo $tr->translate("អ្នកប្រើប្រាស់");?></td>
						        <td><?php echo $tr->translate("ប្រវត្តិ");?></td>
		               	 	</tr>
		                <thead>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->repurchase)){foreach ($this->repurchase AS $index => $rs){?>
		                
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000; <?php if($rs["balance"]<=0){echo"background:#d5daff;";}?>">
						   <td align="center">&nbsp;<?php echo $index+1?></td>
						   <td><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["branch_name"];?></a></td>
						   <td><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["vendor_name"];?></a></td>
						   <td align="center"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/purproductdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["order_number"];?></a></td>
						   <td align="center">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date_order"]));?></td>
						   <td>&nbsp;<?php echo "$ ".number_format($rs["total_payment"],2);?></td>
						   <td>&nbsp;<?php echo "$ ".number_format($rs["paid"],2);?></td>
						   <td>&nbsp;<?php echo "$ ".number_format($rs["balance"],2);?></td>
						   <td>&nbsp;<?php echo $rs["purchase_status"];?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						   <td align="center"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/index/rpt-purchase-payment/id/".$rs["id"];?>">បង់ប្រាក់</a></td>
						</tr>
						   <?php 
							$d_netotal = $d_netotal+$rs["total_payment"];
							$d_paid = $d_paid+$rs["paid"];
							$d_balance = $d_balance+$rs["balance"];
                    	}}?>
		                </tbody>
		           </table>
		            <br>
		             <table border="1" align="center" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="50%" cellspacing="0">
		                <tbody>
			                <tr height="30px;" bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 14px; font-size:12px; padding:2px 0px; ">
			                    <td><strong><?php echo $tr->translate("ទឹកប្រាក់ទិញសរុប");?></strong></td>
			                    <td><strong><?php echo $tr->translate("ប្រាក់បានបង់សរុប");?></strong></td>
			                    <td><strong><?php echo $tr->translate("នៅខ្វះសរុប");?></strong></td>
			                </tr>
			                 <tr align="center" class="style" style=" line-height: 24px; font-size:11px;">
			                    <td>&nbsp;<?php echo "$ ".number_format($d_netotal,2);?>&nbsp;</td>
			                    <td>&nbsp;<?php echo "$ ".number_format($d_paid,2);?>&nbsp;</td>
			                    <td>&nbsp;<?php echo "$ ".number_format($d_balance,2);?>&nbsp;</td>
			                 </tr>
		               </tbody>
		             </table>
		             
		              <br>
		              <table align="center" width="100%">
						   <tbody>
						   	<tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
