<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
?>
<title>Mong Payment Report</title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("របាយការណ៍ ប្រវត្តិបង់ប្រាក់");?>
				</div>
					<div class="btn-group pull-right">
						 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
						   Actions <i class="fa fa-angle-down"></i>
						 </button>
						<ul class="dropdown-menu" role="menu">
							<li>
								<a href="#" onclick="doPrint();">
									<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
								</a>
							</li>
							<li>
								<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
							</li>
						</ul>
				 </div>
			</div>
			
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
		<style>
			.style{
				line-height: 25px;font-size: 12px !important;
				font-family: 'Khmer OS Battambang';
			}
			ul{margin: 0;padding:0;}
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
			th{padding: 5px;}
			.hover:hover{background: #ccc;}
			table { page-break-inside:auto }
			tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
		</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody>
			            	<tr>
			                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="55px"></td>
			                	<td width="60%" valign="top">
			                		<ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
			                			<li style="text-align:center; font-size:15px; font-family:'Khmer OS Battambang'"><?php echo $tr->translate("របាយការណ៍ ប្រវត្តិបង់ប្រាក់");?></li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
			                <tr>
			                	<td colspan="3" valign="top">
			                		&nbsp;
								</td>
							</tr>   
		            	</tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <thead>
			                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
								<td><?php echo $tr->translate("BRANCH_NAME");?></td>
								<td width="10%">&nbsp;<?php echo $tr->translate("វិក័យបត្រ");?></td>
								<td>&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?></td>
								<td><?php echo $tr->translate("លេខទូរស័ព្ទ");?></td>
								
								<td>&nbsp;<?php echo $tr->translate("TOTAL");?></td>
								<td>&nbsp;<?php echo $tr->translate("PAID");?></td>
								<td>&nbsp;<?php echo $tr->translate("BALANCE");?></td>
								
								<td>&nbsp;<?php echo $tr->translate("NOTE");?></td>
								<td>&nbsp;<?php echo $tr->translate("ថ្ងៃបង់");?></td>
								<td>&nbsp;<?php echo $tr->translate("BY_USER");?></td>
								<td>&nbsp;<?php echo $tr->translate("PRINT");?></td>
			                </tr>
		                </thead>
		                <tbody>
		                <?php $i=0; $count = count($this->rsreceipt);
		                if(!empty($this->rsreceipt)){foreach ($this->rsreceipt AS $index => $rs){$i++;?>
						<tr class='hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $i;?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["branch_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["invoice_no"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["cust_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["phone"];?></td>
						  
						   <td style="white-space: nowrap;">&nbsp;<?php echo "$ ".number_format($rs["total"],2);?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo "$ ".number_format($rs["paid"],2);?></td>
						   <td <?php if($rs["balance"]>0 && $count==$i){echo "style='color:red'";}?>>&nbsp;<?php echo "$ ".number_format($rs["balance"],2);?></td>
						  
						   <td>&nbsp;<?php echo $rs["remark"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($rs["receipt_date"]));?></td>
						   <td>&nbsp;<?php echo $rs["user_name"];?></td>
						   <td align="center"><a style="text-decoration: none;color:#000;" href="<?php echo $this->baseUrl()."/mong/customerpayment/receipt/id/".$rs["id"];?>" target="_blank">បង្កាន់ដៃ</a></td>
						</tr>
						   
                    	<?php }}?>
		                </tbody>
		           </table>
	               <br>
	               <table align="center" width="100%">
					   <tbody>
					   		<tr style="font-size: 14px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
					   		</tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
